/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * BlowFish - Enigma API Service
 * OpenAPI spec version: default_version
 */
import type {
    ErrorResponse,
    FeeCreate,
    FeeUpdate,
    HTTPValidationError,
    MerchantCreate,
    MerchantEndpointsListMerchantsEnigmaV1MerchantGetParams,
    MerchantUpdate
} from "../blowFishEnigmaAPIService.schemas";

/**
 * Returns a paginated list of merchants. Supports filtering based on query parameters.
 * @summary Get a list of merchants with filtering and pagination
 */
export type merchantEndpointsListMerchantsEnigmaV1MerchantGetResponse = {
    data: ErrorResponse | HTTPValidationError;
    status: number;
    headers: Headers;
};

export const getMerchantEndpointsListMerchantsEnigmaV1MerchantGetUrl = (
    params?: MerchantEndpointsListMerchantsEnigmaV1MerchantGetParams
) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? "null" : value.toString());
        }
    });

    return normalizedParams.size
        ? `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/merchant?${normalizedParams.toString()}`
        : `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/merchant`;
};

export const merchantEndpointsListMerchantsEnigmaV1MerchantGet = async (
    params?: MerchantEndpointsListMerchantsEnigmaV1MerchantGetParams,
    options?: RequestInit
): Promise<merchantEndpointsListMerchantsEnigmaV1MerchantGetResponse> => {
    const res = await fetch(getMerchantEndpointsListMerchantsEnigmaV1MerchantGetUrl(params), {
        ...options,
        method: "GET"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();
    const data: merchantEndpointsListMerchantsEnigmaV1MerchantGetResponse["data"] = body ? JSON.parse(body) : {};

    return {
        data,
        status: res.status,
        headers: res.headers
    } as merchantEndpointsListMerchantsEnigmaV1MerchantGetResponse;
};

/**
 * Adds a new merchant to the database using the provided details.
 * @summary Create a new merchant entry
 */
export type merchantEndpointsCreateMerchantEnigmaV1MerchantPostResponse = {
    data: ErrorResponse | HTTPValidationError;
    status: number;
    headers: Headers;
};

export const getMerchantEndpointsCreateMerchantEnigmaV1MerchantPostUrl = () => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/merchant`;
};

export const merchantEndpointsCreateMerchantEnigmaV1MerchantPost = async (
    merchantCreate: MerchantCreate,
    options?: RequestInit
): Promise<merchantEndpointsCreateMerchantEnigmaV1MerchantPostResponse> => {
    const res = await fetch(getMerchantEndpointsCreateMerchantEnigmaV1MerchantPostUrl(), {
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(merchantCreate)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();
    const data: merchantEndpointsCreateMerchantEnigmaV1MerchantPostResponse["data"] = body ? JSON.parse(body) : {};

    return {
        data,
        status: res.status,
        headers: res.headers
    } as merchantEndpointsCreateMerchantEnigmaV1MerchantPostResponse;
};

/**
 * Fetches details of a merchant identified by its unique merchant ID.
 * @summary Get details of a specific merchant
 */
export type merchantEndpointsGetMerchantEnigmaV1MerchantMerchantIdGetResponse = {
    data: ErrorResponse | HTTPValidationError;
    status: number;
    headers: Headers;
};

export const getMerchantEndpointsGetMerchantEnigmaV1MerchantMerchantIdGetUrl = (merchantId: string) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/merchant/${merchantId}`;
};

export const merchantEndpointsGetMerchantEnigmaV1MerchantMerchantIdGet = async (
    merchantId: string,
    options?: RequestInit
): Promise<merchantEndpointsGetMerchantEnigmaV1MerchantMerchantIdGetResponse> => {
    const res = await fetch(getMerchantEndpointsGetMerchantEnigmaV1MerchantMerchantIdGetUrl(merchantId), {
        ...options,
        method: "GET"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();
    const data: merchantEndpointsGetMerchantEnigmaV1MerchantMerchantIdGetResponse["data"] = body
        ? JSON.parse(body)
        : {};

    return {
        data,
        status: res.status,
        headers: res.headers
    } as merchantEndpointsGetMerchantEnigmaV1MerchantMerchantIdGetResponse;
};

/**
 * Modifies the details of a merchant identified by its merchant ID.
 * @summary Update an existing merchant
 */
export type merchantEndpointsUpdateMerchantEnigmaV1MerchantMerchantIdPutResponse = {
    data: ErrorResponse | HTTPValidationError;
    status: number;
    headers: Headers;
};

export const getMerchantEndpointsUpdateMerchantEnigmaV1MerchantMerchantIdPutUrl = (merchantId: string) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/merchant/${merchantId}`;
};

export const merchantEndpointsUpdateMerchantEnigmaV1MerchantMerchantIdPut = async (
    merchantId: string,
    merchantUpdate: MerchantUpdate,
    options?: RequestInit
): Promise<merchantEndpointsUpdateMerchantEnigmaV1MerchantMerchantIdPutResponse> => {
    const res = await fetch(getMerchantEndpointsUpdateMerchantEnigmaV1MerchantMerchantIdPutUrl(merchantId), {
        ...options,
        method: "PUT",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(merchantUpdate)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();
    const data: merchantEndpointsUpdateMerchantEnigmaV1MerchantMerchantIdPutResponse["data"] = body
        ? JSON.parse(body)
        : {};

    return {
        data,
        status: res.status,
        headers: res.headers
    } as merchantEndpointsUpdateMerchantEnigmaV1MerchantMerchantIdPutResponse;
};

/**
 * Removes a merchant from the database using its unique merchant ID.
 * @summary Delete a merchant entry
 */
export type merchantEndpointsDeleteMerchantEnigmaV1MerchantMerchantIdDeleteResponse = {
    data: ErrorResponse | HTTPValidationError;
    status: number;
    headers: Headers;
};

export const getMerchantEndpointsDeleteMerchantEnigmaV1MerchantMerchantIdDeleteUrl = (merchantId: string) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/merchant/${merchantId}`;
};

export const merchantEndpointsDeleteMerchantEnigmaV1MerchantMerchantIdDelete = async (
    merchantId: string,
    options?: RequestInit
): Promise<merchantEndpointsDeleteMerchantEnigmaV1MerchantMerchantIdDeleteResponse> => {
    const res = await fetch(getMerchantEndpointsDeleteMerchantEnigmaV1MerchantMerchantIdDeleteUrl(merchantId), {
        ...options,
        method: "DELETE"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();
    const data: merchantEndpointsDeleteMerchantEnigmaV1MerchantMerchantIdDeleteResponse["data"] = body
        ? JSON.parse(body)
        : {};

    return {
        data,
        status: res.status,
        headers: res.headers
    } as merchantEndpointsDeleteMerchantEnigmaV1MerchantMerchantIdDeleteResponse;
};

/**
 * Associates a new fee with a specified merchant.
 * @summary Add a new fee to a merchant
 */
export type merchantEndpointsAddFeeEnigmaV1MerchantMerchantIdFeePatchResponse = {
    data: ErrorResponse | HTTPValidationError;
    status: number;
    headers: Headers;
};

export const getMerchantEndpointsAddFeeEnigmaV1MerchantMerchantIdFeePatchUrl = (merchantId: string) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/merchant/${merchantId}/fee`;
};

export const merchantEndpointsAddFeeEnigmaV1MerchantMerchantIdFeePatch = async (
    merchantId: string,
    feeCreate: FeeCreate,
    options?: RequestInit
): Promise<merchantEndpointsAddFeeEnigmaV1MerchantMerchantIdFeePatchResponse> => {
    const res = await fetch(getMerchantEndpointsAddFeeEnigmaV1MerchantMerchantIdFeePatchUrl(merchantId), {
        ...options,
        method: "PATCH",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(feeCreate)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();
    const data: merchantEndpointsAddFeeEnigmaV1MerchantMerchantIdFeePatchResponse["data"] = body
        ? JSON.parse(body)
        : {};

    return {
        data,
        status: res.status,
        headers: res.headers
    } as merchantEndpointsAddFeeEnigmaV1MerchantMerchantIdFeePatchResponse;
};

/**
 * Modifies an existing fee associated with a specified merchant.
 * @summary Update an existing fee for a merchant
 */
export type merchantEndpointsUpdateFeeEnigmaV1MerchantMerchantIdFeeFeeIdPatchResponse = {
    data: ErrorResponse | HTTPValidationError;
    status: number;
    headers: Headers;
};

export const getMerchantEndpointsUpdateFeeEnigmaV1MerchantMerchantIdFeeFeeIdPatchUrl = (
    merchantId: string,
    feeId: string
) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/merchant/${merchantId}/fee/${feeId}`;
};

export const merchantEndpointsUpdateFeeEnigmaV1MerchantMerchantIdFeeFeeIdPatch = async (
    merchantId: string,
    feeId: string,
    feeUpdate: FeeUpdate,
    options?: RequestInit
): Promise<merchantEndpointsUpdateFeeEnigmaV1MerchantMerchantIdFeeFeeIdPatchResponse> => {
    const res = await fetch(
        getMerchantEndpointsUpdateFeeEnigmaV1MerchantMerchantIdFeeFeeIdPatchUrl(merchantId, feeId),
        {
            ...options,
            method: "PATCH",
            headers: { "Content-Type": "application/json", ...options?.headers },
            body: JSON.stringify(feeUpdate)
        }
    );

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();
    const data: merchantEndpointsUpdateFeeEnigmaV1MerchantMerchantIdFeeFeeIdPatchResponse["data"] = body
        ? JSON.parse(body)
        : {};

    return {
        data,
        status: res.status,
        headers: res.headers
    } as merchantEndpointsUpdateFeeEnigmaV1MerchantMerchantIdFeeFeeIdPatchResponse;
};

/**
 * Deletes a specific fee associated with a given merchant.
 * @summary Remove a fee from a merchant
 */
export type merchantEndpointsDeleteFeeEnigmaV1MerchantMerchantIdFeeFeeIdDeleteResponse = {
    data: ErrorResponse | HTTPValidationError;
    status: number;
    headers: Headers;
};

export const getMerchantEndpointsDeleteFeeEnigmaV1MerchantMerchantIdFeeFeeIdDeleteUrl = (
    merchantId: string,
    feeId: string
) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/merchant/${merchantId}/fee/${feeId}`;
};

export const merchantEndpointsDeleteFeeEnigmaV1MerchantMerchantIdFeeFeeIdDelete = async (
    merchantId: string,
    feeId: string,
    options?: RequestInit
): Promise<merchantEndpointsDeleteFeeEnigmaV1MerchantMerchantIdFeeFeeIdDeleteResponse> => {
    const res = await fetch(
        getMerchantEndpointsDeleteFeeEnigmaV1MerchantMerchantIdFeeFeeIdDeleteUrl(merchantId, feeId),
        {
            ...options,
            method: "DELETE"
        }
    );

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();
    const data: merchantEndpointsDeleteFeeEnigmaV1MerchantMerchantIdFeeFeeIdDeleteResponse["data"] = body
        ? JSON.parse(body)
        : {};

    return {
        data,
        status: res.status,
        headers: res.headers
    } as merchantEndpointsDeleteFeeEnigmaV1MerchantMerchantIdFeeFeeIdDeleteResponse;
};
