/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * BlowFish - Enigma API Service
 * OpenAPI spec version: local
 */
import type {
    ApiResponseDictStrStr,
    ApiResponseMerchantCascadeRead,
    ApiResponseMergedCascadeView,
    ApiResponseOffsetPaginationMerchantCascadeRead,
    ApiResponseOffsetPaginationMerchantCascadeWithDetails,
    HTTPValidationError,
    MerchantCascadeCreate,
    MerchantCascadeEndpointsGetMergedCascadeViewEnigmaV1MerchantCascadeMerchantMerchantIdMergedViewGetParams,
    MerchantCascadeEndpointsListCascadesForMerchantEnigmaV1MerchantCascadeMerchantMerchantIdGetParams,
    MerchantCascadeEndpointsListMerchantCascadesEnigmaV1MerchantCascadeGetParams,
    MerchantCascadeEndpointsListMerchantsForCascadeEnigmaV1MerchantCascadeCascadeCascadeIdGetParams,
    MerchantCascadeUpdate
} from "../blowFishEnigmaAPIService.schemas";

import { authFetch } from "../../../helpers/orvalAuthFetchMiddleware";

/**
 * Returns a paginated list of merchant cascade assignments with filtering
 * @summary Get merchant cascade assignments
 */
export type merchantCascadeEndpointsListMerchantCascadesEnigmaV1MerchantCascadeGetResponse200 = {
    data: ApiResponseOffsetPaginationMerchantCascadeRead;
    status: 200;
};

export type merchantCascadeEndpointsListMerchantCascadesEnigmaV1MerchantCascadeGetResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type merchantCascadeEndpointsListMerchantCascadesEnigmaV1MerchantCascadeGetResponseComposite =
    | merchantCascadeEndpointsListMerchantCascadesEnigmaV1MerchantCascadeGetResponse200
    | merchantCascadeEndpointsListMerchantCascadesEnigmaV1MerchantCascadeGetResponse422;

export type merchantCascadeEndpointsListMerchantCascadesEnigmaV1MerchantCascadeGetResponse =
    merchantCascadeEndpointsListMerchantCascadesEnigmaV1MerchantCascadeGetResponseComposite & {
        headers: Headers;
    };

export const getMerchantCascadeEndpointsListMerchantCascadesEnigmaV1MerchantCascadeGetUrl = (
    params: MerchantCascadeEndpointsListMerchantCascadesEnigmaV1MerchantCascadeGetParams
) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? "null" : value.toString());
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/merchant_cascade?${stringifiedParams}`
        : `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/merchant_cascade`;
};

export const merchantCascadeEndpointsListMerchantCascadesEnigmaV1MerchantCascadeGet = async (
    params: MerchantCascadeEndpointsListMerchantCascadesEnigmaV1MerchantCascadeGetParams,
    options?: RequestInit
): Promise<merchantCascadeEndpointsListMerchantCascadesEnigmaV1MerchantCascadeGetResponse> => {
    return authFetch<merchantCascadeEndpointsListMerchantCascadesEnigmaV1MerchantCascadeGetResponse>(
        getMerchantCascadeEndpointsListMerchantCascadesEnigmaV1MerchantCascadeGetUrl(params),
        {
            ...options,
            method: "GET"
        }
    );
};

/**
 * Assigns a cascade to a merchant with specified configuration
 * @summary Assign cascade to merchant
 */
export type merchantCascadeEndpointsAssignCascadeToMerchantEnigmaV1MerchantCascadePostResponse200 = {
    data: ApiResponseMerchantCascadeRead;
    status: 200;
};

export type merchantCascadeEndpointsAssignCascadeToMerchantEnigmaV1MerchantCascadePostResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type merchantCascadeEndpointsAssignCascadeToMerchantEnigmaV1MerchantCascadePostResponseComposite =
    | merchantCascadeEndpointsAssignCascadeToMerchantEnigmaV1MerchantCascadePostResponse200
    | merchantCascadeEndpointsAssignCascadeToMerchantEnigmaV1MerchantCascadePostResponse422;

export type merchantCascadeEndpointsAssignCascadeToMerchantEnigmaV1MerchantCascadePostResponse =
    merchantCascadeEndpointsAssignCascadeToMerchantEnigmaV1MerchantCascadePostResponseComposite & {
        headers: Headers;
    };

export const getMerchantCascadeEndpointsAssignCascadeToMerchantEnigmaV1MerchantCascadePostUrl = () => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/merchant_cascade`;
};

export const merchantCascadeEndpointsAssignCascadeToMerchantEnigmaV1MerchantCascadePost = async (
    merchantCascadeCreate: MerchantCascadeCreate,
    options?: RequestInit
): Promise<merchantCascadeEndpointsAssignCascadeToMerchantEnigmaV1MerchantCascadePostResponse> => {
    return authFetch<merchantCascadeEndpointsAssignCascadeToMerchantEnigmaV1MerchantCascadePostResponse>(
        getMerchantCascadeEndpointsAssignCascadeToMerchantEnigmaV1MerchantCascadePostUrl(),
        {
            ...options,
            method: "POST",
            headers: { "Content-Type": "application/json", ...options?.headers },
            body: JSON.stringify(merchantCascadeCreate)
        }
    );
};

/**
 * Fetches details of a merchant cascade assignment by its ID
 * @summary Get merchant cascade assignment details
 */
export type merchantCascadeEndpointsGetMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdGetResponse200 = {
    data: ApiResponseMerchantCascadeRead;
    status: 200;
};

export type merchantCascadeEndpointsGetMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdGetResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type merchantCascadeEndpointsGetMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdGetResponseComposite =
    | merchantCascadeEndpointsGetMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdGetResponse200
    | merchantCascadeEndpointsGetMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdGetResponse422;

export type merchantCascadeEndpointsGetMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdGetResponse =
    merchantCascadeEndpointsGetMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdGetResponseComposite & {
        headers: Headers;
    };

export const getMerchantCascadeEndpointsGetMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdGetUrl = (
    merchantCascadeId: string
) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/merchant_cascade/${merchantCascadeId}`;
};

export const merchantCascadeEndpointsGetMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdGet = async (
    merchantCascadeId: string,
    options?: RequestInit
): Promise<merchantCascadeEndpointsGetMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdGetResponse> => {
    return authFetch<merchantCascadeEndpointsGetMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdGetResponse>(
        getMerchantCascadeEndpointsGetMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdGetUrl(merchantCascadeId),
        {
            ...options,
            method: "GET"
        }
    );
};

/**
 * Updates merchant cascade assignment configuration
 * @summary Update merchant cascade assignment
 */
export type merchantCascadeEndpointsUpdateMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdPutResponse200 = {
    data: ApiResponseMerchantCascadeRead;
    status: 200;
};

export type merchantCascadeEndpointsUpdateMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdPutResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type merchantCascadeEndpointsUpdateMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdPutResponseComposite =
    | merchantCascadeEndpointsUpdateMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdPutResponse200
    | merchantCascadeEndpointsUpdateMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdPutResponse422;

export type merchantCascadeEndpointsUpdateMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdPutResponse =
    merchantCascadeEndpointsUpdateMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdPutResponseComposite & {
        headers: Headers;
    };

export const getMerchantCascadeEndpointsUpdateMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdPutUrl = (
    merchantCascadeId: string
) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/merchant_cascade/${merchantCascadeId}`;
};

export const merchantCascadeEndpointsUpdateMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdPut = async (
    merchantCascadeId: string,
    merchantCascadeUpdate: MerchantCascadeUpdate,
    options?: RequestInit
): Promise<merchantCascadeEndpointsUpdateMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdPutResponse> => {
    return authFetch<merchantCascadeEndpointsUpdateMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdPutResponse>(
        getMerchantCascadeEndpointsUpdateMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdPutUrl(
            merchantCascadeId
        ),
        {
            ...options,
            method: "PUT",
            headers: { "Content-Type": "application/json", ...options?.headers },
            body: JSON.stringify(merchantCascadeUpdate)
        }
    );
};

/**
 * Removes a cascade assignment from a merchant
 * @summary Remove cascade from merchant
 */
export type merchantCascadeEndpointsRemoveCascadeFromMerchantEnigmaV1MerchantCascadeMerchantCascadeIdDeleteResponse200 =
    {
        data: ApiResponseDictStrStr;
        status: 200;
    };

export type merchantCascadeEndpointsRemoveCascadeFromMerchantEnigmaV1MerchantCascadeMerchantCascadeIdDeleteResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type merchantCascadeEndpointsRemoveCascadeFromMerchantEnigmaV1MerchantCascadeMerchantCascadeIdDeleteResponseComposite =

        | merchantCascadeEndpointsRemoveCascadeFromMerchantEnigmaV1MerchantCascadeMerchantCascadeIdDeleteResponse200
        | merchantCascadeEndpointsRemoveCascadeFromMerchantEnigmaV1MerchantCascadeMerchantCascadeIdDeleteResponse422;

export type merchantCascadeEndpointsRemoveCascadeFromMerchantEnigmaV1MerchantCascadeMerchantCascadeIdDeleteResponse =
    merchantCascadeEndpointsRemoveCascadeFromMerchantEnigmaV1MerchantCascadeMerchantCascadeIdDeleteResponseComposite & {
        headers: Headers;
    };

export const getMerchantCascadeEndpointsRemoveCascadeFromMerchantEnigmaV1MerchantCascadeMerchantCascadeIdDeleteUrl = (
    merchantCascadeId: string
) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/merchant_cascade/${merchantCascadeId}`;
};

export const merchantCascadeEndpointsRemoveCascadeFromMerchantEnigmaV1MerchantCascadeMerchantCascadeIdDelete = async (
    merchantCascadeId: string,
    options?: RequestInit
): Promise<merchantCascadeEndpointsRemoveCascadeFromMerchantEnigmaV1MerchantCascadeMerchantCascadeIdDeleteResponse> => {
    return authFetch<merchantCascadeEndpointsRemoveCascadeFromMerchantEnigmaV1MerchantCascadeMerchantCascadeIdDeleteResponse>(
        getMerchantCascadeEndpointsRemoveCascadeFromMerchantEnigmaV1MerchantCascadeMerchantCascadeIdDeleteUrl(
            merchantCascadeId
        ),
        {
            ...options,
            method: "DELETE"
        }
    );
};

/**
 * Returns all cascades assigned to a specific merchant
 * @summary Get cascades for merchant
 */
export type merchantCascadeEndpointsListCascadesForMerchantEnigmaV1MerchantCascadeMerchantMerchantIdGetResponse200 = {
    data: ApiResponseOffsetPaginationMerchantCascadeWithDetails;
    status: 200;
};

export type merchantCascadeEndpointsListCascadesForMerchantEnigmaV1MerchantCascadeMerchantMerchantIdGetResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type merchantCascadeEndpointsListCascadesForMerchantEnigmaV1MerchantCascadeMerchantMerchantIdGetResponseComposite =

        | merchantCascadeEndpointsListCascadesForMerchantEnigmaV1MerchantCascadeMerchantMerchantIdGetResponse200
        | merchantCascadeEndpointsListCascadesForMerchantEnigmaV1MerchantCascadeMerchantMerchantIdGetResponse422;

export type merchantCascadeEndpointsListCascadesForMerchantEnigmaV1MerchantCascadeMerchantMerchantIdGetResponse =
    merchantCascadeEndpointsListCascadesForMerchantEnigmaV1MerchantCascadeMerchantMerchantIdGetResponseComposite & {
        headers: Headers;
    };

export const getMerchantCascadeEndpointsListCascadesForMerchantEnigmaV1MerchantCascadeMerchantMerchantIdGetUrl = (
    merchantId: string,
    params: MerchantCascadeEndpointsListCascadesForMerchantEnigmaV1MerchantCascadeMerchantMerchantIdGetParams
) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? "null" : value.toString());
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/merchant_cascade/merchant/${merchantId}?${stringifiedParams}`
        : `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/merchant_cascade/merchant/${merchantId}`;
};

export const merchantCascadeEndpointsListCascadesForMerchantEnigmaV1MerchantCascadeMerchantMerchantIdGet = async (
    merchantId: string,
    params: MerchantCascadeEndpointsListCascadesForMerchantEnigmaV1MerchantCascadeMerchantMerchantIdGetParams,
    options?: RequestInit
): Promise<merchantCascadeEndpointsListCascadesForMerchantEnigmaV1MerchantCascadeMerchantMerchantIdGetResponse> => {
    return authFetch<merchantCascadeEndpointsListCascadesForMerchantEnigmaV1MerchantCascadeMerchantMerchantIdGetResponse>(
        getMerchantCascadeEndpointsListCascadesForMerchantEnigmaV1MerchantCascadeMerchantMerchantIdGetUrl(
            merchantId,
            params
        ),
        {
            ...options,
            method: "GET"
        }
    );
};

/**
 * Returns all merchants assigned to a specific cascade
 * @summary Get merchants for cascade
 */
export type merchantCascadeEndpointsListMerchantsForCascadeEnigmaV1MerchantCascadeCascadeCascadeIdGetResponse200 = {
    data: ApiResponseOffsetPaginationMerchantCascadeRead;
    status: 200;
};

export type merchantCascadeEndpointsListMerchantsForCascadeEnigmaV1MerchantCascadeCascadeCascadeIdGetResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type merchantCascadeEndpointsListMerchantsForCascadeEnigmaV1MerchantCascadeCascadeCascadeIdGetResponseComposite =

        | merchantCascadeEndpointsListMerchantsForCascadeEnigmaV1MerchantCascadeCascadeCascadeIdGetResponse200
        | merchantCascadeEndpointsListMerchantsForCascadeEnigmaV1MerchantCascadeCascadeCascadeIdGetResponse422;

export type merchantCascadeEndpointsListMerchantsForCascadeEnigmaV1MerchantCascadeCascadeCascadeIdGetResponse =
    merchantCascadeEndpointsListMerchantsForCascadeEnigmaV1MerchantCascadeCascadeCascadeIdGetResponseComposite & {
        headers: Headers;
    };

export const getMerchantCascadeEndpointsListMerchantsForCascadeEnigmaV1MerchantCascadeCascadeCascadeIdGetUrl = (
    cascadeId: string,
    params: MerchantCascadeEndpointsListMerchantsForCascadeEnigmaV1MerchantCascadeCascadeCascadeIdGetParams
) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? "null" : value.toString());
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/merchant_cascade/cascade/${cascadeId}?${stringifiedParams}`
        : `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/merchant_cascade/cascade/${cascadeId}`;
};

export const merchantCascadeEndpointsListMerchantsForCascadeEnigmaV1MerchantCascadeCascadeCascadeIdGet = async (
    cascadeId: string,
    params: MerchantCascadeEndpointsListMerchantsForCascadeEnigmaV1MerchantCascadeCascadeCascadeIdGetParams,
    options?: RequestInit
): Promise<merchantCascadeEndpointsListMerchantsForCascadeEnigmaV1MerchantCascadeCascadeCascadeIdGetResponse> => {
    return authFetch<merchantCascadeEndpointsListMerchantsForCascadeEnigmaV1MerchantCascadeCascadeCascadeIdGetResponse>(
        getMerchantCascadeEndpointsListMerchantsForCascadeEnigmaV1MerchantCascadeCascadeCascadeIdGetUrl(
            cascadeId,
            params
        ),
        {
            ...options,
            method: "GET"
        }
    );
};

/**
 * Returns a merged view of all cascades for a merchant with terminal conflict resolution
 * @summary Get merged cascade view for merchant
 */
export type merchantCascadeEndpointsGetMergedCascadeViewEnigmaV1MerchantCascadeMerchantMerchantIdMergedViewGetResponse200 =
    {
        data: ApiResponseMergedCascadeView;
        status: 200;
    };

export type merchantCascadeEndpointsGetMergedCascadeViewEnigmaV1MerchantCascadeMerchantMerchantIdMergedViewGetResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type merchantCascadeEndpointsGetMergedCascadeViewEnigmaV1MerchantCascadeMerchantMerchantIdMergedViewGetResponseComposite =

        | merchantCascadeEndpointsGetMergedCascadeViewEnigmaV1MerchantCascadeMerchantMerchantIdMergedViewGetResponse200
        | merchantCascadeEndpointsGetMergedCascadeViewEnigmaV1MerchantCascadeMerchantMerchantIdMergedViewGetResponse422;

export type merchantCascadeEndpointsGetMergedCascadeViewEnigmaV1MerchantCascadeMerchantMerchantIdMergedViewGetResponse =
    merchantCascadeEndpointsGetMergedCascadeViewEnigmaV1MerchantCascadeMerchantMerchantIdMergedViewGetResponseComposite & {
        headers: Headers;
    };

export const getMerchantCascadeEndpointsGetMergedCascadeViewEnigmaV1MerchantCascadeMerchantMerchantIdMergedViewGetUrl =
    (
        merchantId: string,
        params: MerchantCascadeEndpointsGetMergedCascadeViewEnigmaV1MerchantCascadeMerchantMerchantIdMergedViewGetParams
    ) => {
        const normalizedParams = new URLSearchParams();

        Object.entries(params || {}).forEach(([key, value]) => {
            if (value !== undefined) {
                normalizedParams.append(key, value === null ? "null" : value.toString());
            }
        });

        const stringifiedParams = normalizedParams.toString();

        return stringifiedParams.length > 0
            ? `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/merchant_cascade/merchant/${merchantId}/merged-view?${stringifiedParams}`
            : `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/merchant_cascade/merchant/${merchantId}/merged-view`;
    };

export const merchantCascadeEndpointsGetMergedCascadeViewEnigmaV1MerchantCascadeMerchantMerchantIdMergedViewGet =
    async (
        merchantId: string,
        params: MerchantCascadeEndpointsGetMergedCascadeViewEnigmaV1MerchantCascadeMerchantMerchantIdMergedViewGetParams,
        options?: RequestInit
    ): Promise<merchantCascadeEndpointsGetMergedCascadeViewEnigmaV1MerchantCascadeMerchantMerchantIdMergedViewGetResponse> => {
        return authFetch<merchantCascadeEndpointsGetMergedCascadeViewEnigmaV1MerchantCascadeMerchantMerchantIdMergedViewGetResponse>(
            getMerchantCascadeEndpointsGetMergedCascadeViewEnigmaV1MerchantCascadeMerchantMerchantIdMergedViewGetUrl(
                merchantId,
                params
            ),
            {
                ...options,
                method: "GET"
            }
        );
    };
