/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * BlowFish - Enigma API Service
 * OpenAPI spec version: local
 */
import type {
    ApiResponseDictStrStr,
    ApiResponseMerchantCascadeSchema,
    ApiResponseMergedCascadeView,
    ApiResponseOffsetPaginationMerchantCascadeSchema,
    HTTPValidationError,
    MerchantCascadeCreate,
    MerchantCascadeEndpointsGetMergedCascadeViewEnigmaV1MerchantCascadeMerchantMerchantIdMergedViewGetParams,
    MerchantCascadeEndpointsListMerchantCascadesEnigmaV1MerchantCascadeGetParams,
    MerchantCascadeUpdate
} from "../blowFishEnigmaAPIService.schemas";

import { authFetch } from "../../../helpers/orvalAuthFetchMiddleware";

/**
 * Returns a merged view of all cascades for a merchant with terminal conflict resolution
 * @summary Get merged cascade view for merchant
 */
export type merchantCascadeEndpointsGetMergedCascadeViewEnigmaV1MerchantCascadeMerchantMerchantIdMergedViewGetResponse200 =
    {
        data: ApiResponseMergedCascadeView;
        status: 200;
    };

export type merchantCascadeEndpointsGetMergedCascadeViewEnigmaV1MerchantCascadeMerchantMerchantIdMergedViewGetResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type merchantCascadeEndpointsGetMergedCascadeViewEnigmaV1MerchantCascadeMerchantMerchantIdMergedViewGetResponseComposite =

        | merchantCascadeEndpointsGetMergedCascadeViewEnigmaV1MerchantCascadeMerchantMerchantIdMergedViewGetResponse200
        | merchantCascadeEndpointsGetMergedCascadeViewEnigmaV1MerchantCascadeMerchantMerchantIdMergedViewGetResponse422;

export type merchantCascadeEndpointsGetMergedCascadeViewEnigmaV1MerchantCascadeMerchantMerchantIdMergedViewGetResponse =
    merchantCascadeEndpointsGetMergedCascadeViewEnigmaV1MerchantCascadeMerchantMerchantIdMergedViewGetResponseComposite & {
        headers: Headers;
    };

export const getMerchantCascadeEndpointsGetMergedCascadeViewEnigmaV1MerchantCascadeMerchantMerchantIdMergedViewGetUrl =
    (
        merchantId: string,
        params: MerchantCascadeEndpointsGetMergedCascadeViewEnigmaV1MerchantCascadeMerchantMerchantIdMergedViewGetParams
    ) => {
        const normalizedParams = new URLSearchParams();

        Object.entries(params || {}).forEach(([key, value]) => {
            if (value !== undefined) {
                normalizedParams.append(key, value === null ? "null" : value.toString());
            }
        });

        const stringifiedParams = normalizedParams.toString();

        return stringifiedParams.length > 0
            ? `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/merchant_cascade/merchant/${merchantId}/merged-view?${stringifiedParams}`
            : `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/merchant_cascade/merchant/${merchantId}/merged-view`;
    };

export const merchantCascadeEndpointsGetMergedCascadeViewEnigmaV1MerchantCascadeMerchantMerchantIdMergedViewGet =
    async (
        merchantId: string,
        params: MerchantCascadeEndpointsGetMergedCascadeViewEnigmaV1MerchantCascadeMerchantMerchantIdMergedViewGetParams,
        options?: RequestInit
    ): Promise<merchantCascadeEndpointsGetMergedCascadeViewEnigmaV1MerchantCascadeMerchantMerchantIdMergedViewGetResponse> => {
        return authFetch<merchantCascadeEndpointsGetMergedCascadeViewEnigmaV1MerchantCascadeMerchantMerchantIdMergedViewGetResponse>(
            getMerchantCascadeEndpointsGetMergedCascadeViewEnigmaV1MerchantCascadeMerchantMerchantIdMergedViewGetUrl(
                merchantId,
                params
            ),
            {
                ...options,
                method: "GET"
            }
        );
    };

/**
 * Returns a paginated list of merchant cascade assignments with filtering
 * @summary Get merchant cascade assignments
 */
export type merchantCascadeEndpointsListMerchantCascadesEnigmaV1MerchantCascadeGetResponse200 = {
    data: ApiResponseOffsetPaginationMerchantCascadeSchema;
    status: 200;
};

export type merchantCascadeEndpointsListMerchantCascadesEnigmaV1MerchantCascadeGetResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type merchantCascadeEndpointsListMerchantCascadesEnigmaV1MerchantCascadeGetResponseComposite =
    | merchantCascadeEndpointsListMerchantCascadesEnigmaV1MerchantCascadeGetResponse200
    | merchantCascadeEndpointsListMerchantCascadesEnigmaV1MerchantCascadeGetResponse422;

export type merchantCascadeEndpointsListMerchantCascadesEnigmaV1MerchantCascadeGetResponse =
    merchantCascadeEndpointsListMerchantCascadesEnigmaV1MerchantCascadeGetResponseComposite & {
        headers: Headers;
    };

export const getMerchantCascadeEndpointsListMerchantCascadesEnigmaV1MerchantCascadeGetUrl = (
<<<<<<< HEAD
    params: MerchantCascadeEndpointsListMerchantCascadesEnigmaV1MerchantCascadeGetParams
=======
    params?: MerchantCascadeEndpointsListMerchantCascadesEnigmaV1MerchantCascadeGetParams
>>>>>>> INT-89
) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? "null" : value.toString());
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/merchant_cascade?${stringifiedParams}`
        : `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/merchant_cascade`;
};

export const merchantCascadeEndpointsListMerchantCascadesEnigmaV1MerchantCascadeGet = async (
<<<<<<< HEAD
    params: MerchantCascadeEndpointsListMerchantCascadesEnigmaV1MerchantCascadeGetParams,
=======
    params?: MerchantCascadeEndpointsListMerchantCascadesEnigmaV1MerchantCascadeGetParams,
>>>>>>> INT-89
    options?: RequestInit
): Promise<merchantCascadeEndpointsListMerchantCascadesEnigmaV1MerchantCascadeGetResponse> => {
    return authFetch<merchantCascadeEndpointsListMerchantCascadesEnigmaV1MerchantCascadeGetResponse>(
        getMerchantCascadeEndpointsListMerchantCascadesEnigmaV1MerchantCascadeGetUrl(params),
        {
            ...options,
            method: "GET"
        }
    );
};

/**
 * Assigns a cascade to a merchant with specified configuration
 * @summary Assign cascade to merchant
 */
export type merchantCascadeEndpointsAssignCascadeToMerchantEnigmaV1MerchantCascadePostResponse200 = {
    data: ApiResponseMerchantCascadeSchema;
    status: 200;
};

export type merchantCascadeEndpointsAssignCascadeToMerchantEnigmaV1MerchantCascadePostResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type merchantCascadeEndpointsAssignCascadeToMerchantEnigmaV1MerchantCascadePostResponseComposite =
    | merchantCascadeEndpointsAssignCascadeToMerchantEnigmaV1MerchantCascadePostResponse200
    | merchantCascadeEndpointsAssignCascadeToMerchantEnigmaV1MerchantCascadePostResponse422;

export type merchantCascadeEndpointsAssignCascadeToMerchantEnigmaV1MerchantCascadePostResponse =
    merchantCascadeEndpointsAssignCascadeToMerchantEnigmaV1MerchantCascadePostResponseComposite & {
        headers: Headers;
    };

export const getMerchantCascadeEndpointsAssignCascadeToMerchantEnigmaV1MerchantCascadePostUrl = () => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/merchant_cascade`;
};

export const merchantCascadeEndpointsAssignCascadeToMerchantEnigmaV1MerchantCascadePost = async (
    merchantCascadeCreate: MerchantCascadeCreate,
    options?: RequestInit
): Promise<merchantCascadeEndpointsAssignCascadeToMerchantEnigmaV1MerchantCascadePostResponse> => {
    return authFetch<merchantCascadeEndpointsAssignCascadeToMerchantEnigmaV1MerchantCascadePostResponse>(
        getMerchantCascadeEndpointsAssignCascadeToMerchantEnigmaV1MerchantCascadePostUrl(),
        {
            ...options,
            method: "POST",
            headers: { "Content-Type": "application/json", ...options?.headers },
            body: JSON.stringify(merchantCascadeCreate)
        }
    );
};

/**
 * Fetches details of a merchant cascade assignment by its ID
 * @summary Get merchant cascade assignment details
 */
export type merchantCascadeEndpointsGetMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdGetResponse200 = {
    data: ApiResponseMerchantCascadeSchema;
    status: 200;
};

export type merchantCascadeEndpointsGetMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdGetResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type merchantCascadeEndpointsGetMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdGetResponseComposite =
    | merchantCascadeEndpointsGetMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdGetResponse200
    | merchantCascadeEndpointsGetMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdGetResponse422;

export type merchantCascadeEndpointsGetMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdGetResponse =
    merchantCascadeEndpointsGetMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdGetResponseComposite & {
        headers: Headers;
    };

export const getMerchantCascadeEndpointsGetMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdGetUrl = (
    merchantCascadeId: string
) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/merchant_cascade/${merchantCascadeId}`;
};

export const merchantCascadeEndpointsGetMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdGet = async (
    merchantCascadeId: string,
    options?: RequestInit
): Promise<merchantCascadeEndpointsGetMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdGetResponse> => {
    return authFetch<merchantCascadeEndpointsGetMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdGetResponse>(
        getMerchantCascadeEndpointsGetMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdGetUrl(merchantCascadeId),
        {
            ...options,
            method: "GET"
        }
    );
};

/**
 * Updates merchant cascade assignment configuration
 * @summary Update merchant cascade assignment
 */
export type merchantCascadeEndpointsUpdateMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdPutResponse200 = {
    data: ApiResponseMerchantCascadeSchema;
    status: 200;
};

export type merchantCascadeEndpointsUpdateMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdPutResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type merchantCascadeEndpointsUpdateMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdPutResponseComposite =
    | merchantCascadeEndpointsUpdateMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdPutResponse200
    | merchantCascadeEndpointsUpdateMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdPutResponse422;

export type merchantCascadeEndpointsUpdateMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdPutResponse =
    merchantCascadeEndpointsUpdateMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdPutResponseComposite & {
        headers: Headers;
    };

export const getMerchantCascadeEndpointsUpdateMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdPutUrl = (
    merchantCascadeId: string
) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/merchant_cascade/${merchantCascadeId}`;
};

export const merchantCascadeEndpointsUpdateMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdPut = async (
    merchantCascadeId: string,
    merchantCascadeUpdate: MerchantCascadeUpdate,
    options?: RequestInit
): Promise<merchantCascadeEndpointsUpdateMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdPutResponse> => {
    return authFetch<merchantCascadeEndpointsUpdateMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdPutResponse>(
        getMerchantCascadeEndpointsUpdateMerchantCascadeEnigmaV1MerchantCascadeMerchantCascadeIdPutUrl(
            merchantCascadeId
        ),
        {
            ...options,
            method: "PUT",
            headers: { "Content-Type": "application/json", ...options?.headers },
            body: JSON.stringify(merchantCascadeUpdate)
        }
    );
};

/**
 * Removes a cascade assignment from a merchant
 * @summary Remove cascade from merchant
 */
export type merchantCascadeEndpointsRemoveCascadeFromMerchantEnigmaV1MerchantCascadeMerchantCascadeIdDeleteResponse200 =
    {
        data: ApiResponseDictStrStr;
        status: 200;
    };

export type merchantCascadeEndpointsRemoveCascadeFromMerchantEnigmaV1MerchantCascadeMerchantCascadeIdDeleteResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type merchantCascadeEndpointsRemoveCascadeFromMerchantEnigmaV1MerchantCascadeMerchantCascadeIdDeleteResponseComposite =

        | merchantCascadeEndpointsRemoveCascadeFromMerchantEnigmaV1MerchantCascadeMerchantCascadeIdDeleteResponse200
        | merchantCascadeEndpointsRemoveCascadeFromMerchantEnigmaV1MerchantCascadeMerchantCascadeIdDeleteResponse422;

export type merchantCascadeEndpointsRemoveCascadeFromMerchantEnigmaV1MerchantCascadeMerchantCascadeIdDeleteResponse =
    merchantCascadeEndpointsRemoveCascadeFromMerchantEnigmaV1MerchantCascadeMerchantCascadeIdDeleteResponseComposite & {
        headers: Headers;
    };

export const getMerchantCascadeEndpointsRemoveCascadeFromMerchantEnigmaV1MerchantCascadeMerchantCascadeIdDeleteUrl = (
    merchantCascadeId: string
) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/merchant_cascade/${merchantCascadeId}`;
};

export const merchantCascadeEndpointsRemoveCascadeFromMerchantEnigmaV1MerchantCascadeMerchantCascadeIdDelete = async (
    merchantCascadeId: string,
    options?: RequestInit
): Promise<merchantCascadeEndpointsRemoveCascadeFromMerchantEnigmaV1MerchantCascadeMerchantCascadeIdDeleteResponse> => {
    return authFetch<merchantCascadeEndpointsRemoveCascadeFromMerchantEnigmaV1MerchantCascadeMerchantCascadeIdDeleteResponse>(
        getMerchantCascadeEndpointsRemoveCascadeFromMerchantEnigmaV1MerchantCascadeMerchantCascadeIdDeleteUrl(
            merchantCascadeId
        ),
        {
            ...options,
            method: "DELETE"
        }
    );
};
