/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * BlowFish - Enigma API Service
 * OpenAPI spec version: develop
 */
import type {
    ApiResponseImportResponse,
    ApiResponseNoneType,
    ApiResponseOffsetPaginationSystemPaymentInstrument,
    ApiResponseSystemPaymentInstrument,
    BodySystemPaymentInstrumentEndpointsImportSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsImportPost,
    HTTPValidationError,
    SystemPaymentInstrumentCreate,
    SystemPaymentInstrumentEndpointsExportSystemPaymentInstrumentsEnigmaV1SystemPaymentInstrumentsExportGetParams,
    SystemPaymentInstrumentEndpointsImportSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsImportPostParams,
    SystemPaymentInstrumentEndpointsListSystemPaymentInstrumentsEnigmaV1SystemPaymentInstrumentsGetParams,
    SystemPaymentInstrumentUpdate
} from "../blowFishEnigmaAPIService.schemas";

import { authFetch } from "../../../helpers/orvalAuthFetchMiddleware";

/**
 * Retrieves a list of system payment instruments with pagination, filtering, and sorting capabilities.
 * @summary Retrieve a list of System Payment Instruments
 */
export type systemPaymentInstrumentEndpointsListSystemPaymentInstrumentsEnigmaV1SystemPaymentInstrumentsGetResponse200 =
    {
        data: ApiResponseOffsetPaginationSystemPaymentInstrument;
        status: 200;
    };

export type systemPaymentInstrumentEndpointsListSystemPaymentInstrumentsEnigmaV1SystemPaymentInstrumentsGetResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type systemPaymentInstrumentEndpointsListSystemPaymentInstrumentsEnigmaV1SystemPaymentInstrumentsGetResponseComposite =

        | systemPaymentInstrumentEndpointsListSystemPaymentInstrumentsEnigmaV1SystemPaymentInstrumentsGetResponse200
        | systemPaymentInstrumentEndpointsListSystemPaymentInstrumentsEnigmaV1SystemPaymentInstrumentsGetResponse422;

export type systemPaymentInstrumentEndpointsListSystemPaymentInstrumentsEnigmaV1SystemPaymentInstrumentsGetResponse =
    systemPaymentInstrumentEndpointsListSystemPaymentInstrumentsEnigmaV1SystemPaymentInstrumentsGetResponseComposite & {
        headers: Headers;
    };

export const getSystemPaymentInstrumentEndpointsListSystemPaymentInstrumentsEnigmaV1SystemPaymentInstrumentsGetUrl = (
    params?: SystemPaymentInstrumentEndpointsListSystemPaymentInstrumentsEnigmaV1SystemPaymentInstrumentsGetParams
) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? "null" : value.toString());
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/system_payment_instruments?${stringifiedParams}`
        : `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/system_payment_instruments`;
};

export const systemPaymentInstrumentEndpointsListSystemPaymentInstrumentsEnigmaV1SystemPaymentInstrumentsGet = async (
    params?: SystemPaymentInstrumentEndpointsListSystemPaymentInstrumentsEnigmaV1SystemPaymentInstrumentsGetParams,
    options?: RequestInit
): Promise<systemPaymentInstrumentEndpointsListSystemPaymentInstrumentsEnigmaV1SystemPaymentInstrumentsGetResponse> => {
    return authFetch<systemPaymentInstrumentEndpointsListSystemPaymentInstrumentsEnigmaV1SystemPaymentInstrumentsGetResponse>(
        getSystemPaymentInstrumentEndpointsListSystemPaymentInstrumentsEnigmaV1SystemPaymentInstrumentsGetUrl(params),
        {
            ...options,
            method: "GET"
        }
    );
};

/**
 * Creates a new system payment instrument with the provided details.
 * @summary Create a new System Payment Instrument
 */
export type systemPaymentInstrumentEndpointsCreateSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsPostResponse200 =
    {
        data: ApiResponseSystemPaymentInstrument;
        status: 200;
    };

export type systemPaymentInstrumentEndpointsCreateSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsPostResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type systemPaymentInstrumentEndpointsCreateSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsPostResponseComposite =

        | systemPaymentInstrumentEndpointsCreateSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsPostResponse200
        | systemPaymentInstrumentEndpointsCreateSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsPostResponse422;

export type systemPaymentInstrumentEndpointsCreateSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsPostResponse =
    systemPaymentInstrumentEndpointsCreateSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsPostResponseComposite & {
        headers: Headers;
    };

export const getSystemPaymentInstrumentEndpointsCreateSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsPostUrl =
    () => {
        return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/system_payment_instruments`;
    };

export const systemPaymentInstrumentEndpointsCreateSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsPost = async (
    systemPaymentInstrumentCreate: SystemPaymentInstrumentCreate,
    options?: RequestInit
): Promise<systemPaymentInstrumentEndpointsCreateSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsPostResponse> => {
    return authFetch<systemPaymentInstrumentEndpointsCreateSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsPostResponse>(
        getSystemPaymentInstrumentEndpointsCreateSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsPostUrl(),
        {
            ...options,
            method: "POST",
            headers: { "Content-Type": "application/json", ...options?.headers },
            body: JSON.stringify(systemPaymentInstrumentCreate)
        }
    );
};

/**
 * Exports System Payment Instruments to a CSV file and download it
 * @summary Export System Payment Instruments to CSV
 */
export type systemPaymentInstrumentEndpointsExportSystemPaymentInstrumentsEnigmaV1SystemPaymentInstrumentsExportGetResponse200 =
    {
        data: unknown;
        status: 200;
    };

export type systemPaymentInstrumentEndpointsExportSystemPaymentInstrumentsEnigmaV1SystemPaymentInstrumentsExportGetResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type systemPaymentInstrumentEndpointsExportSystemPaymentInstrumentsEnigmaV1SystemPaymentInstrumentsExportGetResponseComposite =

        | systemPaymentInstrumentEndpointsExportSystemPaymentInstrumentsEnigmaV1SystemPaymentInstrumentsExportGetResponse200
        | systemPaymentInstrumentEndpointsExportSystemPaymentInstrumentsEnigmaV1SystemPaymentInstrumentsExportGetResponse422;

export type systemPaymentInstrumentEndpointsExportSystemPaymentInstrumentsEnigmaV1SystemPaymentInstrumentsExportGetResponse =
    systemPaymentInstrumentEndpointsExportSystemPaymentInstrumentsEnigmaV1SystemPaymentInstrumentsExportGetResponseComposite & {
        headers: Headers;
    };

export const getSystemPaymentInstrumentEndpointsExportSystemPaymentInstrumentsEnigmaV1SystemPaymentInstrumentsExportGetUrl =
    (
        params?: SystemPaymentInstrumentEndpointsExportSystemPaymentInstrumentsEnigmaV1SystemPaymentInstrumentsExportGetParams
    ) => {
        const normalizedParams = new URLSearchParams();

        Object.entries(params || {}).forEach(([key, value]) => {
            if (value !== undefined) {
                normalizedParams.append(key, value === null ? "null" : value.toString());
            }
        });

        const stringifiedParams = normalizedParams.toString();

        return stringifiedParams.length > 0
            ? `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/system_payment_instruments/export?${stringifiedParams}`
            : `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/system_payment_instruments/export`;
    };

export const systemPaymentInstrumentEndpointsExportSystemPaymentInstrumentsEnigmaV1SystemPaymentInstrumentsExportGet =
    async (
        params?: SystemPaymentInstrumentEndpointsExportSystemPaymentInstrumentsEnigmaV1SystemPaymentInstrumentsExportGetParams,
        options?: RequestInit
    ): Promise<systemPaymentInstrumentEndpointsExportSystemPaymentInstrumentsEnigmaV1SystemPaymentInstrumentsExportGetResponse> => {
        return authFetch<systemPaymentInstrumentEndpointsExportSystemPaymentInstrumentsEnigmaV1SystemPaymentInstrumentsExportGetResponse>(
            getSystemPaymentInstrumentEndpointsExportSystemPaymentInstrumentsEnigmaV1SystemPaymentInstrumentsExportGetUrl(
                params
            ),
            {
                ...options,
                method: "GET"
            }
        );
    };

/**
 * Upload CSV file and import System Payment Instruments from it to system.
 * @summary Systempaymentinstrumentendpoints.Import System Payment Instrument
 */
export type systemPaymentInstrumentEndpointsImportSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsImportPostResponse200 =
    {
        data: ApiResponseImportResponse;
        status: 200;
    };

export type systemPaymentInstrumentEndpointsImportSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsImportPostResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type systemPaymentInstrumentEndpointsImportSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsImportPostResponseComposite =

        | systemPaymentInstrumentEndpointsImportSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsImportPostResponse200
        | systemPaymentInstrumentEndpointsImportSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsImportPostResponse422;

export type systemPaymentInstrumentEndpointsImportSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsImportPostResponse =
    systemPaymentInstrumentEndpointsImportSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsImportPostResponseComposite & {
        headers: Headers;
    };

export const getSystemPaymentInstrumentEndpointsImportSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsImportPostUrl =
    (
        params?: SystemPaymentInstrumentEndpointsImportSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsImportPostParams
    ) => {
        const normalizedParams = new URLSearchParams();

        Object.entries(params || {}).forEach(([key, value]) => {
            if (value !== undefined) {
                normalizedParams.append(key, value === null ? "null" : value.toString());
            }
        });

        const stringifiedParams = normalizedParams.toString();

        return stringifiedParams.length > 0
            ? `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/system_payment_instruments/import?${stringifiedParams}`
            : `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/system_payment_instruments/import`;
    };

export const systemPaymentInstrumentEndpointsImportSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsImportPost =
    async (
        bodySystemPaymentInstrumentEndpointsImportSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsImportPost: BodySystemPaymentInstrumentEndpointsImportSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsImportPost,
        params?: SystemPaymentInstrumentEndpointsImportSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsImportPostParams,
        options?: RequestInit
    ): Promise<systemPaymentInstrumentEndpointsImportSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsImportPostResponse> => {
        const formData = new FormData();
        formData.append(
            "csv_file",
            bodySystemPaymentInstrumentEndpointsImportSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsImportPost.csv_file
        );

        return authFetch<systemPaymentInstrumentEndpointsImportSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsImportPostResponse>(
            getSystemPaymentInstrumentEndpointsImportSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsImportPostUrl(
                params
            ),
            {
                ...options,
                method: "POST",
                body: formData
            }
        );
    };

/**
 * Retrieves detailed information about a specific system payment instrument by its unique ID.
 * @summary Retrieve a single System Payment Instrument by ID
 */
export type systemPaymentInstrumentEndpointsGetSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsSystemPaymentInstrumentIdGetResponse200 =
    {
        data: ApiResponseSystemPaymentInstrument;
        status: 200;
    };

export type systemPaymentInstrumentEndpointsGetSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsSystemPaymentInstrumentIdGetResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type systemPaymentInstrumentEndpointsGetSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsSystemPaymentInstrumentIdGetResponseComposite =

        | systemPaymentInstrumentEndpointsGetSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsSystemPaymentInstrumentIdGetResponse200
        | systemPaymentInstrumentEndpointsGetSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsSystemPaymentInstrumentIdGetResponse422;

export type systemPaymentInstrumentEndpointsGetSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsSystemPaymentInstrumentIdGetResponse =
    systemPaymentInstrumentEndpointsGetSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsSystemPaymentInstrumentIdGetResponseComposite & {
        headers: Headers;
    };

export const getSystemPaymentInstrumentEndpointsGetSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsSystemPaymentInstrumentIdGetUrl =
    (systemPaymentInstrumentId: string) => {
        return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/system_payment_instruments/${systemPaymentInstrumentId}`;
    };

export const systemPaymentInstrumentEndpointsGetSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsSystemPaymentInstrumentIdGet =
    async (
        systemPaymentInstrumentId: string,
        options?: RequestInit
    ): Promise<systemPaymentInstrumentEndpointsGetSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsSystemPaymentInstrumentIdGetResponse> => {
        return authFetch<systemPaymentInstrumentEndpointsGetSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsSystemPaymentInstrumentIdGetResponse>(
            getSystemPaymentInstrumentEndpointsGetSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsSystemPaymentInstrumentIdGetUrl(
                systemPaymentInstrumentId
            ),
            {
                ...options,
                method: "GET"
            }
        );
    };

/**
 * Partially updates an existing system payment instrument identified by its ID with the provided data. Only the fields present in the request body will be updated.
 * @summary Partially update a System Payment Instrument by ID
 */
export type systemPaymentInstrumentEndpointsPatchSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsSystemPaymentInstrumentIdPatchResponse200 =
    {
        data: ApiResponseSystemPaymentInstrument;
        status: 200;
    };

export type systemPaymentInstrumentEndpointsPatchSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsSystemPaymentInstrumentIdPatchResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type systemPaymentInstrumentEndpointsPatchSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsSystemPaymentInstrumentIdPatchResponseComposite =

        | systemPaymentInstrumentEndpointsPatchSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsSystemPaymentInstrumentIdPatchResponse200
        | systemPaymentInstrumentEndpointsPatchSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsSystemPaymentInstrumentIdPatchResponse422;

export type systemPaymentInstrumentEndpointsPatchSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsSystemPaymentInstrumentIdPatchResponse =
    systemPaymentInstrumentEndpointsPatchSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsSystemPaymentInstrumentIdPatchResponseComposite & {
        headers: Headers;
    };

export const getSystemPaymentInstrumentEndpointsPatchSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsSystemPaymentInstrumentIdPatchUrl =
    (systemPaymentInstrumentId: string) => {
        return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/system_payment_instruments/${systemPaymentInstrumentId}`;
    };

export const systemPaymentInstrumentEndpointsPatchSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsSystemPaymentInstrumentIdPatch =
    async (
        systemPaymentInstrumentId: string,
        systemPaymentInstrumentUpdate: SystemPaymentInstrumentUpdate,
        options?: RequestInit
    ): Promise<systemPaymentInstrumentEndpointsPatchSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsSystemPaymentInstrumentIdPatchResponse> => {
        return authFetch<systemPaymentInstrumentEndpointsPatchSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsSystemPaymentInstrumentIdPatchResponse>(
            getSystemPaymentInstrumentEndpointsPatchSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsSystemPaymentInstrumentIdPatchUrl(
                systemPaymentInstrumentId
            ),
            {
                ...options,
                method: "PATCH",
                headers: { "Content-Type": "application/json", ...options?.headers },
                body: JSON.stringify(systemPaymentInstrumentUpdate)
            }
        );
    };

/**
 * Deletes a system payment instrument by its unique ID.
 * @summary Delete a System Payment Instrument by ID
 */
export type systemPaymentInstrumentEndpointsDeleteSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsSystemPaymentInstrumentIdDeleteResponse200 =
    {
        data: ApiResponseNoneType;
        status: 200;
    };

export type systemPaymentInstrumentEndpointsDeleteSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsSystemPaymentInstrumentIdDeleteResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type systemPaymentInstrumentEndpointsDeleteSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsSystemPaymentInstrumentIdDeleteResponseComposite =

        | systemPaymentInstrumentEndpointsDeleteSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsSystemPaymentInstrumentIdDeleteResponse200
        | systemPaymentInstrumentEndpointsDeleteSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsSystemPaymentInstrumentIdDeleteResponse422;

export type systemPaymentInstrumentEndpointsDeleteSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsSystemPaymentInstrumentIdDeleteResponse =
    systemPaymentInstrumentEndpointsDeleteSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsSystemPaymentInstrumentIdDeleteResponseComposite & {
        headers: Headers;
    };

export const getSystemPaymentInstrumentEndpointsDeleteSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsSystemPaymentInstrumentIdDeleteUrl =
    (systemPaymentInstrumentId: string) => {
        return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/system_payment_instruments/${systemPaymentInstrumentId}`;
    };

export const systemPaymentInstrumentEndpointsDeleteSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsSystemPaymentInstrumentIdDelete =
    async (
        systemPaymentInstrumentId: string,
        options?: RequestInit
    ): Promise<systemPaymentInstrumentEndpointsDeleteSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsSystemPaymentInstrumentIdDeleteResponse> => {
        return authFetch<systemPaymentInstrumentEndpointsDeleteSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsSystemPaymentInstrumentIdDeleteResponse>(
            getSystemPaymentInstrumentEndpointsDeleteSystemPaymentInstrumentEnigmaV1SystemPaymentInstrumentsSystemPaymentInstrumentIdDeleteUrl(
                systemPaymentInstrumentId
            ),
            {
                ...options,
                method: "DELETE"
            }
        );
    };
