/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * BlowFish - Enigma API Service
 * OpenAPI spec version: develop
 */
import type {
    ApiResponseKeyPair,
    HTTPValidationError,
    KeyGenEndpointsGenerateRsaKeypairEnigmaV1PkiKeygenGetParams
} from "../blowFishEnigmaAPIService.schemas";

/**
 * Generates a new RSA key pair and returns keys in base58 encoded format.
 * @summary Generate RSA key pair
 */
export type keyGenEndpointsGenerateRsaKeypairEnigmaV1PkiKeygenGetResponse200 = {
    data: ApiResponseKeyPair;
    status: 200;
};

export type keyGenEndpointsGenerateRsaKeypairEnigmaV1PkiKeygenGetResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type keyGenEndpointsGenerateRsaKeypairEnigmaV1PkiKeygenGetResponseComposite =
    | keyGenEndpointsGenerateRsaKeypairEnigmaV1PkiKeygenGetResponse200
    | keyGenEndpointsGenerateRsaKeypairEnigmaV1PkiKeygenGetResponse422;

export type keyGenEndpointsGenerateRsaKeypairEnigmaV1PkiKeygenGetResponse =
    keyGenEndpointsGenerateRsaKeypairEnigmaV1PkiKeygenGetResponseComposite & {
        headers: Headers;
    };

export const getKeyGenEndpointsGenerateRsaKeypairEnigmaV1PkiKeygenGetUrl = (
    params?: KeyGenEndpointsGenerateRsaKeypairEnigmaV1PkiKeygenGetParams
) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? "null" : value.toString());
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/pki/keygen?${stringifiedParams}`
        : `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/pki/keygen`;
};

export const keyGenEndpointsGenerateRsaKeypairEnigmaV1PkiKeygenGet = async (
    params?: KeyGenEndpointsGenerateRsaKeypairEnigmaV1PkiKeygenGetParams,
    options?: RequestInit
): Promise<keyGenEndpointsGenerateRsaKeypairEnigmaV1PkiKeygenGetResponse> => {
    const res = await fetch(getKeyGenEndpointsGenerateRsaKeypairEnigmaV1PkiKeygenGetUrl(params), {
        ...options,
        method: "GET"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();
    const data: keyGenEndpointsGenerateRsaKeypairEnigmaV1PkiKeygenGetResponse["data"] = body ? JSON.parse(body) : {};

    return {
        data,
        status: res.status,
        headers: res.headers
    } as keyGenEndpointsGenerateRsaKeypairEnigmaV1PkiKeygenGetResponse;
};
