/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * BlowFish - CallBridge API Service
 * OpenAPI spec version: develop
 */
import type {
    ApiResponseCallbackMappingBulkResponse,
    ApiResponseCallbackMappingRead,
    ApiResponseNoneType,
    ApiResponseOffsetPaginationCallbackMappingRead,
    CallbackMappingBulkCreate,
    CallbackMappingCreate,
    CallbackMappingEndpointsListMappingsCallbridgeV1MappingGetParams,
    CallbackMappingUpdate,
    HTTPValidationError
} from "../blowFishCallBridgeAPIService.schemas";

import { authFetch } from "../../../helpers/orvalAuthFetchMiddleware";

/**
 * @summary List callback mappings
 */
export type callbackMappingEndpointsListMappingsCallbridgeV1MappingGetResponse200 = {
    data: ApiResponseOffsetPaginationCallbackMappingRead;
    status: 200;
};

export type callbackMappingEndpointsListMappingsCallbridgeV1MappingGetResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type callbackMappingEndpointsListMappingsCallbridgeV1MappingGetResponseComposite =
    | callbackMappingEndpointsListMappingsCallbridgeV1MappingGetResponse200
    | callbackMappingEndpointsListMappingsCallbridgeV1MappingGetResponse422;

export type callbackMappingEndpointsListMappingsCallbridgeV1MappingGetResponse =
    callbackMappingEndpointsListMappingsCallbridgeV1MappingGetResponseComposite & {
        headers: Headers;
    };

export const getCallbackMappingEndpointsListMappingsCallbridgeV1MappingGetUrl = (
    params?: CallbackMappingEndpointsListMappingsCallbridgeV1MappingGetParams
) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? "null" : value.toString());
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `https://apigate.develop.blowfish.api4ftx.cloud/callbridge/v1/mapping?${stringifiedParams}`
        : `https://apigate.develop.blowfish.api4ftx.cloud/callbridge/v1/mapping`;
};

export const callbackMappingEndpointsListMappingsCallbridgeV1MappingGet = async (
    params?: CallbackMappingEndpointsListMappingsCallbridgeV1MappingGetParams,
    options?: RequestInit
): Promise<callbackMappingEndpointsListMappingsCallbridgeV1MappingGetResponse> => {
    return authFetch<callbackMappingEndpointsListMappingsCallbridgeV1MappingGetResponse>(
        getCallbackMappingEndpointsListMappingsCallbridgeV1MappingGetUrl(params),
        {
            ...options,
            method: "GET"
        }
    );
};

/**
 * @deprecated
 * @summary Create callback mapping
 */
export type callbackMappingEndpointsCreateMappingCallbridgeV1MappingPostResponse200 = {
    data: ApiResponseCallbackMappingRead;
    status: 200;
};

export type callbackMappingEndpointsCreateMappingCallbridgeV1MappingPostResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type callbackMappingEndpointsCreateMappingCallbridgeV1MappingPostResponseComposite =
    | callbackMappingEndpointsCreateMappingCallbridgeV1MappingPostResponse200
    | callbackMappingEndpointsCreateMappingCallbridgeV1MappingPostResponse422;

export type callbackMappingEndpointsCreateMappingCallbridgeV1MappingPostResponse =
    callbackMappingEndpointsCreateMappingCallbridgeV1MappingPostResponseComposite & {
        headers: Headers;
    };

export const getCallbackMappingEndpointsCreateMappingCallbridgeV1MappingPostUrl = () => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/callbridge/v1/mapping`;
};

export const callbackMappingEndpointsCreateMappingCallbridgeV1MappingPost = async (
    callbackMappingCreate: CallbackMappingCreate,
    options?: RequestInit
): Promise<callbackMappingEndpointsCreateMappingCallbridgeV1MappingPostResponse> => {
    return authFetch<callbackMappingEndpointsCreateMappingCallbridgeV1MappingPostResponse>(
        getCallbackMappingEndpointsCreateMappingCallbridgeV1MappingPostUrl(),
        {
            ...options,
            method: "POST",
            headers: { "Content-Type": "application/json", ...options?.headers },
            body: JSON.stringify(callbackMappingCreate)
        }
    );
};

/**
 * @summary Create or update callback mapping by internal path
 */
export type callbackMappingEndpointsCreateOrUpdateMappingViaInternalPathCallbridgeV1MappingByExternalPathPostResponse200 =
    {
        data: ApiResponseCallbackMappingRead;
        status: 200;
    };

export type callbackMappingEndpointsCreateOrUpdateMappingViaInternalPathCallbridgeV1MappingByExternalPathPostResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type callbackMappingEndpointsCreateOrUpdateMappingViaInternalPathCallbridgeV1MappingByExternalPathPostResponseComposite =

        | callbackMappingEndpointsCreateOrUpdateMappingViaInternalPathCallbridgeV1MappingByExternalPathPostResponse200
        | callbackMappingEndpointsCreateOrUpdateMappingViaInternalPathCallbridgeV1MappingByExternalPathPostResponse422;

export type callbackMappingEndpointsCreateOrUpdateMappingViaInternalPathCallbridgeV1MappingByExternalPathPostResponse =
    callbackMappingEndpointsCreateOrUpdateMappingViaInternalPathCallbridgeV1MappingByExternalPathPostResponseComposite & {
        headers: Headers;
    };

export const getCallbackMappingEndpointsCreateOrUpdateMappingViaInternalPathCallbridgeV1MappingByExternalPathPostUrl =
    () => {
        return `https://apigate.develop.blowfish.api4ftx.cloud/callbridge/v1/mapping/by-external-path`;
    };

export const callbackMappingEndpointsCreateOrUpdateMappingViaInternalPathCallbridgeV1MappingByExternalPathPost = async (
    callbackMappingCreate: CallbackMappingCreate,
    options?: RequestInit
): Promise<callbackMappingEndpointsCreateOrUpdateMappingViaInternalPathCallbridgeV1MappingByExternalPathPostResponse> => {
    return authFetch<callbackMappingEndpointsCreateOrUpdateMappingViaInternalPathCallbridgeV1MappingByExternalPathPostResponse>(
        getCallbackMappingEndpointsCreateOrUpdateMappingViaInternalPathCallbridgeV1MappingByExternalPathPostUrl(),
        {
            ...options,
            method: "POST",
            headers: { "Content-Type": "application/json", ...options?.headers },
            body: JSON.stringify(callbackMappingCreate)
        }
    );
};

/**
 * @summary Get callback mapping by ID
 */
export type callbackMappingEndpointsGetMappingCallbridgeV1MappingMappingIdGetResponse200 = {
    data: ApiResponseCallbackMappingRead;
    status: 200;
};

export type callbackMappingEndpointsGetMappingCallbridgeV1MappingMappingIdGetResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type callbackMappingEndpointsGetMappingCallbridgeV1MappingMappingIdGetResponseComposite =
    | callbackMappingEndpointsGetMappingCallbridgeV1MappingMappingIdGetResponse200
    | callbackMappingEndpointsGetMappingCallbridgeV1MappingMappingIdGetResponse422;

export type callbackMappingEndpointsGetMappingCallbridgeV1MappingMappingIdGetResponse =
    callbackMappingEndpointsGetMappingCallbridgeV1MappingMappingIdGetResponseComposite & {
        headers: Headers;
    };

export const getCallbackMappingEndpointsGetMappingCallbridgeV1MappingMappingIdGetUrl = (mappingId: string) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/callbridge/v1/mapping/${mappingId}`;
};

export const callbackMappingEndpointsGetMappingCallbridgeV1MappingMappingIdGet = async (
    mappingId: string,
    options?: RequestInit
): Promise<callbackMappingEndpointsGetMappingCallbridgeV1MappingMappingIdGetResponse> => {
    return authFetch<callbackMappingEndpointsGetMappingCallbridgeV1MappingMappingIdGetResponse>(
        getCallbackMappingEndpointsGetMappingCallbridgeV1MappingMappingIdGetUrl(mappingId),
        {
            ...options,
            method: "GET"
        }
    );
};

/**
 * @deprecated
 * @summary Update callback mapping
 */
export type callbackMappingEndpointsUpdateMappingCallbridgeV1MappingMappingIdPutResponse200 = {
    data: ApiResponseCallbackMappingRead;
    status: 200;
};

export type callbackMappingEndpointsUpdateMappingCallbridgeV1MappingMappingIdPutResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type callbackMappingEndpointsUpdateMappingCallbridgeV1MappingMappingIdPutResponseComposite =
    | callbackMappingEndpointsUpdateMappingCallbridgeV1MappingMappingIdPutResponse200
    | callbackMappingEndpointsUpdateMappingCallbridgeV1MappingMappingIdPutResponse422;

export type callbackMappingEndpointsUpdateMappingCallbridgeV1MappingMappingIdPutResponse =
    callbackMappingEndpointsUpdateMappingCallbridgeV1MappingMappingIdPutResponseComposite & {
        headers: Headers;
    };

export const getCallbackMappingEndpointsUpdateMappingCallbridgeV1MappingMappingIdPutUrl = (mappingId: string) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/callbridge/v1/mapping/${mappingId}`;
};

export const callbackMappingEndpointsUpdateMappingCallbridgeV1MappingMappingIdPut = async (
    mappingId: string,
    callbackMappingUpdate: CallbackMappingUpdate,
    options?: RequestInit
): Promise<callbackMappingEndpointsUpdateMappingCallbridgeV1MappingMappingIdPutResponse> => {
    return authFetch<callbackMappingEndpointsUpdateMappingCallbridgeV1MappingMappingIdPutResponse>(
        getCallbackMappingEndpointsUpdateMappingCallbridgeV1MappingMappingIdPutUrl(mappingId),
        {
            ...options,
            method: "PUT",
            headers: { "Content-Type": "application/json", ...options?.headers },
            body: JSON.stringify(callbackMappingUpdate)
        }
    );
};

/**
 * @summary Delete callback mapping
 */
export type callbackMappingEndpointsDeleteMappingCallbridgeV1MappingMappingIdDeleteResponse200 = {
    data: ApiResponseNoneType;
    status: 200;
};

export type callbackMappingEndpointsDeleteMappingCallbridgeV1MappingMappingIdDeleteResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type callbackMappingEndpointsDeleteMappingCallbridgeV1MappingMappingIdDeleteResponseComposite =
    | callbackMappingEndpointsDeleteMappingCallbridgeV1MappingMappingIdDeleteResponse200
    | callbackMappingEndpointsDeleteMappingCallbridgeV1MappingMappingIdDeleteResponse422;

export type callbackMappingEndpointsDeleteMappingCallbridgeV1MappingMappingIdDeleteResponse =
    callbackMappingEndpointsDeleteMappingCallbridgeV1MappingMappingIdDeleteResponseComposite & {
        headers: Headers;
    };

export const getCallbackMappingEndpointsDeleteMappingCallbridgeV1MappingMappingIdDeleteUrl = (mappingId: string) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/callbridge/v1/mapping/${mappingId}`;
};

export const callbackMappingEndpointsDeleteMappingCallbridgeV1MappingMappingIdDelete = async (
    mappingId: string,
    options?: RequestInit
): Promise<callbackMappingEndpointsDeleteMappingCallbridgeV1MappingMappingIdDeleteResponse> => {
    return authFetch<callbackMappingEndpointsDeleteMappingCallbridgeV1MappingMappingIdDeleteResponse>(
        getCallbackMappingEndpointsDeleteMappingCallbridgeV1MappingMappingIdDeleteUrl(mappingId),
        {
            ...options,
            method: "DELETE"
        }
    );
};

/**
 * @summary Create or update multiple callback mappings
 */
export type callbackMappingEndpointsBulkCreateOrUpdateMappingViaInternalPathCallbridgeV1MappingBulkCreateOrUpdatePostResponse200 =
    {
        data: ApiResponseCallbackMappingBulkResponse;
        status: 200;
    };

export type callbackMappingEndpointsBulkCreateOrUpdateMappingViaInternalPathCallbridgeV1MappingBulkCreateOrUpdatePostResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type callbackMappingEndpointsBulkCreateOrUpdateMappingViaInternalPathCallbridgeV1MappingBulkCreateOrUpdatePostResponseComposite =

        | callbackMappingEndpointsBulkCreateOrUpdateMappingViaInternalPathCallbridgeV1MappingBulkCreateOrUpdatePostResponse200
        | callbackMappingEndpointsBulkCreateOrUpdateMappingViaInternalPathCallbridgeV1MappingBulkCreateOrUpdatePostResponse422;

export type callbackMappingEndpointsBulkCreateOrUpdateMappingViaInternalPathCallbridgeV1MappingBulkCreateOrUpdatePostResponse =
    callbackMappingEndpointsBulkCreateOrUpdateMappingViaInternalPathCallbridgeV1MappingBulkCreateOrUpdatePostResponseComposite & {
        headers: Headers;
    };

export const getCallbackMappingEndpointsBulkCreateOrUpdateMappingViaInternalPathCallbridgeV1MappingBulkCreateOrUpdatePostUrl =
    () => {
        return `https://apigate.develop.blowfish.api4ftx.cloud/callbridge/v1/mapping/bulk/create-or-update`;
    };

export const callbackMappingEndpointsBulkCreateOrUpdateMappingViaInternalPathCallbridgeV1MappingBulkCreateOrUpdatePost =
    async (
        callbackMappingBulkCreate: CallbackMappingBulkCreate,
        options?: RequestInit
    ): Promise<callbackMappingEndpointsBulkCreateOrUpdateMappingViaInternalPathCallbridgeV1MappingBulkCreateOrUpdatePostResponse> => {
        return authFetch<callbackMappingEndpointsBulkCreateOrUpdateMappingViaInternalPathCallbridgeV1MappingBulkCreateOrUpdatePostResponse>(
            getCallbackMappingEndpointsBulkCreateOrUpdateMappingViaInternalPathCallbridgeV1MappingBulkCreateOrUpdatePostUrl(),
            {
                ...options,
                method: "POST",
                headers: { "Content-Type": "application/json", ...options?.headers },
                body: JSON.stringify(callbackMappingBulkCreate)
            }
        );
    };
