/**
 * Generated by orval v7.6.0 🍺
 * Do not edit manually.
 * BlowFish - Enigma API Service
 * OpenAPI spec version: develop
 */
import type {
    ApiResponseCurrency,
    ApiResponseNoneType,
    ApiResponseOffsetPaginationCurrency,
    CurrencyCreate,
    CurrencyEndpointsListCurrenciesEnigmaV1CurrencyGetParams,
    CurrencyUpdate,
    HTTPValidationError
} from "../blowFishEnigmaAPIService.schemas";

/**
 * Returns a paginated list of available currencies. Supports filtering based on query parameters.
 * @summary Get a list of currencies with filtering and pagination
 */
export type currencyEndpointsListCurrenciesEnigmaV1CurrencyGetResponse200 = {
    data: ApiResponseOffsetPaginationCurrency;
    status: 200;
};

export type currencyEndpointsListCurrenciesEnigmaV1CurrencyGetResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type currencyEndpointsListCurrenciesEnigmaV1CurrencyGetResponseComposite =
    | currencyEndpointsListCurrenciesEnigmaV1CurrencyGetResponse200
    | currencyEndpointsListCurrenciesEnigmaV1CurrencyGetResponse422;

export type currencyEndpointsListCurrenciesEnigmaV1CurrencyGetResponse =
    currencyEndpointsListCurrenciesEnigmaV1CurrencyGetResponseComposite & {
        headers: Headers;
    };

export const getCurrencyEndpointsListCurrenciesEnigmaV1CurrencyGetUrl = (
    params?: CurrencyEndpointsListCurrenciesEnigmaV1CurrencyGetParams
) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? "null" : value.toString());
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/currency?${stringifiedParams}`
        : `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/currency`;
};

export const currencyEndpointsListCurrenciesEnigmaV1CurrencyGet = async (
    params?: CurrencyEndpointsListCurrenciesEnigmaV1CurrencyGetParams,
    options?: RequestInit
): Promise<currencyEndpointsListCurrenciesEnigmaV1CurrencyGetResponse> => {
    const res = await fetch(getCurrencyEndpointsListCurrenciesEnigmaV1CurrencyGetUrl(params), {
        ...options,
        method: "GET"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();
    const data: currencyEndpointsListCurrenciesEnigmaV1CurrencyGetResponse["data"] = body ? JSON.parse(body) : {};

    return {
        data,
        status: res.status,
        headers: res.headers
    } as currencyEndpointsListCurrenciesEnigmaV1CurrencyGetResponse;
};

/**
 * Adds a new currency to the database using the provided details.
 * @summary Create a new currency entry
 */
export type currencyEndpointsCreateCurrencyEnigmaV1CurrencyPostResponse200 = {
    data: ApiResponseCurrency;
    status: 200;
};

export type currencyEndpointsCreateCurrencyEnigmaV1CurrencyPostResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type currencyEndpointsCreateCurrencyEnigmaV1CurrencyPostResponseComposite =
    | currencyEndpointsCreateCurrencyEnigmaV1CurrencyPostResponse200
    | currencyEndpointsCreateCurrencyEnigmaV1CurrencyPostResponse422;

export type currencyEndpointsCreateCurrencyEnigmaV1CurrencyPostResponse =
    currencyEndpointsCreateCurrencyEnigmaV1CurrencyPostResponseComposite & {
        headers: Headers;
    };

export const getCurrencyEndpointsCreateCurrencyEnigmaV1CurrencyPostUrl = () => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/currency`;
};

export const currencyEndpointsCreateCurrencyEnigmaV1CurrencyPost = async (
    currencyCreate: CurrencyCreate,
    options?: RequestInit
): Promise<currencyEndpointsCreateCurrencyEnigmaV1CurrencyPostResponse> => {
    const res = await fetch(getCurrencyEndpointsCreateCurrencyEnigmaV1CurrencyPostUrl(), {
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(currencyCreate)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();
    const data: currencyEndpointsCreateCurrencyEnigmaV1CurrencyPostResponse["data"] = body ? JSON.parse(body) : {};

    return {
        data,
        status: res.status,
        headers: res.headers
    } as currencyEndpointsCreateCurrencyEnigmaV1CurrencyPostResponse;
};

/**
 * Fetches details of a currency identified by its unique currency code.
 * @summary Get details of a specific currency
 */
export type currencyEndpointsGetCurrencyEnigmaV1CurrencyCurrencyCodeGetResponse200 = {
    data: ApiResponseCurrency;
    status: 200;
};

export type currencyEndpointsGetCurrencyEnigmaV1CurrencyCurrencyCodeGetResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type currencyEndpointsGetCurrencyEnigmaV1CurrencyCurrencyCodeGetResponseComposite =
    | currencyEndpointsGetCurrencyEnigmaV1CurrencyCurrencyCodeGetResponse200
    | currencyEndpointsGetCurrencyEnigmaV1CurrencyCurrencyCodeGetResponse422;

export type currencyEndpointsGetCurrencyEnigmaV1CurrencyCurrencyCodeGetResponse =
    currencyEndpointsGetCurrencyEnigmaV1CurrencyCurrencyCodeGetResponseComposite & {
        headers: Headers;
    };

export const getCurrencyEndpointsGetCurrencyEnigmaV1CurrencyCurrencyCodeGetUrl = (currencyCode: string) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/currency/${currencyCode}`;
};

export const currencyEndpointsGetCurrencyEnigmaV1CurrencyCurrencyCodeGet = async (
    currencyCode: string,
    options?: RequestInit
): Promise<currencyEndpointsGetCurrencyEnigmaV1CurrencyCurrencyCodeGetResponse> => {
    const res = await fetch(getCurrencyEndpointsGetCurrencyEnigmaV1CurrencyCurrencyCodeGetUrl(currencyCode), {
        ...options,
        method: "GET"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();
    const data: currencyEndpointsGetCurrencyEnigmaV1CurrencyCurrencyCodeGetResponse["data"] = body
        ? JSON.parse(body)
        : {};

    return {
        data,
        status: res.status,
        headers: res.headers
    } as currencyEndpointsGetCurrencyEnigmaV1CurrencyCurrencyCodeGetResponse;
};

/**
 * Modifies the details of a currency identified by its currency code.
 * @summary Update an existing currency
 */
export type currencyEndpointsUpdateCurrencyEnigmaV1CurrencyCurrencyCodePutResponse200 = {
    data: ApiResponseCurrency;
    status: 200;
};

export type currencyEndpointsUpdateCurrencyEnigmaV1CurrencyCurrencyCodePutResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type currencyEndpointsUpdateCurrencyEnigmaV1CurrencyCurrencyCodePutResponseComposite =
    | currencyEndpointsUpdateCurrencyEnigmaV1CurrencyCurrencyCodePutResponse200
    | currencyEndpointsUpdateCurrencyEnigmaV1CurrencyCurrencyCodePutResponse422;

export type currencyEndpointsUpdateCurrencyEnigmaV1CurrencyCurrencyCodePutResponse =
    currencyEndpointsUpdateCurrencyEnigmaV1CurrencyCurrencyCodePutResponseComposite & {
        headers: Headers;
    };

export const getCurrencyEndpointsUpdateCurrencyEnigmaV1CurrencyCurrencyCodePutUrl = (currencyCode: string) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/currency/${currencyCode}`;
};

export const currencyEndpointsUpdateCurrencyEnigmaV1CurrencyCurrencyCodePut = async (
    currencyCode: string,
    currencyUpdate: CurrencyUpdate,
    options?: RequestInit
): Promise<currencyEndpointsUpdateCurrencyEnigmaV1CurrencyCurrencyCodePutResponse> => {
    const res = await fetch(getCurrencyEndpointsUpdateCurrencyEnigmaV1CurrencyCurrencyCodePutUrl(currencyCode), {
        ...options,
        method: "PUT",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(currencyUpdate)
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();
    const data: currencyEndpointsUpdateCurrencyEnigmaV1CurrencyCurrencyCodePutResponse["data"] = body
        ? JSON.parse(body)
        : {};

    return {
        data,
        status: res.status,
        headers: res.headers
    } as currencyEndpointsUpdateCurrencyEnigmaV1CurrencyCurrencyCodePutResponse;
};

/**
 * Removes a currency from the database using its unique currency code.
 * @summary Delete a currency entry
 */
export type currencyEndpointsDeleteCurrencyEnigmaV1CurrencyCurrencyCodeDeleteResponse200 = {
    data: ApiResponseNoneType;
    status: 200;
};

export type currencyEndpointsDeleteCurrencyEnigmaV1CurrencyCurrencyCodeDeleteResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type currencyEndpointsDeleteCurrencyEnigmaV1CurrencyCurrencyCodeDeleteResponseComposite =
    | currencyEndpointsDeleteCurrencyEnigmaV1CurrencyCurrencyCodeDeleteResponse200
    | currencyEndpointsDeleteCurrencyEnigmaV1CurrencyCurrencyCodeDeleteResponse422;

export type currencyEndpointsDeleteCurrencyEnigmaV1CurrencyCurrencyCodeDeleteResponse =
    currencyEndpointsDeleteCurrencyEnigmaV1CurrencyCurrencyCodeDeleteResponseComposite & {
        headers: Headers;
    };

export const getCurrencyEndpointsDeleteCurrencyEnigmaV1CurrencyCurrencyCodeDeleteUrl = (currencyCode: string) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/currency/${currencyCode}`;
};

export const currencyEndpointsDeleteCurrencyEnigmaV1CurrencyCurrencyCodeDelete = async (
    currencyCode: string,
    options?: RequestInit
): Promise<currencyEndpointsDeleteCurrencyEnigmaV1CurrencyCurrencyCodeDeleteResponse> => {
    const res = await fetch(getCurrencyEndpointsDeleteCurrencyEnigmaV1CurrencyCurrencyCodeDeleteUrl(currencyCode), {
        ...options,
        method: "DELETE"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();
    const data: currencyEndpointsDeleteCurrencyEnigmaV1CurrencyCurrencyCodeDeleteResponse["data"] = body
        ? JSON.parse(body)
        : {};

    return {
        data,
        status: res.status,
        headers: res.headers
    } as currencyEndpointsDeleteCurrencyEnigmaV1CurrencyCurrencyCodeDeleteResponse;
};
