/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * BlowFish - Enigma API Service
 * OpenAPI spec version: develop
 */
import type {
    ApiResponseNoneType,
    ApiResponseOffsetPaginationProvider,
    ApiResponseProvider,
    ApiResponseProviderAddKeypair,
    HTTPValidationError,
    ProviderCreate,
    ProviderEndpointsAddKeypairEnigmaV1ProviderProviderNameAddKeypairPatchParams,
    ProviderEndpointsListProvidersEnigmaV1ProviderGetParams,
    ProviderUpdate
} from "../blowFishEnigmaAPIService.schemas";

import { authFetch } from "../../../helpers/orvalAuthFetchMiddleware";

/**
 * Fetches a paginated list of providers. Supports filtering and pagination parameters.
 * @summary Retrieve a paginated list of providers
 */
export type providerEndpointsListProvidersEnigmaV1ProviderGetResponse200 = {
    data: ApiResponseOffsetPaginationProvider;
    status: 200;
};

export type providerEndpointsListProvidersEnigmaV1ProviderGetResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type providerEndpointsListProvidersEnigmaV1ProviderGetResponseComposite =
    | providerEndpointsListProvidersEnigmaV1ProviderGetResponse200
    | providerEndpointsListProvidersEnigmaV1ProviderGetResponse422;

export type providerEndpointsListProvidersEnigmaV1ProviderGetResponse =
    providerEndpointsListProvidersEnigmaV1ProviderGetResponseComposite & {
        headers: Headers;
    };

export const getProviderEndpointsListProvidersEnigmaV1ProviderGetUrl = (
    params?: ProviderEndpointsListProvidersEnigmaV1ProviderGetParams
) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? "null" : value.toString());
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/provider?${stringifiedParams}`
        : `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/provider`;
};

export const providerEndpointsListProvidersEnigmaV1ProviderGet = async (
    params?: ProviderEndpointsListProvidersEnigmaV1ProviderGetParams,
    options?: RequestInit
): Promise<providerEndpointsListProvidersEnigmaV1ProviderGetResponse> => {
    return authFetch<providerEndpointsListProvidersEnigmaV1ProviderGetResponse>(
        getProviderEndpointsListProvidersEnigmaV1ProviderGetUrl(params),
        {
            ...options,
            method: "GET"
        }
    );
};

/**
 * Adds a new provider to the system with the specified details.
 * @summary Create a new provider
 */
export type providerEndpointsCreateProviderEnigmaV1ProviderPostResponse200 = {
    data: ApiResponseProvider;
    status: 200;
};

export type providerEndpointsCreateProviderEnigmaV1ProviderPostResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type providerEndpointsCreateProviderEnigmaV1ProviderPostResponseComposite =
    | providerEndpointsCreateProviderEnigmaV1ProviderPostResponse200
    | providerEndpointsCreateProviderEnigmaV1ProviderPostResponse422;

export type providerEndpointsCreateProviderEnigmaV1ProviderPostResponse =
    providerEndpointsCreateProviderEnigmaV1ProviderPostResponseComposite & {
        headers: Headers;
    };

export const getProviderEndpointsCreateProviderEnigmaV1ProviderPostUrl = () => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/provider`;
};

export const providerEndpointsCreateProviderEnigmaV1ProviderPost = async (
    providerCreate: ProviderCreate,
    options?: RequestInit
): Promise<providerEndpointsCreateProviderEnigmaV1ProviderPostResponse> => {
    return authFetch<providerEndpointsCreateProviderEnigmaV1ProviderPostResponse>(
        getProviderEndpointsCreateProviderEnigmaV1ProviderPostUrl(),
        {
            ...options,
            method: "POST",
            headers: { "Content-Type": "application/json", ...options?.headers },
            body: JSON.stringify(providerCreate)
        }
    );
};

/**
 * Retrieves details of a specific provider using its unique name.
 * @summary Get provider details by name
 */
export type providerEndpointsGetProviderEnigmaV1ProviderProviderNameGetResponse200 = {
    data: ApiResponseProvider;
    status: 200;
};

export type providerEndpointsGetProviderEnigmaV1ProviderProviderNameGetResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type providerEndpointsGetProviderEnigmaV1ProviderProviderNameGetResponseComposite =
    | providerEndpointsGetProviderEnigmaV1ProviderProviderNameGetResponse200
    | providerEndpointsGetProviderEnigmaV1ProviderProviderNameGetResponse422;

export type providerEndpointsGetProviderEnigmaV1ProviderProviderNameGetResponse =
    providerEndpointsGetProviderEnigmaV1ProviderProviderNameGetResponseComposite & {
        headers: Headers;
    };

export const getProviderEndpointsGetProviderEnigmaV1ProviderProviderNameGetUrl = (providerName: string) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/provider/${providerName}`;
};

export const providerEndpointsGetProviderEnigmaV1ProviderProviderNameGet = async (
    providerName: string,
    options?: RequestInit
): Promise<providerEndpointsGetProviderEnigmaV1ProviderProviderNameGetResponse> => {
    return authFetch<providerEndpointsGetProviderEnigmaV1ProviderProviderNameGetResponse>(
        getProviderEndpointsGetProviderEnigmaV1ProviderProviderNameGetUrl(providerName),
        {
            ...options,
            method: "GET"
        }
    );
};

/**
 * Updates the details of an existing provider identified by its name.
 * @summary Update provider details
 */
export type providerEndpointsUpdateProviderEnigmaV1ProviderProviderNamePutResponse200 = {
    data: ApiResponseProvider;
    status: 200;
};

export type providerEndpointsUpdateProviderEnigmaV1ProviderProviderNamePutResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type providerEndpointsUpdateProviderEnigmaV1ProviderProviderNamePutResponseComposite =
    | providerEndpointsUpdateProviderEnigmaV1ProviderProviderNamePutResponse200
    | providerEndpointsUpdateProviderEnigmaV1ProviderProviderNamePutResponse422;

export type providerEndpointsUpdateProviderEnigmaV1ProviderProviderNamePutResponse =
    providerEndpointsUpdateProviderEnigmaV1ProviderProviderNamePutResponseComposite & {
        headers: Headers;
    };

export const getProviderEndpointsUpdateProviderEnigmaV1ProviderProviderNamePutUrl = (providerName: string) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/provider/${providerName}`;
};

export const providerEndpointsUpdateProviderEnigmaV1ProviderProviderNamePut = async (
    providerName: string,
    providerUpdate: ProviderUpdate,
    options?: RequestInit
): Promise<providerEndpointsUpdateProviderEnigmaV1ProviderProviderNamePutResponse> => {
    return authFetch<providerEndpointsUpdateProviderEnigmaV1ProviderProviderNamePutResponse>(
        getProviderEndpointsUpdateProviderEnigmaV1ProviderProviderNamePutUrl(providerName),
        {
            ...options,
            method: "PUT",
            headers: { "Content-Type": "application/json", ...options?.headers },
            body: JSON.stringify(providerUpdate)
        }
    );
};

/**
 * Removes a provider from the system using its unique name.
 * @summary Delete a provider
 */
export type providerEndpointsDeleteProviderEnigmaV1ProviderProviderNameDeleteResponse200 = {
    data: ApiResponseNoneType;
    status: 200;
};

export type providerEndpointsDeleteProviderEnigmaV1ProviderProviderNameDeleteResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type providerEndpointsDeleteProviderEnigmaV1ProviderProviderNameDeleteResponseComposite =
    | providerEndpointsDeleteProviderEnigmaV1ProviderProviderNameDeleteResponse200
    | providerEndpointsDeleteProviderEnigmaV1ProviderProviderNameDeleteResponse422;

export type providerEndpointsDeleteProviderEnigmaV1ProviderProviderNameDeleteResponse =
    providerEndpointsDeleteProviderEnigmaV1ProviderProviderNameDeleteResponseComposite & {
        headers: Headers;
    };

export const getProviderEndpointsDeleteProviderEnigmaV1ProviderProviderNameDeleteUrl = (providerName: string) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/provider/${providerName}`;
};

export const providerEndpointsDeleteProviderEnigmaV1ProviderProviderNameDelete = async (
    providerName: string,
    options?: RequestInit
): Promise<providerEndpointsDeleteProviderEnigmaV1ProviderProviderNameDeleteResponse> => {
    return authFetch<providerEndpointsDeleteProviderEnigmaV1ProviderProviderNameDeleteResponse>(
        getProviderEndpointsDeleteProviderEnigmaV1ProviderProviderNameDeleteUrl(providerName),
        {
            ...options,
            method: "DELETE"
        }
    );
};

/**
 * Generates an RSA key pair with specified parameters and associates its public key with the provider.
 * @summary Add RSA key pair to provider
 */
export type providerEndpointsAddKeypairEnigmaV1ProviderProviderNameAddKeypairPatchResponse200 = {
    data: ApiResponseProviderAddKeypair;
    status: 200;
};

export type providerEndpointsAddKeypairEnigmaV1ProviderProviderNameAddKeypairPatchResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type providerEndpointsAddKeypairEnigmaV1ProviderProviderNameAddKeypairPatchResponseComposite =
    | providerEndpointsAddKeypairEnigmaV1ProviderProviderNameAddKeypairPatchResponse200
    | providerEndpointsAddKeypairEnigmaV1ProviderProviderNameAddKeypairPatchResponse422;

export type providerEndpointsAddKeypairEnigmaV1ProviderProviderNameAddKeypairPatchResponse =
    providerEndpointsAddKeypairEnigmaV1ProviderProviderNameAddKeypairPatchResponseComposite & {
        headers: Headers;
    };

export const getProviderEndpointsAddKeypairEnigmaV1ProviderProviderNameAddKeypairPatchUrl = (
    providerName: string,
    params?: ProviderEndpointsAddKeypairEnigmaV1ProviderProviderNameAddKeypairPatchParams
) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? "null" : value.toString());
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/provider/${providerName}/add_keypair?${stringifiedParams}`
        : `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/provider/${providerName}/add_keypair`;
};

export const providerEndpointsAddKeypairEnigmaV1ProviderProviderNameAddKeypairPatch = async (
    providerName: string,
    params?: ProviderEndpointsAddKeypairEnigmaV1ProviderProviderNameAddKeypairPatchParams,
    options?: RequestInit
): Promise<providerEndpointsAddKeypairEnigmaV1ProviderProviderNameAddKeypairPatchResponse> => {
    return authFetch<providerEndpointsAddKeypairEnigmaV1ProviderProviderNameAddKeypairPatchResponse>(
        getProviderEndpointsAddKeypairEnigmaV1ProviderProviderNameAddKeypairPatchUrl(providerName, params),
        {
            ...options,
            method: "PATCH"
        }
    );
};
