/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * BlowFish - CallBridge API Service
 * OpenAPI spec version: local
 */
import type {
    ApiResponseNoneType,
    ApiResponseOffsetPaginationCallbackHistoryRead,
    CallbackHistoryEndpointsGetCallbackCallbridgeV1HistoryCallbackIdGetParams,
    CallbackHistoryEndpointsListHistoryCallbridgeV1HistoryGetParams,
    HTTPValidationError
} from "../blowFishCallBridgeAPIService.schemas";

/**
 * @summary List callback history records
 */
export type callbackHistoryEndpointsListHistoryCallbridgeV1HistoryGetResponse200 = {
    data: ApiResponseOffsetPaginationCallbackHistoryRead;
    status: 200;
};

export type callbackHistoryEndpointsListHistoryCallbridgeV1HistoryGetResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type callbackHistoryEndpointsListHistoryCallbridgeV1HistoryGetResponseComposite =
    | callbackHistoryEndpointsListHistoryCallbridgeV1HistoryGetResponse200
    | callbackHistoryEndpointsListHistoryCallbridgeV1HistoryGetResponse422;

export type callbackHistoryEndpointsListHistoryCallbridgeV1HistoryGetResponse =
    callbackHistoryEndpointsListHistoryCallbridgeV1HistoryGetResponseComposite & {
        headers: Headers;
    };

export const getCallbackHistoryEndpointsListHistoryCallbridgeV1HistoryGetUrl = (
    params?: CallbackHistoryEndpointsListHistoryCallbridgeV1HistoryGetParams
) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? "null" : value.toString());
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `https://apigate.develop.blowfish.api4ftx.cloud/callbridge/v1/history?${stringifiedParams}`
        : `https://apigate.develop.blowfish.api4ftx.cloud/callbridge/v1/history`;
};

export const callbackHistoryEndpointsListHistoryCallbridgeV1HistoryGet = async (
    params?: CallbackHistoryEndpointsListHistoryCallbridgeV1HistoryGetParams,
    options?: RequestInit
): Promise<callbackHistoryEndpointsListHistoryCallbridgeV1HistoryGetResponse> => {
    const res = await fetch(getCallbackHistoryEndpointsListHistoryCallbridgeV1HistoryGetUrl(params), {
        ...options,
        method: "GET"
    });

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();
    const data: callbackHistoryEndpointsListHistoryCallbridgeV1HistoryGetResponse["data"] = body
        ? JSON.parse(body)
        : {};

    return {
        data,
        status: res.status,
        headers: res.headers
    } as callbackHistoryEndpointsListHistoryCallbridgeV1HistoryGetResponse;
};

/**
 * @summary Get callback record by ID
 */
export type callbackHistoryEndpointsGetCallbackCallbridgeV1HistoryCallbackIdGetResponse200 = {
    data: ApiResponseOffsetPaginationCallbackHistoryRead;
    status: 200;
};

export type callbackHistoryEndpointsGetCallbackCallbridgeV1HistoryCallbackIdGetResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type callbackHistoryEndpointsGetCallbackCallbridgeV1HistoryCallbackIdGetResponseComposite =
    | callbackHistoryEndpointsGetCallbackCallbridgeV1HistoryCallbackIdGetResponse200
    | callbackHistoryEndpointsGetCallbackCallbridgeV1HistoryCallbackIdGetResponse422;

export type callbackHistoryEndpointsGetCallbackCallbridgeV1HistoryCallbackIdGetResponse =
    callbackHistoryEndpointsGetCallbackCallbridgeV1HistoryCallbackIdGetResponseComposite & {
        headers: Headers;
    };

export const getCallbackHistoryEndpointsGetCallbackCallbridgeV1HistoryCallbackIdGetUrl = (
    callbackId: string,
    params?: CallbackHistoryEndpointsGetCallbackCallbridgeV1HistoryCallbackIdGetParams
) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? "null" : value.toString());
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `https://apigate.develop.blowfish.api4ftx.cloud/callbridge/v1/history/${callbackId}?${stringifiedParams}`
        : `https://apigate.develop.blowfish.api4ftx.cloud/callbridge/v1/history/${callbackId}`;
};

export const callbackHistoryEndpointsGetCallbackCallbridgeV1HistoryCallbackIdGet = async (
    callbackId: string,
    params?: CallbackHistoryEndpointsGetCallbackCallbridgeV1HistoryCallbackIdGetParams,
    options?: RequestInit
): Promise<callbackHistoryEndpointsGetCallbackCallbridgeV1HistoryCallbackIdGetResponse> => {
    const res = await fetch(
        getCallbackHistoryEndpointsGetCallbackCallbridgeV1HistoryCallbackIdGetUrl(callbackId, params),
        {
            ...options,
            method: "GET"
        }
    );

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();
    const data: callbackHistoryEndpointsGetCallbackCallbridgeV1HistoryCallbackIdGetResponse["data"] = body
        ? JSON.parse(body)
        : {};

    return {
        data,
        status: res.status,
        headers: res.headers
    } as callbackHistoryEndpointsGetCallbackCallbridgeV1HistoryCallbackIdGetResponse;
};

/**
 * @summary Retry callback by history ID
 */
export type callbackHistoryEndpointsRetryByHistoryCallbridgeV1HistoryHistoryHistoryIdRetryPostResponse200 = {
    data: ApiResponseNoneType;
    status: 200;
};

export type callbackHistoryEndpointsRetryByHistoryCallbridgeV1HistoryHistoryHistoryIdRetryPostResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type callbackHistoryEndpointsRetryByHistoryCallbridgeV1HistoryHistoryHistoryIdRetryPostResponseComposite =
    | callbackHistoryEndpointsRetryByHistoryCallbridgeV1HistoryHistoryHistoryIdRetryPostResponse200
    | callbackHistoryEndpointsRetryByHistoryCallbridgeV1HistoryHistoryHistoryIdRetryPostResponse422;

export type callbackHistoryEndpointsRetryByHistoryCallbridgeV1HistoryHistoryHistoryIdRetryPostResponse =
    callbackHistoryEndpointsRetryByHistoryCallbridgeV1HistoryHistoryHistoryIdRetryPostResponseComposite & {
        headers: Headers;
    };

export const getCallbackHistoryEndpointsRetryByHistoryCallbridgeV1HistoryHistoryHistoryIdRetryPostUrl = (
    historyId: string
) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/callbridge/v1/history/history/${historyId}/retry`;
};

export const callbackHistoryEndpointsRetryByHistoryCallbridgeV1HistoryHistoryHistoryIdRetryPost = async (
    historyId: string,
    options?: RequestInit
): Promise<callbackHistoryEndpointsRetryByHistoryCallbridgeV1HistoryHistoryHistoryIdRetryPostResponse> => {
    const res = await fetch(
        getCallbackHistoryEndpointsRetryByHistoryCallbridgeV1HistoryHistoryHistoryIdRetryPostUrl(historyId),
        {
            ...options,
            method: "POST"
        }
    );

    const body = [204, 205, 304].includes(res.status) ? null : await res.text();
    const data: callbackHistoryEndpointsRetryByHistoryCallbridgeV1HistoryHistoryHistoryIdRetryPostResponse["data"] =
        body ? JSON.parse(body) : {};

    return {
        data,
        status: res.status,
        headers: res.headers
    } as callbackHistoryEndpointsRetryByHistoryCallbridgeV1HistoryHistoryHistoryIdRetryPostResponse;
};
