/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * BlowFish - CallBridge API Service
 * OpenAPI spec version: develop
 */
import type {
    ApiResponseCallbackRetryResponse,
    ApiResponseDeliveryRequestMessage,
    ApiResponseOffsetPaginationCallbackHistoryRead,
    CallbackHistoryEndpointsGetCallbackCallbridgeV1HistoryCallbackIdGetParams,
    CallbackHistoryEndpointsListHistoryCallbridgeV1HistoryGetParams,
    CallbackRetryRequestItems,
    HTTPValidationError
} from "../blowFishCallBridgeAPIService.schemas";

import { authFetch } from "../../../helpers/orvalAuthFetchMiddleware";

/**
 * @summary List callback history records
 */
export type callbackHistoryEndpointsListHistoryCallbridgeV1HistoryGetResponse200 = {
    data: ApiResponseOffsetPaginationCallbackHistoryRead;
    status: 200;
};

export type callbackHistoryEndpointsListHistoryCallbridgeV1HistoryGetResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type callbackHistoryEndpointsListHistoryCallbridgeV1HistoryGetResponseComposite =
    | callbackHistoryEndpointsListHistoryCallbridgeV1HistoryGetResponse200
    | callbackHistoryEndpointsListHistoryCallbridgeV1HistoryGetResponse422;

export type callbackHistoryEndpointsListHistoryCallbridgeV1HistoryGetResponse =
    callbackHistoryEndpointsListHistoryCallbridgeV1HistoryGetResponseComposite & {
        headers: Headers;
    };

export const getCallbackHistoryEndpointsListHistoryCallbridgeV1HistoryGetUrl = (
    params?: CallbackHistoryEndpointsListHistoryCallbridgeV1HistoryGetParams
) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? "null" : value.toString());
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `https://api.develop.blowfish.api4ftx.cloud/callbridge/v1/history?${stringifiedParams}`
        : `https://api.develop.blowfish.api4ftx.cloud/callbridge/v1/history`;
};

export const callbackHistoryEndpointsListHistoryCallbridgeV1HistoryGet = async (
    params?: CallbackHistoryEndpointsListHistoryCallbridgeV1HistoryGetParams,
    options?: RequestInit
): Promise<callbackHistoryEndpointsListHistoryCallbridgeV1HistoryGetResponse> => {
    return authFetch<callbackHistoryEndpointsListHistoryCallbridgeV1HistoryGetResponse>(
        getCallbackHistoryEndpointsListHistoryCallbridgeV1HistoryGetUrl(params),
        {
            ...options,
            method: "GET"
        }
    );
};

/**
 * @summary Get callback record by ID
 */
export type callbackHistoryEndpointsGetCallbackCallbridgeV1HistoryCallbackIdGetResponse200 = {
    data: ApiResponseOffsetPaginationCallbackHistoryRead;
    status: 200;
};

export type callbackHistoryEndpointsGetCallbackCallbridgeV1HistoryCallbackIdGetResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type callbackHistoryEndpointsGetCallbackCallbridgeV1HistoryCallbackIdGetResponseComposite =
    | callbackHistoryEndpointsGetCallbackCallbridgeV1HistoryCallbackIdGetResponse200
    | callbackHistoryEndpointsGetCallbackCallbridgeV1HistoryCallbackIdGetResponse422;

export type callbackHistoryEndpointsGetCallbackCallbridgeV1HistoryCallbackIdGetResponse =
    callbackHistoryEndpointsGetCallbackCallbridgeV1HistoryCallbackIdGetResponseComposite & {
        headers: Headers;
    };

export const getCallbackHistoryEndpointsGetCallbackCallbridgeV1HistoryCallbackIdGetUrl = (
    callbackId: string,
    params?: CallbackHistoryEndpointsGetCallbackCallbridgeV1HistoryCallbackIdGetParams
) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? "null" : value.toString());
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `https://api.develop.blowfish.api4ftx.cloud/callbridge/v1/history/${callbackId}?${stringifiedParams}`
        : `https://api.develop.blowfish.api4ftx.cloud/callbridge/v1/history/${callbackId}`;
};

export const callbackHistoryEndpointsGetCallbackCallbridgeV1HistoryCallbackIdGet = async (
    callbackId: string,
    params?: CallbackHistoryEndpointsGetCallbackCallbridgeV1HistoryCallbackIdGetParams,
    options?: RequestInit
): Promise<callbackHistoryEndpointsGetCallbackCallbridgeV1HistoryCallbackIdGetResponse> => {
    return authFetch<callbackHistoryEndpointsGetCallbackCallbridgeV1HistoryCallbackIdGetResponse>(
        getCallbackHistoryEndpointsGetCallbackCallbridgeV1HistoryCallbackIdGetUrl(callbackId, params),
        {
            ...options,
            method: "GET"
        }
    );
};

/**
 * This endpoint is deprecated and will be removed in a future version.
             Use `/callbridge/v1/history/retry/bulk`
 * @deprecated
 * @summary Retry callback by history ID
 */
export type callbackHistoryEndpointsRetryByCallbackIdCallbridgeV1HistoryCallbackIdRetryGetResponse200 = {
    data: ApiResponseDeliveryRequestMessage;
    status: 200;
};

export type callbackHistoryEndpointsRetryByCallbackIdCallbridgeV1HistoryCallbackIdRetryGetResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type callbackHistoryEndpointsRetryByCallbackIdCallbridgeV1HistoryCallbackIdRetryGetResponseComposite =
    | callbackHistoryEndpointsRetryByCallbackIdCallbridgeV1HistoryCallbackIdRetryGetResponse200
    | callbackHistoryEndpointsRetryByCallbackIdCallbridgeV1HistoryCallbackIdRetryGetResponse422;

export type callbackHistoryEndpointsRetryByCallbackIdCallbridgeV1HistoryCallbackIdRetryGetResponse =
    callbackHistoryEndpointsRetryByCallbackIdCallbridgeV1HistoryCallbackIdRetryGetResponseComposite & {
        headers: Headers;
    };

export const getCallbackHistoryEndpointsRetryByCallbackIdCallbridgeV1HistoryCallbackIdRetryGetUrl = (
    callbackId: string
) => {
    return `https://api.develop.blowfish.api4ftx.cloud/callbridge/v1/history/${callbackId}/retry`;
};

export const callbackHistoryEndpointsRetryByCallbackIdCallbridgeV1HistoryCallbackIdRetryGet = async (
    callbackId: string,
    options?: RequestInit
): Promise<callbackHistoryEndpointsRetryByCallbackIdCallbridgeV1HistoryCallbackIdRetryGetResponse> => {
    return authFetch<callbackHistoryEndpointsRetryByCallbackIdCallbridgeV1HistoryCallbackIdRetryGetResponse>(
        getCallbackHistoryEndpointsRetryByCallbackIdCallbridgeV1HistoryCallbackIdRetryGetUrl(callbackId),
        {
            ...options,
            method: "GET"
        }
    );
};

/**
 * @summary Retry all callbacks by listed history IDs
 */
export type callbackHistoryEndpointsRetryBulkByCallbackIdsCallbridgeV1HistoryRetryBulkPostResponse200 = {
    data: ApiResponseCallbackRetryResponse;
    status: 200;
};

export type callbackHistoryEndpointsRetryBulkByCallbackIdsCallbridgeV1HistoryRetryBulkPostResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type callbackHistoryEndpointsRetryBulkByCallbackIdsCallbridgeV1HistoryRetryBulkPostResponseComposite =
    | callbackHistoryEndpointsRetryBulkByCallbackIdsCallbridgeV1HistoryRetryBulkPostResponse200
    | callbackHistoryEndpointsRetryBulkByCallbackIdsCallbridgeV1HistoryRetryBulkPostResponse422;

export type callbackHistoryEndpointsRetryBulkByCallbackIdsCallbridgeV1HistoryRetryBulkPostResponse =
    callbackHistoryEndpointsRetryBulkByCallbackIdsCallbridgeV1HistoryRetryBulkPostResponseComposite & {
        headers: Headers;
    };

export const getCallbackHistoryEndpointsRetryBulkByCallbackIdsCallbridgeV1HistoryRetryBulkPostUrl = () => {
    return `https://api.develop.blowfish.api4ftx.cloud/callbridge/v1/history/retry/bulk`;
};

export const callbackHistoryEndpointsRetryBulkByCallbackIdsCallbridgeV1HistoryRetryBulkPost = async (
    callbackRetryRequestItems: CallbackRetryRequestItems,
    options?: RequestInit
): Promise<callbackHistoryEndpointsRetryBulkByCallbackIdsCallbridgeV1HistoryRetryBulkPostResponse> => {
    return authFetch<callbackHistoryEndpointsRetryBulkByCallbackIdsCallbridgeV1HistoryRetryBulkPostResponse>(
        getCallbackHistoryEndpointsRetryBulkByCallbackIdsCallbridgeV1HistoryRetryBulkPostUrl(),
        {
            ...options,
            method: "POST",
            headers: { "Content-Type": "application/json", ...options?.headers },
            body: JSON.stringify(callbackRetryRequestItems)
        }
    );
};
