/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * BlowFish - Enigma API Service
 * OpenAPI spec version: develop
 */
import type {
    ApiResponseNoneType,
    ApiResponseOffsetPaginationTerminalInstrumentConfiguration,
    ApiResponseTerminalInstrumentConfiguration,
    HTTPValidationError,
    TerminalInstrumentConfigurationCreate,
    TerminalInstrumentConfigurationEndpointsGetTerminalInstrumentConfigurationsByTerminalEnigmaV1TerminalInstrumentConfigurationsTerminalsTerminalIdInstrumentConfigurationsGetParams,
    TerminalInstrumentConfigurationEndpointsListTerminalInstrumentConfigurationsEnigmaV1TerminalInstrumentConfigurationsGetParams,
    TerminalInstrumentConfigurationUpdate
} from "../blowFishEnigmaAPIService.schemas";

import { authFetch } from "../../../helpers/orvalAuthFetchMiddleware";

/**
 * Returns a list of terminal payment instruments associated with a given terminal ID.
 * @summary Get terminal payment instruments for a specific terminal
 */
export type terminalInstrumentConfigurationEndpointsGetTerminalInstrumentConfigurationsByTerminalEnigmaV1TerminalInstrumentConfigurationsTerminalsTerminalIdInstrumentConfigurationsGetResponse200 =
    {
        data: ApiResponseOffsetPaginationTerminalInstrumentConfiguration;
        status: 200;
    };

export type terminalInstrumentConfigurationEndpointsGetTerminalInstrumentConfigurationsByTerminalEnigmaV1TerminalInstrumentConfigurationsTerminalsTerminalIdInstrumentConfigurationsGetResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type terminalInstrumentConfigurationEndpointsGetTerminalInstrumentConfigurationsByTerminalEnigmaV1TerminalInstrumentConfigurationsTerminalsTerminalIdInstrumentConfigurationsGetResponseComposite =

        | terminalInstrumentConfigurationEndpointsGetTerminalInstrumentConfigurationsByTerminalEnigmaV1TerminalInstrumentConfigurationsTerminalsTerminalIdInstrumentConfigurationsGetResponse200
        | terminalInstrumentConfigurationEndpointsGetTerminalInstrumentConfigurationsByTerminalEnigmaV1TerminalInstrumentConfigurationsTerminalsTerminalIdInstrumentConfigurationsGetResponse422;

export type terminalInstrumentConfigurationEndpointsGetTerminalInstrumentConfigurationsByTerminalEnigmaV1TerminalInstrumentConfigurationsTerminalsTerminalIdInstrumentConfigurationsGetResponse =
    terminalInstrumentConfigurationEndpointsGetTerminalInstrumentConfigurationsByTerminalEnigmaV1TerminalInstrumentConfigurationsTerminalsTerminalIdInstrumentConfigurationsGetResponseComposite & {
        headers: Headers;
    };

export const getTerminalInstrumentConfigurationEndpointsGetTerminalInstrumentConfigurationsByTerminalEnigmaV1TerminalInstrumentConfigurationsTerminalsTerminalIdInstrumentConfigurationsGetUrl =
    (
        terminalId: string,
        params?: TerminalInstrumentConfigurationEndpointsGetTerminalInstrumentConfigurationsByTerminalEnigmaV1TerminalInstrumentConfigurationsTerminalsTerminalIdInstrumentConfigurationsGetParams
    ) => {
        const normalizedParams = new URLSearchParams();

        Object.entries(params || {}).forEach(([key, value]) => {
            if (value !== undefined) {
                normalizedParams.append(key, value === null ? "null" : value.toString());
            }
        });

        const stringifiedParams = normalizedParams.toString();

        return stringifiedParams.length > 0
            ? `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/terminal-instrument-configurations/terminals/${terminalId}/instrument-configurations?${stringifiedParams}`
            : `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/terminal-instrument-configurations/terminals/${terminalId}/instrument-configurations`;
    };

export const terminalInstrumentConfigurationEndpointsGetTerminalInstrumentConfigurationsByTerminalEnigmaV1TerminalInstrumentConfigurationsTerminalsTerminalIdInstrumentConfigurationsGet =
    async (
        terminalId: string,
        params?: TerminalInstrumentConfigurationEndpointsGetTerminalInstrumentConfigurationsByTerminalEnigmaV1TerminalInstrumentConfigurationsTerminalsTerminalIdInstrumentConfigurationsGetParams,
        options?: RequestInit
    ): Promise<terminalInstrumentConfigurationEndpointsGetTerminalInstrumentConfigurationsByTerminalEnigmaV1TerminalInstrumentConfigurationsTerminalsTerminalIdInstrumentConfigurationsGetResponse> => {
        return authFetch<terminalInstrumentConfigurationEndpointsGetTerminalInstrumentConfigurationsByTerminalEnigmaV1TerminalInstrumentConfigurationsTerminalsTerminalIdInstrumentConfigurationsGetResponse>(
            getTerminalInstrumentConfigurationEndpointsGetTerminalInstrumentConfigurationsByTerminalEnigmaV1TerminalInstrumentConfigurationsTerminalsTerminalIdInstrumentConfigurationsGetUrl(
                terminalId,
                params
            ),
            {
                ...options,
                method: "GET"
            }
        );
    };

/**
 * Returns a paginated list of terminal payment instruments with optional filtering.
 * @summary Get a paginated list of terminal payment instruments
 */
export type terminalInstrumentConfigurationEndpointsListTerminalInstrumentConfigurationsEnigmaV1TerminalInstrumentConfigurationsGetResponse200 =
    {
        data: ApiResponseOffsetPaginationTerminalInstrumentConfiguration;
        status: 200;
    };

export type terminalInstrumentConfigurationEndpointsListTerminalInstrumentConfigurationsEnigmaV1TerminalInstrumentConfigurationsGetResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type terminalInstrumentConfigurationEndpointsListTerminalInstrumentConfigurationsEnigmaV1TerminalInstrumentConfigurationsGetResponseComposite =

        | terminalInstrumentConfigurationEndpointsListTerminalInstrumentConfigurationsEnigmaV1TerminalInstrumentConfigurationsGetResponse200
        | terminalInstrumentConfigurationEndpointsListTerminalInstrumentConfigurationsEnigmaV1TerminalInstrumentConfigurationsGetResponse422;

export type terminalInstrumentConfigurationEndpointsListTerminalInstrumentConfigurationsEnigmaV1TerminalInstrumentConfigurationsGetResponse =
    terminalInstrumentConfigurationEndpointsListTerminalInstrumentConfigurationsEnigmaV1TerminalInstrumentConfigurationsGetResponseComposite & {
        headers: Headers;
    };

export const getTerminalInstrumentConfigurationEndpointsListTerminalInstrumentConfigurationsEnigmaV1TerminalInstrumentConfigurationsGetUrl =
    (
        params?: TerminalInstrumentConfigurationEndpointsListTerminalInstrumentConfigurationsEnigmaV1TerminalInstrumentConfigurationsGetParams
    ) => {
        const normalizedParams = new URLSearchParams();

        Object.entries(params || {}).forEach(([key, value]) => {
            if (value !== undefined) {
                normalizedParams.append(key, value === null ? "null" : value.toString());
            }
        });

        const stringifiedParams = normalizedParams.toString();

        return stringifiedParams.length > 0
            ? `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/terminal-instrument-configurations?${stringifiedParams}`
            : `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/terminal-instrument-configurations`;
    };

export const terminalInstrumentConfigurationEndpointsListTerminalInstrumentConfigurationsEnigmaV1TerminalInstrumentConfigurationsGet =
    async (
        params?: TerminalInstrumentConfigurationEndpointsListTerminalInstrumentConfigurationsEnigmaV1TerminalInstrumentConfigurationsGetParams,
        options?: RequestInit
    ): Promise<terminalInstrumentConfigurationEndpointsListTerminalInstrumentConfigurationsEnigmaV1TerminalInstrumentConfigurationsGetResponse> => {
        return authFetch<terminalInstrumentConfigurationEndpointsListTerminalInstrumentConfigurationsEnigmaV1TerminalInstrumentConfigurationsGetResponse>(
            getTerminalInstrumentConfigurationEndpointsListTerminalInstrumentConfigurationsEnigmaV1TerminalInstrumentConfigurationsGetUrl(
                params
            ),
            {
                ...options,
                method: "GET"
            }
        );
    };

/**
 * Registers a new terminal payment instrument.
 * @summary Create a new terminal payment instrument
 */
export type terminalInstrumentConfigurationEndpointsCreateTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsPostResponse200 =
    {
        data: ApiResponseTerminalInstrumentConfiguration;
        status: 200;
    };

export type terminalInstrumentConfigurationEndpointsCreateTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsPostResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type terminalInstrumentConfigurationEndpointsCreateTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsPostResponseComposite =

        | terminalInstrumentConfigurationEndpointsCreateTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsPostResponse200
        | terminalInstrumentConfigurationEndpointsCreateTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsPostResponse422;

export type terminalInstrumentConfigurationEndpointsCreateTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsPostResponse =
    terminalInstrumentConfigurationEndpointsCreateTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsPostResponseComposite & {
        headers: Headers;
    };

export const getTerminalInstrumentConfigurationEndpointsCreateTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsPostUrl =
    () => {
        return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/terminal-instrument-configurations`;
    };

export const terminalInstrumentConfigurationEndpointsCreateTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsPost =
    async (
        terminalInstrumentConfigurationCreate: TerminalInstrumentConfigurationCreate,
        options?: RequestInit
    ): Promise<terminalInstrumentConfigurationEndpointsCreateTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsPostResponse> => {
        return authFetch<terminalInstrumentConfigurationEndpointsCreateTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsPostResponse>(
            getTerminalInstrumentConfigurationEndpointsCreateTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsPostUrl(),
            {
                ...options,
                method: "POST",
                headers: { "Content-Type": "application/json", ...options?.headers },
                body: JSON.stringify(terminalInstrumentConfigurationCreate)
            }
        );
    };

/**
 * Returns the details of a specific terminal payment instrument.
 * @summary Get a single terminal payment instrument by ID
 */
export type terminalInstrumentConfigurationEndpointsGetTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsTerminalPaymentInstrumentIdGetResponse200 =
    {
        data: ApiResponseTerminalInstrumentConfiguration;
        status: 200;
    };

export type terminalInstrumentConfigurationEndpointsGetTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsTerminalPaymentInstrumentIdGetResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type terminalInstrumentConfigurationEndpointsGetTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsTerminalPaymentInstrumentIdGetResponseComposite =

        | terminalInstrumentConfigurationEndpointsGetTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsTerminalPaymentInstrumentIdGetResponse200
        | terminalInstrumentConfigurationEndpointsGetTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsTerminalPaymentInstrumentIdGetResponse422;

export type terminalInstrumentConfigurationEndpointsGetTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsTerminalPaymentInstrumentIdGetResponse =
    terminalInstrumentConfigurationEndpointsGetTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsTerminalPaymentInstrumentIdGetResponseComposite & {
        headers: Headers;
    };

export const getTerminalInstrumentConfigurationEndpointsGetTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsTerminalPaymentInstrumentIdGetUrl =
    (terminalPaymentInstrumentId: string) => {
        return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/terminal-instrument-configurations/${terminalPaymentInstrumentId}`;
    };

export const terminalInstrumentConfigurationEndpointsGetTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsTerminalPaymentInstrumentIdGet =
    async (
        terminalPaymentInstrumentId: string,
        options?: RequestInit
    ): Promise<terminalInstrumentConfigurationEndpointsGetTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsTerminalPaymentInstrumentIdGetResponse> => {
        return authFetch<terminalInstrumentConfigurationEndpointsGetTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsTerminalPaymentInstrumentIdGetResponse>(
            getTerminalInstrumentConfigurationEndpointsGetTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsTerminalPaymentInstrumentIdGetUrl(
                terminalPaymentInstrumentId
            ),
            {
                ...options,
                method: "GET"
            }
        );
    };

/**
 * Partially updates an existing terminal payment instrument.
 * @summary Partially update a terminal payment instrument
 */
export type terminalInstrumentConfigurationEndpointsPatchTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsTerminalPaymentInstrumentIdPatchResponse200 =
    {
        data: ApiResponseTerminalInstrumentConfiguration;
        status: 200;
    };

export type terminalInstrumentConfigurationEndpointsPatchTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsTerminalPaymentInstrumentIdPatchResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type terminalInstrumentConfigurationEndpointsPatchTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsTerminalPaymentInstrumentIdPatchResponseComposite =

        | terminalInstrumentConfigurationEndpointsPatchTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsTerminalPaymentInstrumentIdPatchResponse200
        | terminalInstrumentConfigurationEndpointsPatchTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsTerminalPaymentInstrumentIdPatchResponse422;

export type terminalInstrumentConfigurationEndpointsPatchTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsTerminalPaymentInstrumentIdPatchResponse =
    terminalInstrumentConfigurationEndpointsPatchTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsTerminalPaymentInstrumentIdPatchResponseComposite & {
        headers: Headers;
    };

export const getTerminalInstrumentConfigurationEndpointsPatchTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsTerminalPaymentInstrumentIdPatchUrl =
    (terminalPaymentInstrumentId: string) => {
        return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/terminal-instrument-configurations/${terminalPaymentInstrumentId}`;
    };

export const terminalInstrumentConfigurationEndpointsPatchTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsTerminalPaymentInstrumentIdPatch =
    async (
        terminalPaymentInstrumentId: string,
        terminalInstrumentConfigurationUpdate: TerminalInstrumentConfigurationUpdate,
        options?: RequestInit
    ): Promise<terminalInstrumentConfigurationEndpointsPatchTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsTerminalPaymentInstrumentIdPatchResponse> => {
        return authFetch<terminalInstrumentConfigurationEndpointsPatchTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsTerminalPaymentInstrumentIdPatchResponse>(
            getTerminalInstrumentConfigurationEndpointsPatchTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsTerminalPaymentInstrumentIdPatchUrl(
                terminalPaymentInstrumentId
            ),
            {
                ...options,
                method: "PATCH",
                headers: { "Content-Type": "application/json", ...options?.headers },
                body: JSON.stringify(terminalInstrumentConfigurationUpdate)
            }
        );
    };

/**
 * Deletes a terminal payment instrument by ID.
 * @summary Delete a terminal payment instrument
 */
export type terminalInstrumentConfigurationEndpointsDeleteTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsTerminalPaymentInstrumentIdDeleteResponse200 =
    {
        data: ApiResponseNoneType;
        status: 200;
    };

export type terminalInstrumentConfigurationEndpointsDeleteTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsTerminalPaymentInstrumentIdDeleteResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type terminalInstrumentConfigurationEndpointsDeleteTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsTerminalPaymentInstrumentIdDeleteResponseComposite =

        | terminalInstrumentConfigurationEndpointsDeleteTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsTerminalPaymentInstrumentIdDeleteResponse200
        | terminalInstrumentConfigurationEndpointsDeleteTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsTerminalPaymentInstrumentIdDeleteResponse422;

export type terminalInstrumentConfigurationEndpointsDeleteTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsTerminalPaymentInstrumentIdDeleteResponse =
    terminalInstrumentConfigurationEndpointsDeleteTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsTerminalPaymentInstrumentIdDeleteResponseComposite & {
        headers: Headers;
    };

export const getTerminalInstrumentConfigurationEndpointsDeleteTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsTerminalPaymentInstrumentIdDeleteUrl =
    (terminalPaymentInstrumentId: string) => {
        return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/terminal-instrument-configurations/${terminalPaymentInstrumentId}`;
    };

export const terminalInstrumentConfigurationEndpointsDeleteTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsTerminalPaymentInstrumentIdDelete =
    async (
        terminalPaymentInstrumentId: string,
        options?: RequestInit
    ): Promise<terminalInstrumentConfigurationEndpointsDeleteTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsTerminalPaymentInstrumentIdDeleteResponse> => {
        return authFetch<terminalInstrumentConfigurationEndpointsDeleteTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsTerminalPaymentInstrumentIdDeleteResponse>(
            getTerminalInstrumentConfigurationEndpointsDeleteTerminalInstrumentConfigurationEnigmaV1TerminalInstrumentConfigurationsTerminalPaymentInstrumentIdDeleteUrl(
                terminalPaymentInstrumentId
            ),
            {
                ...options,
                method: "DELETE"
            }
        );
    };
