/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * BlowFish - Enigma API Service
 * OpenAPI spec version: develop
 */
import type {
    ApiResponseNoneType,
    ApiResponseOffsetPaginationTerminalPaymentInstrument,
    ApiResponseTerminalPaymentInstrument,
    HTTPValidationError,
    TerminalPaymentInstrumentCreate,
    TerminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentsByTerminalEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdInstrumentConfigurationsGetParams,
    TerminalPaymentInstrumentEndpointsListTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsGetParams,
    TerminalPaymentInstrumentUpdate
} from "../blowFishEnigmaAPIService.schemas";

import { authFetch } from "../../../helpers/orvalAuthFetchMiddleware";

/**
 * Returns a list of terminal payment instruments associated with a given terminal ID.
 * @summary Get terminal payment instruments for a specific terminal
 */
export type terminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentsByTerminalEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdInstrumentConfigurationsGetResponse200 =
    {
        data: ApiResponseOffsetPaginationTerminalPaymentInstrument;
        status: 200;
    };

export type terminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentsByTerminalEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdInstrumentConfigurationsGetResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type terminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentsByTerminalEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdInstrumentConfigurationsGetResponseComposite =

        | terminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentsByTerminalEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdInstrumentConfigurationsGetResponse200
        | terminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentsByTerminalEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdInstrumentConfigurationsGetResponse422;

export type terminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentsByTerminalEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdInstrumentConfigurationsGetResponse =
    terminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentsByTerminalEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdInstrumentConfigurationsGetResponseComposite & {
        headers: Headers;
    };

export const getTerminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentsByTerminalEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdInstrumentConfigurationsGetUrl =
    (
        terminalId: string,
        params?: TerminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentsByTerminalEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdInstrumentConfigurationsGetParams
    ) => {
        const normalizedParams = new URLSearchParams();

        Object.entries(params || {}).forEach(([key, value]) => {
            if (value !== undefined) {
                normalizedParams.append(key, value === null ? "null" : value.toString());
            }
        });

        const stringifiedParams = normalizedParams.toString();

        return stringifiedParams.length > 0
            ? `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/terminal-payment-instruments/terminals/${terminalId}/instrument-configurations?${stringifiedParams}`
            : `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/terminal-payment-instruments/terminals/${terminalId}/instrument-configurations`;
    };

export const terminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentsByTerminalEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdInstrumentConfigurationsGet =
    async (
        terminalId: string,
        params?: TerminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentsByTerminalEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdInstrumentConfigurationsGetParams,
        options?: RequestInit
    ): Promise<terminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentsByTerminalEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdInstrumentConfigurationsGetResponse> => {
        return authFetch<terminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentsByTerminalEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdInstrumentConfigurationsGetResponse>(
            getTerminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentsByTerminalEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdInstrumentConfigurationsGetUrl(
                terminalId,
                params
            ),
            {
                ...options,
                method: "GET"
            }
        );
    };

/**
 * Returns a paginated list of terminal payment instruments with optional filtering.
 * @summary Get a paginated list of terminal payment instruments
 */
export type terminalPaymentInstrumentEndpointsListTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsGetResponse200 =
    {
        data: ApiResponseOffsetPaginationTerminalPaymentInstrument;
        status: 200;
    };

export type terminalPaymentInstrumentEndpointsListTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsGetResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type terminalPaymentInstrumentEndpointsListTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsGetResponseComposite =

        | terminalPaymentInstrumentEndpointsListTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsGetResponse200
        | terminalPaymentInstrumentEndpointsListTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsGetResponse422;

export type terminalPaymentInstrumentEndpointsListTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsGetResponse =
    terminalPaymentInstrumentEndpointsListTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsGetResponseComposite & {
        headers: Headers;
    };

export const getTerminalPaymentInstrumentEndpointsListTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsGetUrl =
    (
        params?: TerminalPaymentInstrumentEndpointsListTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsGetParams
    ) => {
        const normalizedParams = new URLSearchParams();

        Object.entries(params || {}).forEach(([key, value]) => {
            if (value !== undefined) {
                normalizedParams.append(key, value === null ? "null" : value.toString());
            }
        });

        const stringifiedParams = normalizedParams.toString();

        return stringifiedParams.length > 0
            ? `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/terminal-payment-instruments?${stringifiedParams}`
            : `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/terminal-payment-instruments`;
    };

export const terminalPaymentInstrumentEndpointsListTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsGet =
    async (
        params?: TerminalPaymentInstrumentEndpointsListTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsGetParams,
        options?: RequestInit
    ): Promise<terminalPaymentInstrumentEndpointsListTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsGetResponse> => {
        return authFetch<terminalPaymentInstrumentEndpointsListTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsGetResponse>(
            getTerminalPaymentInstrumentEndpointsListTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsGetUrl(
                params
            ),
            {
                ...options,
                method: "GET"
            }
        );
    };

/**
 * Registers a new terminal payment instrument.
 * @summary Create a new terminal payment instrument
 */
export type terminalPaymentInstrumentEndpointsCreateTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsPostResponse200 =
    {
        data: ApiResponseTerminalPaymentInstrument;
        status: 200;
    };

export type terminalPaymentInstrumentEndpointsCreateTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsPostResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type terminalPaymentInstrumentEndpointsCreateTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsPostResponseComposite =

        | terminalPaymentInstrumentEndpointsCreateTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsPostResponse200
        | terminalPaymentInstrumentEndpointsCreateTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsPostResponse422;

export type terminalPaymentInstrumentEndpointsCreateTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsPostResponse =
    terminalPaymentInstrumentEndpointsCreateTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsPostResponseComposite & {
        headers: Headers;
    };

export const getTerminalPaymentInstrumentEndpointsCreateTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsPostUrl =
    () => {
        return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/terminal-payment-instruments`;
    };

export const terminalPaymentInstrumentEndpointsCreateTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsPost =
    async (
        terminalPaymentInstrumentCreate: TerminalPaymentInstrumentCreate,
        options?: RequestInit
    ): Promise<terminalPaymentInstrumentEndpointsCreateTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsPostResponse> => {
        return authFetch<terminalPaymentInstrumentEndpointsCreateTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsPostResponse>(
            getTerminalPaymentInstrumentEndpointsCreateTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsPostUrl(),
            {
                ...options,
                method: "POST",
                headers: { "Content-Type": "application/json", ...options?.headers },
                body: JSON.stringify(terminalPaymentInstrumentCreate)
            }
        );
    };

/**
 * Returns the details of a specific terminal payment instrument.
 * @summary Get a single terminal payment instrument by ID
 */
export type terminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdGetResponse200 =
    {
        data: ApiResponseTerminalPaymentInstrument;
        status: 200;
    };

export type terminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdGetResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type terminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdGetResponseComposite =

        | terminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdGetResponse200
        | terminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdGetResponse422;

export type terminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdGetResponse =
    terminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdGetResponseComposite & {
        headers: Headers;
    };

export const getTerminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdGetUrl =
    (terminalPaymentInstrumentId: string) => {
        return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/terminal-payment-instruments/${terminalPaymentInstrumentId}`;
    };

export const terminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdGet =
    async (
        terminalPaymentInstrumentId: string,
        options?: RequestInit
    ): Promise<terminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdGetResponse> => {
        return authFetch<terminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdGetResponse>(
            getTerminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdGetUrl(
                terminalPaymentInstrumentId
            ),
            {
                ...options,
                method: "GET"
            }
        );
    };

/**
 * Partially updates an existing terminal payment instrument.
 * @summary Partially update a terminal payment instrument
 */
export type terminalPaymentInstrumentEndpointsPatchTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdPatchResponse200 =
    {
        data: ApiResponseTerminalPaymentInstrument;
        status: 200;
    };

export type terminalPaymentInstrumentEndpointsPatchTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdPatchResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type terminalPaymentInstrumentEndpointsPatchTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdPatchResponseComposite =

        | terminalPaymentInstrumentEndpointsPatchTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdPatchResponse200
        | terminalPaymentInstrumentEndpointsPatchTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdPatchResponse422;

export type terminalPaymentInstrumentEndpointsPatchTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdPatchResponse =
    terminalPaymentInstrumentEndpointsPatchTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdPatchResponseComposite & {
        headers: Headers;
    };

export const getTerminalPaymentInstrumentEndpointsPatchTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdPatchUrl =
    (terminalPaymentInstrumentId: string) => {
        return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/terminal-payment-instruments/${terminalPaymentInstrumentId}`;
    };

export const terminalPaymentInstrumentEndpointsPatchTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdPatch =
    async (
        terminalPaymentInstrumentId: string,
        terminalPaymentInstrumentUpdate: TerminalPaymentInstrumentUpdate,
        options?: RequestInit
    ): Promise<terminalPaymentInstrumentEndpointsPatchTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdPatchResponse> => {
        return authFetch<terminalPaymentInstrumentEndpointsPatchTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdPatchResponse>(
            getTerminalPaymentInstrumentEndpointsPatchTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdPatchUrl(
                terminalPaymentInstrumentId
            ),
            {
                ...options,
                method: "PATCH",
                headers: { "Content-Type": "application/json", ...options?.headers },
                body: JSON.stringify(terminalPaymentInstrumentUpdate)
            }
        );
    };

/**
 * Deletes a terminal payment instrument by ID.
 * @summary Delete a terminal payment instrument
 */
export type terminalPaymentInstrumentEndpointsDeleteTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdDeleteResponse200 =
    {
        data: ApiResponseNoneType;
        status: 200;
    };

export type terminalPaymentInstrumentEndpointsDeleteTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdDeleteResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type terminalPaymentInstrumentEndpointsDeleteTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdDeleteResponseComposite =

        | terminalPaymentInstrumentEndpointsDeleteTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdDeleteResponse200
        | terminalPaymentInstrumentEndpointsDeleteTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdDeleteResponse422;

export type terminalPaymentInstrumentEndpointsDeleteTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdDeleteResponse =
    terminalPaymentInstrumentEndpointsDeleteTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdDeleteResponseComposite & {
        headers: Headers;
    };

export const getTerminalPaymentInstrumentEndpointsDeleteTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdDeleteUrl =
    (terminalPaymentInstrumentId: string) => {
        return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/terminal-payment-instruments/${terminalPaymentInstrumentId}`;
    };

export const terminalPaymentInstrumentEndpointsDeleteTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdDelete =
    async (
        terminalPaymentInstrumentId: string,
        options?: RequestInit
    ): Promise<terminalPaymentInstrumentEndpointsDeleteTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdDeleteResponse> => {
        return authFetch<terminalPaymentInstrumentEndpointsDeleteTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdDeleteResponse>(
            getTerminalPaymentInstrumentEndpointsDeleteTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdDeleteUrl(
                terminalPaymentInstrumentId
            ),
            {
                ...options,
                method: "DELETE"
            }
        );
    };
