/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * BlowFish - Enigma API Service
 * OpenAPI spec version: local
 */
import type {
    ApiResponseImportResponse,
    ApiResponseNoneType,
    ApiResponseOffsetPaginationTerminalPaymentInstrument,
    ApiResponseTerminalPaymentInstrument,
    BodyTerminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsImportPost,
    BodyTerminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsMultiCsvEnigmaV1TerminalPaymentInstrumentsImportMultiCsvPost,
    HTTPValidationError,
    TerminalInitializePaymentInstrumentsRequest,
    TerminalPaymentInstrumentCreate,
    TerminalPaymentInstrumentEndpointsExportTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsExportTerminalIdGetParams,
    TerminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentsByTerminalEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdGetParams,
    TerminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsImportPostParams,
    TerminalPaymentInstrumentEndpointsListProviderPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsProvidersProviderNameGetParams,
    TerminalPaymentInstrumentEndpointsListTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsGetParams,
    TerminalPaymentInstrumentFIData,
    TerminalPaymentInstrumentUpdate
} from "../blowFishEnigmaAPIService.schemas";

import { authFetch } from "../../../helpers/orvalAuthFetchMiddleware";

/**
 * Returns a paginated list of terminal payment instruments with optional filtering.
 * @summary Get a paginated list of terminal payment instruments
 */
export type terminalPaymentInstrumentEndpointsListTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsGetResponse200 =
    {
        data: ApiResponseOffsetPaginationTerminalPaymentInstrument;
        status: 200;
    };

export type terminalPaymentInstrumentEndpointsListTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsGetResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type terminalPaymentInstrumentEndpointsListTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsGetResponseComposite =

        | terminalPaymentInstrumentEndpointsListTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsGetResponse200
        | terminalPaymentInstrumentEndpointsListTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsGetResponse422;

export type terminalPaymentInstrumentEndpointsListTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsGetResponse =
    terminalPaymentInstrumentEndpointsListTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsGetResponseComposite & {
        headers: Headers;
    };

export const getTerminalPaymentInstrumentEndpointsListTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsGetUrl =
    (
        params?: TerminalPaymentInstrumentEndpointsListTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsGetParams
    ) => {
        const normalizedParams = new URLSearchParams();

        Object.entries(params || {}).forEach(([key, value]) => {
            if (value !== undefined) {
                normalizedParams.append(key, value === null ? "null" : value.toString());
            }
        });

        const stringifiedParams = normalizedParams.toString();

        return stringifiedParams.length > 0
            ? `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/terminal_payment_instruments?${stringifiedParams}`
            : `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/terminal_payment_instruments`;
    };

export const terminalPaymentInstrumentEndpointsListTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsGet =
    async (
        params?: TerminalPaymentInstrumentEndpointsListTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsGetParams,
        options?: RequestInit
    ): Promise<terminalPaymentInstrumentEndpointsListTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsGetResponse> => {
        return authFetch<terminalPaymentInstrumentEndpointsListTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsGetResponse>(
            getTerminalPaymentInstrumentEndpointsListTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsGetUrl(
                params
            ),
            {
                ...options,
                method: "GET"
            }
        );
    };

/**
 * Registers a new terminal payment instrument.
 * @summary Create a new terminal payment instrument
 */
export type terminalPaymentInstrumentEndpointsCreateTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsPostResponse200 =
    {
        data: ApiResponseTerminalPaymentInstrument;
        status: 200;
    };

export type terminalPaymentInstrumentEndpointsCreateTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsPostResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type terminalPaymentInstrumentEndpointsCreateTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsPostResponseComposite =

        | terminalPaymentInstrumentEndpointsCreateTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsPostResponse200
        | terminalPaymentInstrumentEndpointsCreateTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsPostResponse422;

export type terminalPaymentInstrumentEndpointsCreateTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsPostResponse =
    terminalPaymentInstrumentEndpointsCreateTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsPostResponseComposite & {
        headers: Headers;
    };

export const getTerminalPaymentInstrumentEndpointsCreateTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsPostUrl =
    () => {
        return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/terminal_payment_instruments`;
    };

export const terminalPaymentInstrumentEndpointsCreateTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsPost =
    async (
        terminalPaymentInstrumentCreate: TerminalPaymentInstrumentCreate,
        options?: RequestInit
    ): Promise<terminalPaymentInstrumentEndpointsCreateTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsPostResponse> => {
        return authFetch<terminalPaymentInstrumentEndpointsCreateTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsPostResponse>(
            getTerminalPaymentInstrumentEndpointsCreateTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsPostUrl(),
            {
                ...options,
                method: "POST",
                headers: { "Content-Type": "application/json", ...options?.headers },
                body: JSON.stringify(terminalPaymentInstrumentCreate)
            }
        );
    };

/**
 * Returns a list of terminal payment instruments associated with all terminals belonging to a given provider name.
 * @summary Get payment instruments for all terminals within a specific provider
 */
export type terminalPaymentInstrumentEndpointsListProviderPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsProvidersProviderNameGetResponse200 =
    {
        data: ApiResponseOffsetPaginationTerminalPaymentInstrument;
        status: 200;
    };

export type terminalPaymentInstrumentEndpointsListProviderPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsProvidersProviderNameGetResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type terminalPaymentInstrumentEndpointsListProviderPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsProvidersProviderNameGetResponseComposite =

        | terminalPaymentInstrumentEndpointsListProviderPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsProvidersProviderNameGetResponse200
        | terminalPaymentInstrumentEndpointsListProviderPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsProvidersProviderNameGetResponse422;

export type terminalPaymentInstrumentEndpointsListProviderPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsProvidersProviderNameGetResponse =
    terminalPaymentInstrumentEndpointsListProviderPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsProvidersProviderNameGetResponseComposite & {
        headers: Headers;
    };

export const getTerminalPaymentInstrumentEndpointsListProviderPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsProvidersProviderNameGetUrl =
    (
        providerName: string,
        params?: TerminalPaymentInstrumentEndpointsListProviderPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsProvidersProviderNameGetParams
    ) => {
        const normalizedParams = new URLSearchParams();

        Object.entries(params || {}).forEach(([key, value]) => {
            if (value !== undefined) {
                normalizedParams.append(key, value === null ? "null" : value.toString());
            }
        });

        const stringifiedParams = normalizedParams.toString();

        return stringifiedParams.length > 0
            ? `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/terminal_payment_instruments/providers/${providerName}?${stringifiedParams}`
            : `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/terminal_payment_instruments/providers/${providerName}`;
    };

export const terminalPaymentInstrumentEndpointsListProviderPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsProvidersProviderNameGet =
    async (
        providerName: string,
        params?: TerminalPaymentInstrumentEndpointsListProviderPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsProvidersProviderNameGetParams,
        options?: RequestInit
    ): Promise<terminalPaymentInstrumentEndpointsListProviderPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsProvidersProviderNameGetResponse> => {
        return authFetch<terminalPaymentInstrumentEndpointsListProviderPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsProvidersProviderNameGetResponse>(
            getTerminalPaymentInstrumentEndpointsListProviderPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsProvidersProviderNameGetUrl(
                providerName,
                params
            ),
            {
                ...options,
                method: "GET"
            }
        );
    };

/**
 * Returns a list of terminal payment instruments associated with a given terminal ID.
 * @summary Get terminal payment instruments for a specific terminal
 */
export type terminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentsByTerminalEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdGetResponse200 =
    {
        data: ApiResponseOffsetPaginationTerminalPaymentInstrument;
        status: 200;
    };

export type terminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentsByTerminalEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdGetResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type terminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentsByTerminalEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdGetResponseComposite =

        | terminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentsByTerminalEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdGetResponse200
        | terminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentsByTerminalEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdGetResponse422;

export type terminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentsByTerminalEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdGetResponse =
    terminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentsByTerminalEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdGetResponseComposite & {
        headers: Headers;
    };

export const getTerminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentsByTerminalEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdGetUrl =
    (
        terminalId: string,
        params?: TerminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentsByTerminalEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdGetParams
    ) => {
        const normalizedParams = new URLSearchParams();

        Object.entries(params || {}).forEach(([key, value]) => {
            if (value !== undefined) {
                normalizedParams.append(key, value === null ? "null" : value.toString());
            }
        });

        const stringifiedParams = normalizedParams.toString();

        return stringifiedParams.length > 0
            ? `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/terminal_payment_instruments/terminals/${terminalId}?${stringifiedParams}`
            : `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/terminal_payment_instruments/terminals/${terminalId}`;
    };

export const terminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentsByTerminalEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdGet =
    async (
        terminalId: string,
        params?: TerminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentsByTerminalEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdGetParams,
        options?: RequestInit
    ): Promise<terminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentsByTerminalEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdGetResponse> => {
        return authFetch<terminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentsByTerminalEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdGetResponse>(
            getTerminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentsByTerminalEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdGetUrl(
                terminalId,
                params
            ),
            {
                ...options,
                method: "GET"
            }
        );
    };

/**
 * Creates TerminalPaymentInstrument records for a given terminal by finding all SystemPaymentInstruments with the specified payment_type_code that the terminal supports.
 * @summary Initialize terminal payment instruments for a terminal based on a payment type
 */
export type terminalPaymentInstrumentEndpointsInitializeTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdInitializePostResponse200 =
    {
        data: ApiResponseOffsetPaginationTerminalPaymentInstrument;
        status: 200;
    };

export type terminalPaymentInstrumentEndpointsInitializeTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdInitializePostResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type terminalPaymentInstrumentEndpointsInitializeTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdInitializePostResponseComposite =

        | terminalPaymentInstrumentEndpointsInitializeTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdInitializePostResponse200
        | terminalPaymentInstrumentEndpointsInitializeTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdInitializePostResponse422;

export type terminalPaymentInstrumentEndpointsInitializeTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdInitializePostResponse =
    terminalPaymentInstrumentEndpointsInitializeTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdInitializePostResponseComposite & {
        headers: Headers;
    };

export const getTerminalPaymentInstrumentEndpointsInitializeTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdInitializePostUrl =
    (terminalId: string) => {
        return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/terminal_payment_instruments/terminals/${terminalId}/initialize`;
    };

export const terminalPaymentInstrumentEndpointsInitializeTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdInitializePost =
    async (
        terminalId: string,
        terminalInitializePaymentInstrumentsRequest: TerminalInitializePaymentInstrumentsRequest,
        options?: RequestInit
    ): Promise<terminalPaymentInstrumentEndpointsInitializeTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdInitializePostResponse> => {
        return authFetch<terminalPaymentInstrumentEndpointsInitializeTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdInitializePostResponse>(
            getTerminalPaymentInstrumentEndpointsInitializeTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdInitializePostUrl(
                terminalId
            ),
            {
                ...options,
                method: "POST",
                headers: { "Content-Type": "application/json", ...options?.headers },
                body: JSON.stringify(terminalInitializePaymentInstrumentsRequest)
            }
        );
    };

/**
 * Adds terminal payment instruments for a specific terminal based on a financial institution code.
 * @summary Add terminal payment instruments by financial institution
 */
export type terminalPaymentInstrumentEndpointsAddTerminalPaymentInstrumentsByFiEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdFinancialInstitutionFinancialInstitutionCodePostResponse200 =
    {
        data: ApiResponseOffsetPaginationTerminalPaymentInstrument;
        status: 200;
    };

export type terminalPaymentInstrumentEndpointsAddTerminalPaymentInstrumentsByFiEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdFinancialInstitutionFinancialInstitutionCodePostResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type terminalPaymentInstrumentEndpointsAddTerminalPaymentInstrumentsByFiEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdFinancialInstitutionFinancialInstitutionCodePostResponseComposite =

        | terminalPaymentInstrumentEndpointsAddTerminalPaymentInstrumentsByFiEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdFinancialInstitutionFinancialInstitutionCodePostResponse200
        | terminalPaymentInstrumentEndpointsAddTerminalPaymentInstrumentsByFiEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdFinancialInstitutionFinancialInstitutionCodePostResponse422;

export type terminalPaymentInstrumentEndpointsAddTerminalPaymentInstrumentsByFiEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdFinancialInstitutionFinancialInstitutionCodePostResponse =
    terminalPaymentInstrumentEndpointsAddTerminalPaymentInstrumentsByFiEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdFinancialInstitutionFinancialInstitutionCodePostResponseComposite & {
        headers: Headers;
    };

export const getTerminalPaymentInstrumentEndpointsAddTerminalPaymentInstrumentsByFiEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdFinancialInstitutionFinancialInstitutionCodePostUrl =
    (terminalId: string, financialInstitutionCode: string) => {
        return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/terminal_payment_instruments/terminals/${terminalId}/financial_institution/${financialInstitutionCode}`;
    };

export const terminalPaymentInstrumentEndpointsAddTerminalPaymentInstrumentsByFiEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdFinancialInstitutionFinancialInstitutionCodePost =
    async (
        terminalId: string,
        financialInstitutionCode: string,
        terminalPaymentInstrumentFIData: TerminalPaymentInstrumentFIData,
        options?: RequestInit
    ): Promise<terminalPaymentInstrumentEndpointsAddTerminalPaymentInstrumentsByFiEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdFinancialInstitutionFinancialInstitutionCodePostResponse> => {
        return authFetch<terminalPaymentInstrumentEndpointsAddTerminalPaymentInstrumentsByFiEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdFinancialInstitutionFinancialInstitutionCodePostResponse>(
            getTerminalPaymentInstrumentEndpointsAddTerminalPaymentInstrumentsByFiEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdFinancialInstitutionFinancialInstitutionCodePostUrl(
                terminalId,
                financialInstitutionCode
            ),
            {
                ...options,
                method: "POST",
                headers: { "Content-Type": "application/json", ...options?.headers },
                body: JSON.stringify(terminalPaymentInstrumentFIData)
            }
        );
    };

/**
 * Updates terminal payment instruments for a specific terminal based on financial institution code
 * @summary Update terminal payment instruments by financial institution
 */
export type terminalPaymentInstrumentEndpointsUpdateTerminalPaymentInstrumentsByFiEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdFinancialInstitutionFinancialInstitutionCodePatchResponse200 =
    {
        data: ApiResponseOffsetPaginationTerminalPaymentInstrument;
        status: 200;
    };

export type terminalPaymentInstrumentEndpointsUpdateTerminalPaymentInstrumentsByFiEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdFinancialInstitutionFinancialInstitutionCodePatchResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type terminalPaymentInstrumentEndpointsUpdateTerminalPaymentInstrumentsByFiEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdFinancialInstitutionFinancialInstitutionCodePatchResponseComposite =

        | terminalPaymentInstrumentEndpointsUpdateTerminalPaymentInstrumentsByFiEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdFinancialInstitutionFinancialInstitutionCodePatchResponse200
        | terminalPaymentInstrumentEndpointsUpdateTerminalPaymentInstrumentsByFiEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdFinancialInstitutionFinancialInstitutionCodePatchResponse422;

export type terminalPaymentInstrumentEndpointsUpdateTerminalPaymentInstrumentsByFiEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdFinancialInstitutionFinancialInstitutionCodePatchResponse =
    terminalPaymentInstrumentEndpointsUpdateTerminalPaymentInstrumentsByFiEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdFinancialInstitutionFinancialInstitutionCodePatchResponseComposite & {
        headers: Headers;
    };

export const getTerminalPaymentInstrumentEndpointsUpdateTerminalPaymentInstrumentsByFiEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdFinancialInstitutionFinancialInstitutionCodePatchUrl =
    (terminalId: string, financialInstitutionCode: string) => {
        return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/terminal_payment_instruments/terminals/${terminalId}/financial_institution/${financialInstitutionCode}`;
    };

export const terminalPaymentInstrumentEndpointsUpdateTerminalPaymentInstrumentsByFiEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdFinancialInstitutionFinancialInstitutionCodePatch =
    async (
        terminalId: string,
        financialInstitutionCode: string,
        terminalPaymentInstrumentFIData: TerminalPaymentInstrumentFIData,
        options?: RequestInit
    ): Promise<terminalPaymentInstrumentEndpointsUpdateTerminalPaymentInstrumentsByFiEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdFinancialInstitutionFinancialInstitutionCodePatchResponse> => {
        return authFetch<terminalPaymentInstrumentEndpointsUpdateTerminalPaymentInstrumentsByFiEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdFinancialInstitutionFinancialInstitutionCodePatchResponse>(
            getTerminalPaymentInstrumentEndpointsUpdateTerminalPaymentInstrumentsByFiEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdFinancialInstitutionFinancialInstitutionCodePatchUrl(
                terminalId,
                financialInstitutionCode
            ),
            {
                ...options,
                method: "PATCH",
                headers: { "Content-Type": "application/json", ...options?.headers },
                body: JSON.stringify(terminalPaymentInstrumentFIData)
            }
        );
    };

/**
 * Deletes terminal payment instruments for a specific terminal based on financial institution code
 * @summary Delete terminal payment instruments by financial institution
 */
export type terminalPaymentInstrumentEndpointsDeleteTerminalPaymentInstrumentsByFiEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdFinancialInstitutionFinancialInstitutionCodeDeleteResponse200 =
    {
        data: ApiResponseNoneType;
        status: 200;
    };

export type terminalPaymentInstrumentEndpointsDeleteTerminalPaymentInstrumentsByFiEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdFinancialInstitutionFinancialInstitutionCodeDeleteResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type terminalPaymentInstrumentEndpointsDeleteTerminalPaymentInstrumentsByFiEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdFinancialInstitutionFinancialInstitutionCodeDeleteResponseComposite =

        | terminalPaymentInstrumentEndpointsDeleteTerminalPaymentInstrumentsByFiEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdFinancialInstitutionFinancialInstitutionCodeDeleteResponse200
        | terminalPaymentInstrumentEndpointsDeleteTerminalPaymentInstrumentsByFiEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdFinancialInstitutionFinancialInstitutionCodeDeleteResponse422;

export type terminalPaymentInstrumentEndpointsDeleteTerminalPaymentInstrumentsByFiEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdFinancialInstitutionFinancialInstitutionCodeDeleteResponse =
    terminalPaymentInstrumentEndpointsDeleteTerminalPaymentInstrumentsByFiEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdFinancialInstitutionFinancialInstitutionCodeDeleteResponseComposite & {
        headers: Headers;
    };

export const getTerminalPaymentInstrumentEndpointsDeleteTerminalPaymentInstrumentsByFiEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdFinancialInstitutionFinancialInstitutionCodeDeleteUrl =
    (terminalId: string, financialInstitutionCode: string) => {
        return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/terminal_payment_instruments/terminals/${terminalId}/financial_institution/${financialInstitutionCode}`;
    };

export const terminalPaymentInstrumentEndpointsDeleteTerminalPaymentInstrumentsByFiEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdFinancialInstitutionFinancialInstitutionCodeDelete =
    async (
        terminalId: string,
        financialInstitutionCode: string,
        options?: RequestInit
    ): Promise<terminalPaymentInstrumentEndpointsDeleteTerminalPaymentInstrumentsByFiEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdFinancialInstitutionFinancialInstitutionCodeDeleteResponse> => {
        return authFetch<terminalPaymentInstrumentEndpointsDeleteTerminalPaymentInstrumentsByFiEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdFinancialInstitutionFinancialInstitutionCodeDeleteResponse>(
            getTerminalPaymentInstrumentEndpointsDeleteTerminalPaymentInstrumentsByFiEnigmaV1TerminalPaymentInstrumentsTerminalsTerminalIdFinancialInstitutionFinancialInstitutionCodeDeleteUrl(
                terminalId,
                financialInstitutionCode
            ),
            {
                ...options,
                method: "DELETE"
            }
        );
    };

/**
 * Returns the details of a specific terminal payment instrument.
 * @summary Get a single terminal payment instrument by ID
 */
export type terminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdGetResponse200 =
    {
        data: ApiResponseTerminalPaymentInstrument;
        status: 200;
    };

export type terminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdGetResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type terminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdGetResponseComposite =

        | terminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdGetResponse200
        | terminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdGetResponse422;

export type terminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdGetResponse =
    terminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdGetResponseComposite & {
        headers: Headers;
    };

export const getTerminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdGetUrl =
    (terminalPaymentInstrumentId: string) => {
        return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/terminal_payment_instruments/${terminalPaymentInstrumentId}`;
    };

export const terminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdGet =
    async (
        terminalPaymentInstrumentId: string,
        options?: RequestInit
    ): Promise<terminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdGetResponse> => {
        return authFetch<terminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdGetResponse>(
            getTerminalPaymentInstrumentEndpointsGetTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdGetUrl(
                terminalPaymentInstrumentId
            ),
            {
                ...options,
                method: "GET"
            }
        );
    };

/**
 * Partially updates an existing terminal payment instrument.
 * @summary Partially update a terminal payment instrument
 */
export type terminalPaymentInstrumentEndpointsPatchTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdPatchResponse200 =
    {
        data: ApiResponseTerminalPaymentInstrument;
        status: 200;
    };

export type terminalPaymentInstrumentEndpointsPatchTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdPatchResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type terminalPaymentInstrumentEndpointsPatchTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdPatchResponseComposite =

        | terminalPaymentInstrumentEndpointsPatchTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdPatchResponse200
        | terminalPaymentInstrumentEndpointsPatchTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdPatchResponse422;

export type terminalPaymentInstrumentEndpointsPatchTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdPatchResponse =
    terminalPaymentInstrumentEndpointsPatchTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdPatchResponseComposite & {
        headers: Headers;
    };

export const getTerminalPaymentInstrumentEndpointsPatchTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdPatchUrl =
    (terminalPaymentInstrumentId: string) => {
        return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/terminal_payment_instruments/${terminalPaymentInstrumentId}`;
    };

export const terminalPaymentInstrumentEndpointsPatchTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdPatch =
    async (
        terminalPaymentInstrumentId: string,
        terminalPaymentInstrumentUpdate: TerminalPaymentInstrumentUpdate,
        options?: RequestInit
    ): Promise<terminalPaymentInstrumentEndpointsPatchTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdPatchResponse> => {
        return authFetch<terminalPaymentInstrumentEndpointsPatchTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdPatchResponse>(
            getTerminalPaymentInstrumentEndpointsPatchTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdPatchUrl(
                terminalPaymentInstrumentId
            ),
            {
                ...options,
                method: "PATCH",
                headers: { "Content-Type": "application/json", ...options?.headers },
                body: JSON.stringify(terminalPaymentInstrumentUpdate)
            }
        );
    };

/**
 * Deletes a terminal payment instrument by ID.
 * @summary Delete a terminal payment instrument
 */
export type terminalPaymentInstrumentEndpointsDeleteTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdDeleteResponse200 =
    {
        data: ApiResponseNoneType;
        status: 200;
    };

export type terminalPaymentInstrumentEndpointsDeleteTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdDeleteResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type terminalPaymentInstrumentEndpointsDeleteTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdDeleteResponseComposite =

        | terminalPaymentInstrumentEndpointsDeleteTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdDeleteResponse200
        | terminalPaymentInstrumentEndpointsDeleteTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdDeleteResponse422;

export type terminalPaymentInstrumentEndpointsDeleteTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdDeleteResponse =
    terminalPaymentInstrumentEndpointsDeleteTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdDeleteResponseComposite & {
        headers: Headers;
    };

export const getTerminalPaymentInstrumentEndpointsDeleteTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdDeleteUrl =
    (terminalPaymentInstrumentId: string) => {
        return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/terminal_payment_instruments/${terminalPaymentInstrumentId}`;
    };

export const terminalPaymentInstrumentEndpointsDeleteTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdDelete =
    async (
        terminalPaymentInstrumentId: string,
        options?: RequestInit
    ): Promise<terminalPaymentInstrumentEndpointsDeleteTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdDeleteResponse> => {
        return authFetch<terminalPaymentInstrumentEndpointsDeleteTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdDeleteResponse>(
            getTerminalPaymentInstrumentEndpointsDeleteTerminalPaymentInstrumentEnigmaV1TerminalPaymentInstrumentsTerminalPaymentInstrumentIdDeleteUrl(
                terminalPaymentInstrumentId
            ),
            {
                ...options,
                method: "DELETE"
            }
        );
    };

/**
 * Export TPI configurations for a specific terminal without terminal_id for later import to selected terminals
 * @summary Export terminal payment instruments to CSV
 */
export type terminalPaymentInstrumentEndpointsExportTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsExportTerminalIdGetResponse200 =
    {
        data: unknown;
        status: 200;
    };

export type terminalPaymentInstrumentEndpointsExportTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsExportTerminalIdGetResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type terminalPaymentInstrumentEndpointsExportTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsExportTerminalIdGetResponseComposite =

        | terminalPaymentInstrumentEndpointsExportTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsExportTerminalIdGetResponse200
        | terminalPaymentInstrumentEndpointsExportTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsExportTerminalIdGetResponse422;

export type terminalPaymentInstrumentEndpointsExportTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsExportTerminalIdGetResponse =
    terminalPaymentInstrumentEndpointsExportTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsExportTerminalIdGetResponseComposite & {
        headers: Headers;
    };

export const getTerminalPaymentInstrumentEndpointsExportTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsExportTerminalIdGetUrl =
    (
        terminalId: string,
        params?: TerminalPaymentInstrumentEndpointsExportTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsExportTerminalIdGetParams
    ) => {
        const normalizedParams = new URLSearchParams();

        Object.entries(params || {}).forEach(([key, value]) => {
            if (value !== undefined) {
                normalizedParams.append(key, value === null ? "null" : value.toString());
            }
        });

        const stringifiedParams = normalizedParams.toString();

        return stringifiedParams.length > 0
            ? `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/terminal_payment_instruments/export/${terminalId}?${stringifiedParams}`
            : `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/terminal_payment_instruments/export/${terminalId}`;
    };

export const terminalPaymentInstrumentEndpointsExportTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsExportTerminalIdGet =
    async (
        terminalId: string,
        params?: TerminalPaymentInstrumentEndpointsExportTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsExportTerminalIdGetParams,
        options?: RequestInit
    ): Promise<terminalPaymentInstrumentEndpointsExportTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsExportTerminalIdGetResponse> => {
        return authFetch<terminalPaymentInstrumentEndpointsExportTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsExportTerminalIdGetResponse>(
            getTerminalPaymentInstrumentEndpointsExportTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsExportTerminalIdGetUrl(
                terminalId,
                params
            ),
            {
                ...options,
                method: "GET"
            }
        );
    };

/**
 * Import TPI configurations from CSV file and apply to selected terminals. Skips entries where SPI doesn't exist and reports counts.
 * @summary Import terminal payment instruments from CSV
 */
export type terminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsImportPostResponse200 =
    {
        data: ApiResponseImportResponse;
        status: 200;
    };

export type terminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsImportPostResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type terminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsImportPostResponseComposite =

        | terminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsImportPostResponse200
        | terminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsImportPostResponse422;

export type terminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsImportPostResponse =
    terminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsImportPostResponseComposite & {
        headers: Headers;
    };

export const getTerminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsImportPostUrl =
    (
        params?: TerminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsImportPostParams
    ) => {
        const normalizedParams = new URLSearchParams();

        Object.entries(params || {}).forEach(([key, value]) => {
            if (value !== undefined) {
                normalizedParams.append(key, value === null ? "null" : value.toString());
            }
        });

        const stringifiedParams = normalizedParams.toString();

        return stringifiedParams.length > 0
            ? `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/terminal_payment_instruments/import?${stringifiedParams}`
            : `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/terminal_payment_instruments/import`;
    };

export const terminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsImportPost =
    async (
        bodyTerminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsImportPost: BodyTerminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsImportPost,
        params?: TerminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsImportPostParams,
        options?: RequestInit
    ): Promise<terminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsImportPostResponse> => {
        const formData = new FormData();
        formData.append(
            "data",
            bodyTerminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsImportPost.data
        );
        formData.append(
            "csv_file",
            bodyTerminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsImportPost.csv_file
        );

        return authFetch<terminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsImportPostResponse>(
            getTerminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsEnigmaV1TerminalPaymentInstrumentsImportPostUrl(
                params
            ),
            {
                ...options,
                method: "POST",
                body: formData
            }
        );
    };

/**
 * Import TPI configurations from three CSV files: Payment Types, Financial Institutions (optional), and Currency mappings (optional). Supports importing to specific terminals or all terminals of a provider.
 * @summary Import terminal payment instruments from multiple CSV files
 */
export type terminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsMultiCsvEnigmaV1TerminalPaymentInstrumentsImportMultiCsvPostResponse200 =
    {
        data: ApiResponseImportResponse;
        status: 200;
    };

export type terminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsMultiCsvEnigmaV1TerminalPaymentInstrumentsImportMultiCsvPostResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type terminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsMultiCsvEnigmaV1TerminalPaymentInstrumentsImportMultiCsvPostResponseComposite =

        | terminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsMultiCsvEnigmaV1TerminalPaymentInstrumentsImportMultiCsvPostResponse200
        | terminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsMultiCsvEnigmaV1TerminalPaymentInstrumentsImportMultiCsvPostResponse422;

export type terminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsMultiCsvEnigmaV1TerminalPaymentInstrumentsImportMultiCsvPostResponse =
    terminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsMultiCsvEnigmaV1TerminalPaymentInstrumentsImportMultiCsvPostResponseComposite & {
        headers: Headers;
    };

export const getTerminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsMultiCsvEnigmaV1TerminalPaymentInstrumentsImportMultiCsvPostUrl =
    () => {
        return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/terminal_payment_instruments/import/multi-csv`;
    };

export const terminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsMultiCsvEnigmaV1TerminalPaymentInstrumentsImportMultiCsvPost =
    async (
        bodyTerminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsMultiCsvEnigmaV1TerminalPaymentInstrumentsImportMultiCsvPost: BodyTerminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsMultiCsvEnigmaV1TerminalPaymentInstrumentsImportMultiCsvPost,
        options?: RequestInit
    ): Promise<terminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsMultiCsvEnigmaV1TerminalPaymentInstrumentsImportMultiCsvPostResponse> => {
        const formData = new FormData();
        formData.append(
            "payment_types_csv",
            bodyTerminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsMultiCsvEnigmaV1TerminalPaymentInstrumentsImportMultiCsvPost.payment_types_csv
        );
        formData.append(
            "data",
            bodyTerminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsMultiCsvEnigmaV1TerminalPaymentInstrumentsImportMultiCsvPost.data
        );
        if (
            bodyTerminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsMultiCsvEnigmaV1TerminalPaymentInstrumentsImportMultiCsvPost.financial_institutions_csv !==
                undefined &&
            bodyTerminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsMultiCsvEnigmaV1TerminalPaymentInstrumentsImportMultiCsvPost.financial_institutions_csv !==
                null
        ) {
            formData.append(
                "financial_institutions_csv",
                bodyTerminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsMultiCsvEnigmaV1TerminalPaymentInstrumentsImportMultiCsvPost.financial_institutions_csv
            );
        }
        if (
            bodyTerminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsMultiCsvEnigmaV1TerminalPaymentInstrumentsImportMultiCsvPost.currency_csv !==
                undefined &&
            bodyTerminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsMultiCsvEnigmaV1TerminalPaymentInstrumentsImportMultiCsvPost.currency_csv !==
                null
        ) {
            formData.append(
                "currency_csv",
                bodyTerminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsMultiCsvEnigmaV1TerminalPaymentInstrumentsImportMultiCsvPost.currency_csv
            );
        }

        return authFetch<terminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsMultiCsvEnigmaV1TerminalPaymentInstrumentsImportMultiCsvPostResponse>(
            getTerminalPaymentInstrumentEndpointsImportTerminalPaymentInstrumentsMultiCsvEnigmaV1TerminalPaymentInstrumentsImportMultiCsvPostUrl(),
            {
                ...options,
                method: "POST",
                body: formData
            }
        );
    };
