/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * BlowFish - Enigma API Service
 * OpenAPI spec version: local
 */
import type {
    ApiResponseCascadeRead,
    ApiResponseDictStrStr,
    ApiResponseOffsetPaginationCascadeRead,
    CascadeCreate,
    CascadeEndpointsListCascadesByCurrencyEnigmaV1CascadeCurrencyCurrencyCodeGetParams,
    CascadeEndpointsListCascadesByTypeEnigmaV1CascadeTypeCascadeTypeGetParams,
    CascadeEndpointsListCascadesEnigmaV1CascadeGetParams,
    CascadeUpdate,
    HTTPValidationError
} from "../blowFishEnigmaAPIService.schemas";

import { authFetch } from "../../../helpers/orvalAuthFetchMiddleware";

/**
 * Returns a paginated list of cascades with filtering and pagination
 * @summary Get a paginated list of cascades
 */
export type cascadeEndpointsListCascadesEnigmaV1CascadeGetResponse200 = {
    data: ApiResponseOffsetPaginationCascadeRead;
    status: 200;
};

export type cascadeEndpointsListCascadesEnigmaV1CascadeGetResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type cascadeEndpointsListCascadesEnigmaV1CascadeGetResponseComposite =
    | cascadeEndpointsListCascadesEnigmaV1CascadeGetResponse200
    | cascadeEndpointsListCascadesEnigmaV1CascadeGetResponse422;

export type cascadeEndpointsListCascadesEnigmaV1CascadeGetResponse =
    cascadeEndpointsListCascadesEnigmaV1CascadeGetResponseComposite & {
        headers: Headers;
    };

export const getCascadeEndpointsListCascadesEnigmaV1CascadeGetUrl = (
    params: CascadeEndpointsListCascadesEnigmaV1CascadeGetParams
) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? "null" : value.toString());
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/cascade?${stringifiedParams}`
        : `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/cascade`;
};

export const cascadeEndpointsListCascadesEnigmaV1CascadeGet = async (
    params: CascadeEndpointsListCascadesEnigmaV1CascadeGetParams,
    options?: RequestInit
): Promise<cascadeEndpointsListCascadesEnigmaV1CascadeGetResponse> => {
    return authFetch<cascadeEndpointsListCascadesEnigmaV1CascadeGetResponse>(
        getCascadeEndpointsListCascadesEnigmaV1CascadeGetUrl(params),
        {
            ...options,
            method: "GET"
        }
    );
};

/**
 * Creates a new cascade with the provided configuration
 * @summary Create a new cascade
 */
export type cascadeEndpointsCreateCascadeEnigmaV1CascadePostResponse200 = {
    data: ApiResponseCascadeRead;
    status: 200;
};

export type cascadeEndpointsCreateCascadeEnigmaV1CascadePostResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type cascadeEndpointsCreateCascadeEnigmaV1CascadePostResponseComposite =
    | cascadeEndpointsCreateCascadeEnigmaV1CascadePostResponse200
    | cascadeEndpointsCreateCascadeEnigmaV1CascadePostResponse422;

export type cascadeEndpointsCreateCascadeEnigmaV1CascadePostResponse =
    cascadeEndpointsCreateCascadeEnigmaV1CascadePostResponseComposite & {
        headers: Headers;
    };

export const getCascadeEndpointsCreateCascadeEnigmaV1CascadePostUrl = () => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/cascade`;
};

export const cascadeEndpointsCreateCascadeEnigmaV1CascadePost = async (
    cascadeCreate: CascadeCreate,
    options?: RequestInit
): Promise<cascadeEndpointsCreateCascadeEnigmaV1CascadePostResponse> => {
    return authFetch<cascadeEndpointsCreateCascadeEnigmaV1CascadePostResponse>(
        getCascadeEndpointsCreateCascadeEnigmaV1CascadePostUrl(),
        {
            ...options,
            method: "POST",
            headers: { "Content-Type": "application/json", ...options?.headers },
            body: JSON.stringify(cascadeCreate)
        }
    );
};

/**
 * Fetches details of a cascade by its ID
 * @summary Get cascade details
 */
export type cascadeEndpointsGetCascadeEnigmaV1CascadeCascadeIdGetResponse200 = {
    data: ApiResponseCascadeRead;
    status: 200;
};

export type cascadeEndpointsGetCascadeEnigmaV1CascadeCascadeIdGetResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type cascadeEndpointsGetCascadeEnigmaV1CascadeCascadeIdGetResponseComposite =
    | cascadeEndpointsGetCascadeEnigmaV1CascadeCascadeIdGetResponse200
    | cascadeEndpointsGetCascadeEnigmaV1CascadeCascadeIdGetResponse422;

export type cascadeEndpointsGetCascadeEnigmaV1CascadeCascadeIdGetResponse =
    cascadeEndpointsGetCascadeEnigmaV1CascadeCascadeIdGetResponseComposite & {
        headers: Headers;
    };

export const getCascadeEndpointsGetCascadeEnigmaV1CascadeCascadeIdGetUrl = (cascadeId: string) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/cascade/${cascadeId}`;
};

export const cascadeEndpointsGetCascadeEnigmaV1CascadeCascadeIdGet = async (
    cascadeId: string,
    options?: RequestInit
): Promise<cascadeEndpointsGetCascadeEnigmaV1CascadeCascadeIdGetResponse> => {
    return authFetch<cascadeEndpointsGetCascadeEnigmaV1CascadeCascadeIdGetResponse>(
        getCascadeEndpointsGetCascadeEnigmaV1CascadeCascadeIdGetUrl(cascadeId),
        {
            ...options,
            method: "GET"
        }
    );
};

/**
 * Updates an existing cascade with new configuration
 * @summary Update cascade
 */
export type cascadeEndpointsUpdateCascadeEnigmaV1CascadeCascadeIdPutResponse200 = {
    data: ApiResponseCascadeRead;
    status: 200;
};

export type cascadeEndpointsUpdateCascadeEnigmaV1CascadeCascadeIdPutResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type cascadeEndpointsUpdateCascadeEnigmaV1CascadeCascadeIdPutResponseComposite =
    | cascadeEndpointsUpdateCascadeEnigmaV1CascadeCascadeIdPutResponse200
    | cascadeEndpointsUpdateCascadeEnigmaV1CascadeCascadeIdPutResponse422;

export type cascadeEndpointsUpdateCascadeEnigmaV1CascadeCascadeIdPutResponse =
    cascadeEndpointsUpdateCascadeEnigmaV1CascadeCascadeIdPutResponseComposite & {
        headers: Headers;
    };

export const getCascadeEndpointsUpdateCascadeEnigmaV1CascadeCascadeIdPutUrl = (cascadeId: string) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/cascade/${cascadeId}`;
};

export const cascadeEndpointsUpdateCascadeEnigmaV1CascadeCascadeIdPut = async (
    cascadeId: string,
    cascadeUpdate: CascadeUpdate,
    options?: RequestInit
): Promise<cascadeEndpointsUpdateCascadeEnigmaV1CascadeCascadeIdPutResponse> => {
    return authFetch<cascadeEndpointsUpdateCascadeEnigmaV1CascadeCascadeIdPutResponse>(
        getCascadeEndpointsUpdateCascadeEnigmaV1CascadeCascadeIdPutUrl(cascadeId),
        {
            ...options,
            method: "PUT",
            headers: { "Content-Type": "application/json", ...options?.headers },
            body: JSON.stringify(cascadeUpdate)
        }
    );
};

/**
 * Deletes a cascade and all its associated data
 * @summary Delete cascade
 */
export type cascadeEndpointsDeleteCascadeEnigmaV1CascadeCascadeIdDeleteResponse200 = {
    data: ApiResponseDictStrStr;
    status: 200;
};

export type cascadeEndpointsDeleteCascadeEnigmaV1CascadeCascadeIdDeleteResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type cascadeEndpointsDeleteCascadeEnigmaV1CascadeCascadeIdDeleteResponseComposite =
    | cascadeEndpointsDeleteCascadeEnigmaV1CascadeCascadeIdDeleteResponse200
    | cascadeEndpointsDeleteCascadeEnigmaV1CascadeCascadeIdDeleteResponse422;

export type cascadeEndpointsDeleteCascadeEnigmaV1CascadeCascadeIdDeleteResponse =
    cascadeEndpointsDeleteCascadeEnigmaV1CascadeCascadeIdDeleteResponseComposite & {
        headers: Headers;
    };

export const getCascadeEndpointsDeleteCascadeEnigmaV1CascadeCascadeIdDeleteUrl = (cascadeId: string) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/cascade/${cascadeId}`;
};

export const cascadeEndpointsDeleteCascadeEnigmaV1CascadeCascadeIdDelete = async (
    cascadeId: string,
    options?: RequestInit
): Promise<cascadeEndpointsDeleteCascadeEnigmaV1CascadeCascadeIdDeleteResponse> => {
    return authFetch<cascadeEndpointsDeleteCascadeEnigmaV1CascadeCascadeIdDeleteResponse>(
        getCascadeEndpointsDeleteCascadeEnigmaV1CascadeCascadeIdDeleteUrl(cascadeId),
        {
            ...options,
            method: "DELETE"
        }
    );
};

/**
 * Returns cascades filtered by type (deposit/withdraw)
 * @summary Get cascades by type
 */
export type cascadeEndpointsListCascadesByTypeEnigmaV1CascadeTypeCascadeTypeGetResponse200 = {
    data: ApiResponseOffsetPaginationCascadeRead;
    status: 200;
};

export type cascadeEndpointsListCascadesByTypeEnigmaV1CascadeTypeCascadeTypeGetResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type cascadeEndpointsListCascadesByTypeEnigmaV1CascadeTypeCascadeTypeGetResponseComposite =
    | cascadeEndpointsListCascadesByTypeEnigmaV1CascadeTypeCascadeTypeGetResponse200
    | cascadeEndpointsListCascadesByTypeEnigmaV1CascadeTypeCascadeTypeGetResponse422;

export type cascadeEndpointsListCascadesByTypeEnigmaV1CascadeTypeCascadeTypeGetResponse =
    cascadeEndpointsListCascadesByTypeEnigmaV1CascadeTypeCascadeTypeGetResponseComposite & {
        headers: Headers;
    };

export const getCascadeEndpointsListCascadesByTypeEnigmaV1CascadeTypeCascadeTypeGetUrl = (
    cascadeType: string,
    params: CascadeEndpointsListCascadesByTypeEnigmaV1CascadeTypeCascadeTypeGetParams
) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? "null" : value.toString());
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/cascade/type/${cascadeType}?${stringifiedParams}`
        : `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/cascade/type/${cascadeType}`;
};

export const cascadeEndpointsListCascadesByTypeEnigmaV1CascadeTypeCascadeTypeGet = async (
    cascadeType: string,
    params: CascadeEndpointsListCascadesByTypeEnigmaV1CascadeTypeCascadeTypeGetParams,
    options?: RequestInit
): Promise<cascadeEndpointsListCascadesByTypeEnigmaV1CascadeTypeCascadeTypeGetResponse> => {
    return authFetch<cascadeEndpointsListCascadesByTypeEnigmaV1CascadeTypeCascadeTypeGetResponse>(
        getCascadeEndpointsListCascadesByTypeEnigmaV1CascadeTypeCascadeTypeGetUrl(cascadeType, params),
        {
            ...options,
            method: "GET"
        }
    );
};

/**
 * Returns cascades filtered by source currency code
 * @summary Get cascades by currency
 */
export type cascadeEndpointsListCascadesByCurrencyEnigmaV1CascadeCurrencyCurrencyCodeGetResponse200 = {
    data: ApiResponseOffsetPaginationCascadeRead;
    status: 200;
};

export type cascadeEndpointsListCascadesByCurrencyEnigmaV1CascadeCurrencyCurrencyCodeGetResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type cascadeEndpointsListCascadesByCurrencyEnigmaV1CascadeCurrencyCurrencyCodeGetResponseComposite =
    | cascadeEndpointsListCascadesByCurrencyEnigmaV1CascadeCurrencyCurrencyCodeGetResponse200
    | cascadeEndpointsListCascadesByCurrencyEnigmaV1CascadeCurrencyCurrencyCodeGetResponse422;

export type cascadeEndpointsListCascadesByCurrencyEnigmaV1CascadeCurrencyCurrencyCodeGetResponse =
    cascadeEndpointsListCascadesByCurrencyEnigmaV1CascadeCurrencyCurrencyCodeGetResponseComposite & {
        headers: Headers;
    };

export const getCascadeEndpointsListCascadesByCurrencyEnigmaV1CascadeCurrencyCurrencyCodeGetUrl = (
    currencyCode: string,
    params: CascadeEndpointsListCascadesByCurrencyEnigmaV1CascadeCurrencyCurrencyCodeGetParams
) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? "null" : value.toString());
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/cascade/currency/${currencyCode}?${stringifiedParams}`
        : `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/cascade/currency/${currencyCode}`;
};

export const cascadeEndpointsListCascadesByCurrencyEnigmaV1CascadeCurrencyCurrencyCodeGet = async (
    currencyCode: string,
    params: CascadeEndpointsListCascadesByCurrencyEnigmaV1CascadeCurrencyCurrencyCodeGetParams,
    options?: RequestInit
): Promise<cascadeEndpointsListCascadesByCurrencyEnigmaV1CascadeCurrencyCurrencyCodeGetResponse> => {
    return authFetch<cascadeEndpointsListCascadesByCurrencyEnigmaV1CascadeCurrencyCurrencyCodeGetResponse>(
        getCascadeEndpointsListCascadesByCurrencyEnigmaV1CascadeCurrencyCurrencyCodeGetUrl(currencyCode, params),
        {
            ...options,
            method: "GET"
        }
    );
};
