/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * BlowFish - CallBridge API Service
 * OpenAPI spec version: local
 */
/**
 * The error details if the request was not successful.
 */
export type ApiResponseCallbackHistoryRestoreResultError = ErrorBody | null;

/**
 * The meta details if the request. DEPRECATED
 * @deprecated
 */
export type ApiResponseCallbackHistoryRestoreResultMeta = unknown | null;

export interface ApiResponseCallbackHistoryRestoreResult {
    /** Indicates whether the request was successful. */
    success?: boolean;
    /** The actual response data if the request was successful. */
    data: CallbackHistoryRestoreResult;
    /** The error details if the request was not successful. */
    error?: ApiResponseCallbackHistoryRestoreResultError;
    /**
     * The meta details if the request. DEPRECATED
     * @deprecated
     */
    meta?: ApiResponseCallbackHistoryRestoreResultMeta;
}

/**
 * The error details if the request was not successful.
 */
export type ApiResponseCallbackMappingBulkResponseError = ErrorBody | null;

/**
 * The meta details if the request. DEPRECATED
 * @deprecated
 */
export type ApiResponseCallbackMappingBulkResponseMeta = unknown | null;

export interface ApiResponseCallbackMappingBulkResponse {
    /** Indicates whether the request was successful. */
    success?: boolean;
    /** The actual response data if the request was successful. */
    data: CallbackMappingBulkResponse;
    /** The error details if the request was not successful. */
    error?: ApiResponseCallbackMappingBulkResponseError;
    /**
     * The meta details if the request. DEPRECATED
     * @deprecated
     */
    meta?: ApiResponseCallbackMappingBulkResponseMeta;
}

/**
 * The error details if the request was not successful.
 */
export type ApiResponseCallbackMappingReadError = ErrorBody | null;

/**
 * The meta details if the request. DEPRECATED
 * @deprecated
 */
export type ApiResponseCallbackMappingReadMeta = unknown | null;

export interface ApiResponseCallbackMappingRead {
    /** Indicates whether the request was successful. */
    success?: boolean;
    /** The actual response data if the request was successful. */
    data: CallbackMappingRead;
    /** The error details if the request was not successful. */
    error?: ApiResponseCallbackMappingReadError;
    /**
     * The meta details if the request. DEPRECATED
     * @deprecated
     */
    meta?: ApiResponseCallbackMappingReadMeta;
}

/**
 * The error details if the request was not successful.
 */
export type ApiResponseCallbackRetryResponseError = ErrorBody | null;

/**
 * The meta details if the request. DEPRECATED
 * @deprecated
 */
export type ApiResponseCallbackRetryResponseMeta = unknown | null;

export interface ApiResponseCallbackRetryResponse {
    /** Indicates whether the request was successful. */
    success?: boolean;
    /** The actual response data if the request was successful. */
    data: CallbackRetryResponse;
    /** The error details if the request was not successful. */
    error?: ApiResponseCallbackRetryResponseError;
    /**
     * The meta details if the request. DEPRECATED
     * @deprecated
     */
    meta?: ApiResponseCallbackRetryResponseMeta;
}

/**
 * The error details if the request was not successful.
 */
export type ApiResponseDeliveryRequestMessageError = ErrorBody | null;

/**
 * The meta details if the request. DEPRECATED
 * @deprecated
 */
export type ApiResponseDeliveryRequestMessageMeta = unknown | null;

export interface ApiResponseDeliveryRequestMessage {
    /** Indicates whether the request was successful. */
    success?: boolean;
    /** The actual response data if the request was successful. */
    data: DeliveryRequestMessage;
    /** The error details if the request was not successful. */
    error?: ApiResponseDeliveryRequestMessageError;
    /**
     * The meta details if the request. DEPRECATED
     * @deprecated
     */
    meta?: ApiResponseDeliveryRequestMessageMeta;
}

/**
 * The error details if the request was not successful.
 */
export type ApiResponseNoneTypeError = ErrorBody | null;

/**
 * The meta details if the request. DEPRECATED
 * @deprecated
 */
export type ApiResponseNoneTypeMeta = unknown | null;

export interface ApiResponseNoneType {
    /** Indicates whether the request was successful. */
    success?: boolean;
    /** The actual response data if the request was successful. */
    data: null;
    /** The error details if the request was not successful. */
    error?: ApiResponseNoneTypeError;
    /**
     * The meta details if the request. DEPRECATED
     * @deprecated
     */
    meta?: ApiResponseNoneTypeMeta;
}

/**
 * The error details if the request was not successful.
 */
export type ApiResponseOffsetPaginationCallbackHistoryBackupError = ErrorBody | null;

/**
 * The meta details if the request. DEPRECATED
 * @deprecated
 */
export type ApiResponseOffsetPaginationCallbackHistoryBackupMeta = unknown | null;

export interface ApiResponseOffsetPaginationCallbackHistoryBackup {
    /** Indicates whether the request was successful. */
    success?: boolean;
    /** The actual response data if the request was successful. */
    data: OffsetPaginationCallbackHistoryBackup;
    /** The error details if the request was not successful. */
    error?: ApiResponseOffsetPaginationCallbackHistoryBackupError;
    /**
     * The meta details if the request. DEPRECATED
     * @deprecated
     */
    meta?: ApiResponseOffsetPaginationCallbackHistoryBackupMeta;
}

/**
 * The error details if the request was not successful.
 */
export type ApiResponseOffsetPaginationCallbackHistoryReadError = ErrorBody | null;

/**
 * The meta details if the request. DEPRECATED
 * @deprecated
 */
export type ApiResponseOffsetPaginationCallbackHistoryReadMeta = unknown | null;

export interface ApiResponseOffsetPaginationCallbackHistoryRead {
    /** Indicates whether the request was successful. */
    success?: boolean;
    /** The actual response data if the request was successful. */
    data: OffsetPaginationCallbackHistoryRead;
    /** The error details if the request was not successful. */
    error?: ApiResponseOffsetPaginationCallbackHistoryReadError;
    /**
     * The meta details if the request. DEPRECATED
     * @deprecated
     */
    meta?: ApiResponseOffsetPaginationCallbackHistoryReadMeta;
}

/**
 * The error details if the request was not successful.
 */
export type ApiResponseOffsetPaginationCallbackMappingReadError = ErrorBody | null;

/**
 * The meta details if the request. DEPRECATED
 * @deprecated
 */
export type ApiResponseOffsetPaginationCallbackMappingReadMeta = unknown | null;

export interface ApiResponseOffsetPaginationCallbackMappingRead {
    /** Indicates whether the request was successful. */
    success?: boolean;
    /** The actual response data if the request was successful. */
    data: OffsetPaginationCallbackMappingRead;
    /** The error details if the request was not successful. */
    error?: ApiResponseOffsetPaginationCallbackMappingReadError;
    /**
     * The meta details if the request. DEPRECATED
     * @deprecated
     */
    meta?: ApiResponseOffsetPaginationCallbackMappingReadMeta;
}

export interface BodyCallbackHistoryBackupEndpointsRestoreBackupCallbridgeV1HistoryBackupRestorePost {
    /** Put GZIP compressed .jsonl archive */
    file: Blob;
}

export interface CallbackHistoryBackup {
    /** File name of the backup */
    file_name: string;
    /** File size in bytes */
    file_size: number;
    /** Date when the backup was created */
    created: string;
    /** Number of records in backup */
    records_count: number;
}

/**
 * Full callback URL
 */
export type CallbackHistoryReadRequestUrl = string | null;

/**
 * Incoming headers
 */
export type CallbackHistoryReadRequestHeaders = { [key: string]: unknown };

/**
 * Incoming query params
 */
export type CallbackHistoryReadRequestParams = { [key: string]: unknown };

/**
 * Incoming body
 */
export type CallbackHistoryReadRequestBody = string | null;

/**
 * HTTP status code returned by destination
 */
export type CallbackHistoryReadResponseStatus = number | null;

export type CallbackHistoryReadResponseHeadersAnyOf = { [key: string]: unknown };

/**
 * Response headers
 */
export type CallbackHistoryReadResponseHeaders = CallbackHistoryReadResponseHeadersAnyOf | null;

/**
 * Response body
 */
export type CallbackHistoryReadResponseBody = string | null;

/**
 * Actual delivery time
 */
export type CallbackHistoryReadDeliveredAt = string | null;

/**
 * Transaction ID
 */
export type CallbackHistoryReadTransactionId = string | null;

/**
 * External Order ID
 */
export type CallbackHistoryReadExternalOrderId = string | null;

/**
 * Planned time for next retry
 */
export type CallbackHistoryReadNextRetryAt = string | null;

/**
 * Error explanation if failed
 */
export type CallbackHistoryReadErrorMessage = string | null;

export type CallbackHistoryReadChangesHistoryItem = { [key: string]: unknown };

/**
 * Linked mapping if matched
 */
export type CallbackHistoryReadMappingId = string | null;

/**
 * Callback Mapping entity
 */
export type CallbackHistoryReadMapping = CallbackMappingBase | null;

export interface CallbackHistoryRead {
    /** Full original callback URL */
    original_url: string;
    /** HTTP method */
    request_method: string;
    /** Full callback URL */
    request_url?: CallbackHistoryReadRequestUrl;
    /** Incoming headers */
    request_headers: CallbackHistoryReadRequestHeaders;
    /** Incoming query params */
    request_params: CallbackHistoryReadRequestParams;
    /** Incoming body */
    request_body?: CallbackHistoryReadRequestBody;
    /** HTTP status code returned by destination */
    response_status?: CallbackHistoryReadResponseStatus;
    /** Response headers */
    response_headers?: CallbackHistoryReadResponseHeaders;
    /** Response body */
    response_body?: CallbackHistoryReadResponseBody;
    /** Actual delivery time */
    delivered_at?: CallbackHistoryReadDeliveredAt;
    /** Transaction ID */
    transaction_id?: CallbackHistoryReadTransactionId;
    /** External Order ID */
    external_order_id?: CallbackHistoryReadExternalOrderId;
    /** Processing status */
    status: CallbackStatusEnum;
    /** What triggered this delivery */
    trigger_type: CallbackTriggerType;
    /** How many times attempted */
    attempts?: number;
    /** Planned time for next retry */
    next_retry_at?: CallbackHistoryReadNextRetryAt;
    /** Error explanation if failed */
    error_message?: CallbackHistoryReadErrorMessage;
    /** Changes history */
    changes_history?: CallbackHistoryReadChangesHistoryItem[];
    /** Identifier of the callback history */
    id: string;
    /** Linked mapping if matched */
    mapping_id?: CallbackHistoryReadMappingId;
    /** Identifier of the callback attempt flow */
    callback_id: string;
    /** Callback Mapping entity */
    mapping?: CallbackHistoryReadMapping;
    created_at: string;
    updated_at: string;
}

export interface CallbackHistoryRestoreResult {
    /** Number records in backup */
    total: number;
    /** Number of inserted records */
    inserted?: number;
    /** Number of deleted records */
    deleted?: number;
    /** Number of skipped records */
    skipped?: number;
}

/**
 * Description of the CallbackMapping
 */
export type CallbackMappingBaseDescription = string | null;

/**
 * NATS subject for the adapter to publish messages to
 */
export type CallbackMappingBaseAdapterNatsSubject = string | null;

/**
 * Terminal to which the callback is associated
 */
export type CallbackMappingBaseTerminal = TerminalOutput | null;

/**
 * Full internal URL path to route the request to
 */
export type CallbackMappingBaseInternalPath = string | null;

export interface CallbackMappingBase {
    /** Name of the CallbackMapping */
    name: string;
    /** Description of the CallbackMapping */
    description?: CallbackMappingBaseDescription;
    /** Full external path exposed to clients */
    external_path: string;
    /** NATS subject for the adapter to publish messages to */
    adapter_nats_subject?: CallbackMappingBaseAdapterNatsSubject;
    /** Terminal to which the callback is associated */
    terminal?: CallbackMappingBaseTerminal;
    /** Full internal URL path to route the request to */
    internal_path?: CallbackMappingBaseInternalPath;
    /** Security policy including IP filtering and rate limiting */
    security_policy?: SecurityPolicyConfig;
    /** Delivery policy (strategy, retry, fallback) */
    delivery_policy?: DeliveryPolicyOutput;
}

export interface CallbackMappingBulkCreate {
    /**
     * List of callback mappings to create or update
     * @minItems 1
     * @maxItems 100
     */
    mappings: CallbackMappingCreate[];
}

export type CallbackMappingBulkResponseErrorsItem = { [key: string]: string };

export interface CallbackMappingBulkResponse {
    /** Successfully created mappings */
    created?: CallbackMappingRead[];
    /** Successfully updated mappings */
    updated?: CallbackMappingRead[];
    /** Errors that occurred during processing */
    errors?: CallbackMappingBulkResponseErrorsItem[];
    /** Total number of mappings processed */
    total_processed: number;
    /** Number of successful operations */
    total_successful: number;
    /** Number of failed operations */
    total_errors: number;
}

/**
 * Description of the CallbackMapping
 */
export type CallbackMappingCreateDescription = string | null;

/**
 * NATS subject for the adapter to publish messages to
 */
export type CallbackMappingCreateAdapterNatsSubject = string | null;

/**
 * Terminal to which the callback is associated
 */
export type CallbackMappingCreateTerminal = TerminalInput | null;

/**
 * Full internal URL path to route the request to
 */
export type CallbackMappingCreateInternalPath = string | null;

export interface CallbackMappingCreate {
    /** Name of the CallbackMapping */
    name: string;
    /** Description of the CallbackMapping */
    description?: CallbackMappingCreateDescription;
    /** Full external path exposed to clients */
    external_path: string;
    /** NATS subject for the adapter to publish messages to */
    adapter_nats_subject?: CallbackMappingCreateAdapterNatsSubject;
    /** Terminal to which the callback is associated */
    terminal?: CallbackMappingCreateTerminal;
    /** Full internal URL path to route the request to */
    internal_path?: CallbackMappingCreateInternalPath;
    /** Security policy including IP filtering and rate limiting */
    security_policy?: SecurityPolicyConfig;
    /** Delivery policy (strategy, retry, fallback) */
    delivery_policy?: DeliveryPolicyInput;
}

/**
 * Description of the CallbackMapping
 */
export type CallbackMappingReadDescription = string | null;

/**
 * NATS subject for the adapter to publish messages to
 */
export type CallbackMappingReadAdapterNatsSubject = string | null;

/**
 * Terminal to which the callback is associated
 */
export type CallbackMappingReadTerminal = TerminalOutput | null;

/**
 * Full internal URL path to route the request to
 */
export type CallbackMappingReadInternalPath = string | null;

export interface CallbackMappingRead {
    /** Name of the CallbackMapping */
    name: string;
    /** Description of the CallbackMapping */
    description?: CallbackMappingReadDescription;
    /** Full external path exposed to clients */
    external_path: string;
    /** NATS subject for the adapter to publish messages to */
    adapter_nats_subject?: CallbackMappingReadAdapterNatsSubject;
    /** Terminal to which the callback is associated */
    terminal?: CallbackMappingReadTerminal;
    /** Full internal URL path to route the request to */
    internal_path?: CallbackMappingReadInternalPath;
    /** Security policy including IP filtering and rate limiting */
    security_policy?: SecurityPolicyConfig;
    /** Delivery policy (strategy, retry, fallback) */
    delivery_policy?: DeliveryPolicyOutput;
    id: string;
    created_at: string;
    updated_at: string;
    /** Full callback_url path exposed to internal service */
    readonly callback_url: string;
}

/**
 * Name of the CallbackMapping
 */
export type CallbackMappingUpdateName = string | null;

/**
 * Description of the CallbackMapping
 */
export type CallbackMappingUpdateDescription = string | null;

/**
 * New external path
 */
export type CallbackMappingUpdateExternalPath = string | null;

/**
 * NATS subject for the adapter to publish messages to
 */
export type CallbackMappingUpdateAdapterNatsSubject = string | null;

/**
 * Terminal to which the callback is associated
 */
export type CallbackMappingUpdateTerminal = TerminalInput | null;

/**
 * Updated security policy
 */
export type CallbackMappingUpdateSecurityPolicy = SecurityPolicyConfig | null;

/**
 * Updated delivery policy
 */
export type CallbackMappingUpdateDeliveryPolicy = DeliveryPolicyInput | null;

export interface CallbackMappingUpdate {
    /** Name of the CallbackMapping */
    name?: CallbackMappingUpdateName;
    /** Description of the CallbackMapping */
    description?: CallbackMappingUpdateDescription;
    /** New external path */
    external_path?: CallbackMappingUpdateExternalPath;
    /** NATS subject for the adapter to publish messages to */
    adapter_nats_subject?: CallbackMappingUpdateAdapterNatsSubject;
    /** Terminal to which the callback is associated */
    terminal?: CallbackMappingUpdateTerminal;
    /** Updated security policy */
    security_policy?: CallbackMappingUpdateSecurityPolicy;
    /** Updated delivery policy */
    delivery_policy?: CallbackMappingUpdateDeliveryPolicy;
}

/**
 * HTTP headers
 */
export type CallbackResponseHeaders = { [key: string]: string };

/**
 * Response body
 */
export type CallbackResponseBody = string | null;

export interface CallbackResponse {
    /**
     * HTTP status code
     * @minimum 100
     * @maximum 599
     */
    status_code?: number;
    /** HTTP headers */
    headers?: CallbackResponseHeaders;
    /** Response body */
    body?: CallbackResponseBody;
}

export interface CallbackRetryRequestItems {
    /** List unique identifiers of the callback */
    callback_ids: string[];
}

export interface CallbackRetryResponse {
    /** Successfully delivered callbacks */
    delivered?: DeliveryRequestMessage[];
    /** Skipped callbacks */
    skipped?: CallbackRetrySkippedItem[];
}

export interface CallbackRetrySkippedItem {
    /** Identifier of the callback */
    callback_id: string;
    /** Reason for skipping */
    reason: string;
}

export type CallbackStatusEnum = (typeof CallbackStatusEnum)[keyof typeof CallbackStatusEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CallbackStatusEnum = {
    security_rejected: "security_rejected",
    queued: "queued",
    rpc_sent: "rpc_sent",
    rpc_completed: "rpc_completed",
    rpc_failed: "rpc_failed",
    rpc_timeout: "rpc_timeout",
    processing: "processing",
    delivered: "delivered",
    error: "error",
    retrying: "retrying",
    success: "success",
    quick_processing: "quick_processing"
} as const;

export type CallbackTriggerType = (typeof CallbackTriggerType)[keyof typeof CallbackTriggerType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CallbackTriggerType = {
    system: "system",
    retry: "retry",
    manual: "manual",
    unknown: "unknown"
} as const;

export interface DeliveryPolicyInput {
    /** Delivery strategy */
    strategy?: DeliveryStrategyEnum;
    /** Retry policy */
    retry_policy?: RetryPolicyConfig;
    /** Timeout configuration for different strategies */
    timeout_config?: TimeoutConfig;
    /** Response policy from template or response */
    response_policy?: ResponsePolicy;
}

export interface DeliveryPolicyOutput {
    /** Delivery strategy */
    strategy?: DeliveryStrategyEnum;
    /** Retry policy */
    retry_policy?: RetryPolicyConfig;
    /** Timeout configuration for different strategies */
    timeout_config?: TimeoutConfig;
    /** Response policy from template or response */
    response_policy?: ResponsePolicy;
}

/**
 * Target internal URL
 */
export type DeliveryRequestMessageUrl = string | null;

/**
 * Query parameters
 */
export type DeliveryRequestMessageParams = { [key: string]: unknown };

/**
 * Request headers
 */
export type DeliveryRequestMessageHeaders = { [key: string]: string };

/**
 * Raw request body
 */
export type DeliveryRequestMessageBody = string | null;

/**
 * Planned time for next retry
 */
export type DeliveryRequestMessageNextRetryAt = string | null;

/**
 * NATS subject for the adapter to publish messages to
 */
export type DeliveryRequestMessageAdapterNatsSubject = string | null;

/**
 * Terminal to which the callback is associated
 */
export type DeliveryRequestMessageTerminal = TerminalOutput | null;

export interface DeliveryRequestMessage {
    /** Callback tracking ID */
    callback_id: string;
    /** Associated mapping ID */
    mapping_id: string;
    /** Target internal URL */
    original_url: string;
    /** Target internal URL */
    url?: DeliveryRequestMessageUrl;
    /** HTTP method */
    method: string;
    /** Query parameters */
    params?: DeliveryRequestMessageParams;
    /** Request headers */
    headers?: DeliveryRequestMessageHeaders;
    /** Raw request body */
    body?: DeliveryRequestMessageBody;
    /** Current attempt count */
    attempt?: number;
    /** Planned time for next retry */
    next_retry_at?: DeliveryRequestMessageNextRetryAt;
    /** Security and access rules */
    security_policy?: SecurityPolicyConfig;
    /** Delivery policy */
    delivery_policy?: DeliveryPolicyOutput;
    /** What triggered this delivery */
    trigger_type: CallbackTriggerType;
    /** NATS subject for the adapter to publish messages to */
    adapter_nats_subject?: DeliveryRequestMessageAdapterNatsSubject;
    /** Terminal to which the callback is associated */
    terminal?: DeliveryRequestMessageTerminal;
}

export type DeliveryStrategyEnum = (typeof DeliveryStrategyEnum)[keyof typeof DeliveryStrategyEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DeliveryStrategyEnum = {
    ASYNC_ONLY: "ASYNC_ONLY",
    RPC_STRICT: "RPC_STRICT",
    RPC_WITH_FALLBACK: "RPC_WITH_FALLBACK"
} as const;

export interface ErrorBody {
    /** A string identifier for the error type. */
    error_type: string;
    /** A human-readable error message describing the issue. */
    error_message: string;
}

/**
 * Currency code for the fee
 */
export type FeeCurrency = string | null;

/**
 * Fee direction if applicable
 */
export type FeeDirection = TransactionType | null;

/**
 * Optional fee description
 */
export type FeeDescription = string | null;

export interface Fee {
    /** Unique identifier for the fee */
    id?: string;
    /** Recipient for the fee */
    recipient: string;
    /** Type of the fee */
    type: FeeType;
    /** Currency code for the fee */
    currency?: FeeCurrency;
    /** Rate value for the fee */
    value: RateValue;
    /** Fee direction if applicable */
    direction?: FeeDirection;
    /** Optional fee description */
    description?: FeeDescription;
}

export type FeeType = (typeof FeeType)[keyof typeof FeeType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FeeType = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3
} as const;

export interface HTTPValidationError {
    detail?: ValidationError[];
}

export interface OffsetPaginationCallbackHistoryBackup {
    /** A list of items in the current page. */
    items: CallbackHistoryBackup[];
    /** The maximum number of items returned in a single page. */
    limit: number;
    /** The starting index for the current page. */
    offset: number;
    /** The total number of available items. */
    total: number;
}

export interface OffsetPaginationCallbackHistoryRead {
    /** A list of items in the current page. */
    items: CallbackHistoryRead[];
    /** The maximum number of items returned in a single page. */
    limit: number;
    /** The starting index for the current page. */
    offset: number;
    /** The total number of available items. */
    total: number;
}

export interface OffsetPaginationCallbackMappingRead {
    /** A list of items in the current page. */
    items: CallbackMappingRead[];
    /** The maximum number of items returned in a single page. */
    limit: number;
    /** The starting index for the current page. */
    offset: number;
    /** The total number of available items. */
    total: number;
}

export type PaymentCategory = (typeof PaymentCategory)[keyof typeof PaymentCategory];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentCategory = {
    p2p: "p2p",
    ecom: "ecom"
} as const;

/**
 * Arbitrary metadata for the payment type (JSON object)
 */
export type PaymentTypeBaseMeta = { [key: string]: unknown };

export interface PaymentTypeBase {
    /**
     * Unique payment type code
     * @pattern ^[A-Za-z0-9_-]+$
     */
    code: string;
    /** Human-readable payment type title */
    title: string;
    /** Category of the payment type (H2H or ECOM) */
    category: PaymentCategory;
    /** List of field names required to initiate a payment with this type. These fields must exist in the Requisites model. */
    required_fields_for_payment?: RequiredFieldsForPayment;
    /** Arbitrary metadata for the payment type (JSON object) */
    meta?: PaymentTypeBaseMeta;
}

export interface RateValue {
    /**
     * The quantity part of the rate value. It represents the numeric value without the decimal separator. For example, '12.34' is stored as 1234.
     * @minimum 0
     */
    quantity?: number;
    /**
     * The accuracy factor for the rate value. It must be a power of 10 (e.g., 1, 10, 100, 1000) corresponding to the number of decimal places.
     * @minimum 0
     */
    accuracy?: number;
}

export interface RequiredFieldsForPayment {
    /** List of required fields for deposit operation */
    deposit?: string[];
    /** List of required fields for withdrawal operation */
    withdrawal?: string[];
}

/**
 * Response template
 */
export type ResponsePolicyTemplate = CallbackResponse | null;

export interface ResponsePolicy {
    /** Response type */
    type?: ResponsePolicyTypeEnum;
    /** Response template */
    template?: ResponsePolicyTemplate;
}

export type ResponsePolicyTypeEnum = (typeof ResponsePolicyTypeEnum)[keyof typeof ResponsePolicyTypeEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ResponsePolicyTypeEnum = {
    FROM_TEMPLATE: "FROM_TEMPLATE",
    FROM_RESPONSE: "FROM_RESPONSE"
} as const;

export type RestoreStrategy = (typeof RestoreStrategy)[keyof typeof RestoreStrategy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RestoreStrategy = {
    merge: "merge",
    skip: "skip",
    overwrite: "overwrite"
} as const;

export interface RetryPolicyConfig {
    /** Enable retries for this mapping */
    enabled?: boolean;
    /** Maximum number of retry attempts */
    max_attempts?: number;
    /** Base delay (in seconds) between retries */
    base_delay?: number;
    /** List of HTTP status codes that should trigger a retry. Empty list disables retry based on status code. */
    retry_on_status?: number[];
    /** Backoff strategy to use */
    strategy?: RetryStrategy;
}

export type RetryStrategy = (typeof RetryStrategy)[keyof typeof RetryStrategy];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RetryStrategy = {
    fixed: "fixed",
    exponential: "exponential"
} as const;

export type SecurityPolicyConfigAllowedIpsItem = string | string;

export type SecurityPolicyConfigBlockedIpsItem = string | string;

/**
 * Maximum number of requests per minute per source IP
 */
export type SecurityPolicyConfigRateLimit = number | null;

/**
 * Mode of policy enforcement: 'log' only logs violations, 'strict' blocks them
 */
export type SecurityPolicyConfigEnforcementMode =
    (typeof SecurityPolicyConfigEnforcementMode)[keyof typeof SecurityPolicyConfigEnforcementMode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SecurityPolicyConfigEnforcementMode = {
    log: "log",
    strict: "strict"
} as const;

export interface SecurityPolicyConfig {
    /** List of allowed IPs or networks (CIDR) that can access the route */
    allowed_ips?: SecurityPolicyConfigAllowedIpsItem[];
    /** IPs or networks to explicitly deny (takes precedence over allowed) */
    blocked_ips?: SecurityPolicyConfigBlockedIpsItem[];
    /** Maximum number of requests per minute per source IP */
    rate_limit?: SecurityPolicyConfigRateLimit;
    /** Entire route is blocked and should not process any callbacks */
    blocked?: boolean;
    /** Mode of policy enforcement: 'log' only logs violations, 'strict' blocks them */
    enforcement_mode?: SecurityPolicyConfigEnforcementMode;
}

export type Status = (typeof Status)[keyof typeof Status];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const Status = {
    Ok: "Ok"
} as const;

/**
 * Description of the terminal
 */
export type TerminalInputDescription = string | null;

/**
 * Mapping of fee configurations with fee.id as key
 */
export type TerminalInputFees = { [key: string]: Fee };

/**
 * Authentication data for the terminal
 */
export type TerminalInputAuth = { [key: string]: unknown };

/**
 * Callback URL template or final callback URL. If the value contains '{api_key}', it will be replaced with auth['api_key'] during registration.
 */
export type TerminalInputCallbackUrl = string | null;

/**
 * Additional details about the terminal
 */
export type TerminalInputDetails = { [key: string]: unknown };

export interface TerminalInput {
    /** Unique identifier of the terminal */
    terminal_id: string;
    /** Name of the terminal */
    verbose_name: string;
    /** Description of the terminal */
    description?: TerminalInputDescription;
    /** Timeout for allocation in seconds */
    allocation_timeout_seconds?: number;
    /** Mapping of fee configurations with fee.id as key */
    fees?: TerminalInputFees;
    /** Provider name associated with the terminal */
    provider: string;
    /** Authentication data for the terminal */
    auth?: TerminalInputAuth;
    /** Indicates if the account is created */
    account_created?: boolean;
    /** Callback URL template or final callback URL. If the value contains '{api_key}', it will be replaced with auth['api_key'] during registration. */
    callback_url?: TerminalInputCallbackUrl;
    /** Additional details about the terminal */
    details?: TerminalInputDetails;
    /** List of payment types associated with this terminal */
    payment_types?: PaymentTypeBase[];
}

/**
 * Description of the terminal
 */
export type TerminalOutputDescription = string | null;

/**
 * Mapping of fee configurations with fee.id as key
 */
export type TerminalOutputFees = { [key: string]: Fee };

/**
 * Authentication data for the terminal
 */
export type TerminalOutputAuth = { [key: string]: unknown };

/**
 * Callback URL template or final callback URL. If the value contains '{api_key}', it will be replaced with auth['api_key'] during registration.
 */
export type TerminalOutputCallbackUrl = string | null;

/**
 * Additional details about the terminal
 */
export type TerminalOutputDetails = { [key: string]: unknown };

export interface TerminalOutput {
    /** Unique identifier of the terminal */
    terminal_id: string;
    /** Name of the terminal */
    verbose_name: string;
    /** Description of the terminal */
    description?: TerminalOutputDescription;
    /** Timeout for allocation in seconds */
    allocation_timeout_seconds?: number;
    /** Mapping of fee configurations with fee.id as key */
    fees?: TerminalOutputFees;
    /** Provider name associated with the terminal */
    provider: string;
    /** Authentication data for the terminal */
    auth?: TerminalOutputAuth;
    /** Indicates if the account is created */
    account_created?: boolean;
    /** Callback URL template or final callback URL. If the value contains '{api_key}', it will be replaced with auth['api_key'] during registration. */
    callback_url?: TerminalOutputCallbackUrl;
    /** Additional details about the terminal */
    details?: TerminalOutputDetails;
    /** List of payment types associated with this terminal */
    payment_types?: PaymentTypeBase[];
}

export interface TimeoutConfig {
    /**
     * RPC timeout in seconds
     * @minimum 1
     * @maximum 600
     */
    rpc_timeout?: number;
    /**
     * Async timeout in seconds
     * @minimum 1
     * @maximum 3600
     */
    async_timeout?: number;
}

export type TransactionType = (typeof TransactionType)[keyof typeof TransactionType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TransactionType = {
    NUMBER_1: 1,
    NUMBER_2: 2,
    NUMBER_3: 3,
    NUMBER_4: 4
} as const;

export type ValidationErrorLocItem = string | number;

export interface ValidationError {
    loc: ValidationErrorLocItem[];
    msg: string;
    type: string;
}

export type CallbackMappingEndpointsListMappingsCallbridgeV1MappingGetParams = {
    /**
     * List of identifiers for filtering
     */
    ids?: string[] | null;
    /**
     * Upper bound for creation date filter
     */
    createdBefore?: string | null;
    /**
     * Lower bound for creation date filter
     */
    createdAfter?: string | null;
    /**
     * Upper bound for update date filter
     */
    updatedBefore?: string | null;
    /**
     * Lower bound for update date filter
     */
    updatedAfter?: string | null;
    /**
     * Current page number (starting from 1)
     */
    currentPage?: number;
    /**
     * Number of records per page
     */
    pageSize?: number;
    /**
     * List of fields to perform the search on
     */
    searchField?: string[] | null;
    /**
     * List of values to search for in corresponding fields
     */
    searchString?: string[] | null;
    /**
     * Determines if the search should be case insensitive
     */
    searchIgnoreCase?: boolean;
    /**
     * Field to sort the results by
     */
    orderBy?: string | null;
    /**
     * Sort order: 'asc' or 'desc'
     */
    sortOrder?: CallbackMappingEndpointsListMappingsCallbridgeV1MappingGetSortOrder;
};

export type CallbackMappingEndpointsListMappingsCallbridgeV1MappingGetSortOrder =
    (typeof CallbackMappingEndpointsListMappingsCallbridgeV1MappingGetSortOrder)[keyof typeof CallbackMappingEndpointsListMappingsCallbridgeV1MappingGetSortOrder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CallbackMappingEndpointsListMappingsCallbridgeV1MappingGetSortOrder = {
    asc: "asc",
    desc: "desc"
} as const;

export type CallbackHistoryBackupEndpointsListBackupsCallbridgeV1HistoryBackupGetParams = {
    /**
     * Current page number (starting from 1)
     */
    currentPage?: number;
    /**
     * Number of files per page
     */
    pageSize?: number;
    /**
     * Show up to this date (ISO)
     */
    createdAfter?: string | null;
    /**
     * Show from this date (ISO)
     */
    createdBefore?: string | null;
    /**
     * Sort order: 'asc' or 'desc'
     */
    sortOrder?: CallbackHistoryBackupEndpointsListBackupsCallbridgeV1HistoryBackupGetSortOrder;
};

export type CallbackHistoryBackupEndpointsListBackupsCallbridgeV1HistoryBackupGetSortOrder =
    (typeof CallbackHistoryBackupEndpointsListBackupsCallbridgeV1HistoryBackupGetSortOrder)[keyof typeof CallbackHistoryBackupEndpointsListBackupsCallbridgeV1HistoryBackupGetSortOrder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CallbackHistoryBackupEndpointsListBackupsCallbridgeV1HistoryBackupGetSortOrder = {
    asc: "asc",
    desc: "desc"
} as const;

export type CallbackHistoryBackupEndpointsDownloadBackupCallbridgeV1HistoryBackupDownloadGetParams = {
    /**
     * Backup file name, format: YYYY-MM-DD.jsonl.gz
     */
    fileName: string;
};

export type CallbackHistoryBackupEndpointsRestoreBackupCallbridgeV1HistoryBackupRestorePostParams = {
    /**
     * Restore strategy
     */
    strategy?: RestoreStrategy;
};

export type CallbackHistoryEndpointsListHistoryCallbridgeV1HistoryGetParams = {
    /**
     * List of identifiers for filtering
     */
    ids?: string[] | null;
    /**
     * Upper bound for creation date filter
     */
    createdBefore?: string | null;
    /**
     * Lower bound for creation date filter
     */
    createdAfter?: string | null;
    /**
     * Upper bound for update date filter
     */
    updatedBefore?: string | null;
    /**
     * Lower bound for update date filter
     */
    updatedAfter?: string | null;
    /**
     * Current page number (starting from 1)
     */
    currentPage?: number;
    /**
     * Number of records per page
     */
    pageSize?: number;
    /**
     * List of fields to perform the search on
     */
    searchField?: string[] | null;
    /**
     * List of values to search for in corresponding fields
     */
    searchString?: string[] | null;
    /**
     * Determines if the search should be case insensitive
     */
    searchIgnoreCase?: boolean;
    /**
     * Field to sort the results by
     */
    orderBy?: string | null;
    /**
     * Sort order: 'asc' or 'desc'
     */
    sortOrder?: CallbackHistoryEndpointsListHistoryCallbridgeV1HistoryGetSortOrder;
};

export type CallbackHistoryEndpointsListHistoryCallbridgeV1HistoryGetSortOrder =
    (typeof CallbackHistoryEndpointsListHistoryCallbridgeV1HistoryGetSortOrder)[keyof typeof CallbackHistoryEndpointsListHistoryCallbridgeV1HistoryGetSortOrder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CallbackHistoryEndpointsListHistoryCallbridgeV1HistoryGetSortOrder = {
    asc: "asc",
    desc: "desc"
} as const;

export type CallbackHistoryEndpointsGetCallbackCallbridgeV1HistoryCallbackIdGetParams = {
    /**
     * List of identifiers for filtering
     */
    ids?: string[] | null;
    /**
     * Upper bound for creation date filter
     */
    createdBefore?: string | null;
    /**
     * Lower bound for creation date filter
     */
    createdAfter?: string | null;
    /**
     * Upper bound for update date filter
     */
    updatedBefore?: string | null;
    /**
     * Lower bound for update date filter
     */
    updatedAfter?: string | null;
    /**
     * Current page number (starting from 1)
     */
    currentPage?: number;
    /**
     * Number of records per page
     */
    pageSize?: number;
    /**
     * List of fields to perform the search on
     */
    searchField?: string[] | null;
    /**
     * List of values to search for in corresponding fields
     */
    searchString?: string[] | null;
    /**
     * Determines if the search should be case insensitive
     */
    searchIgnoreCase?: boolean;
    /**
     * Field to sort the results by
     */
    orderBy?: string | null;
    /**
     * Sort order: 'asc' or 'desc'
     */
    sortOrder?: CallbackHistoryEndpointsGetCallbackCallbridgeV1HistoryCallbackIdGetSortOrder;
};

export type CallbackHistoryEndpointsGetCallbackCallbridgeV1HistoryCallbackIdGetSortOrder =
    (typeof CallbackHistoryEndpointsGetCallbackCallbridgeV1HistoryCallbackIdGetSortOrder)[keyof typeof CallbackHistoryEndpointsGetCallbackCallbridgeV1HistoryCallbackIdGetSortOrder];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CallbackHistoryEndpointsGetCallbackCallbridgeV1HistoryCallbackIdGetSortOrder = {
    asc: "asc",
    desc: "desc"
} as const;
