/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * BlowFish - Enigma API Service
 * OpenAPI spec version: local
 */
import type {
    ApiResponseDirection,
    ApiResponseNoneType,
    ApiResponseOffsetPaginationDirection,
    ApiResponseOffsetPaginationPaymentTypeModel,
    DirectionCreate,
    DirectionEndpointsGetAvailablePaymentTypesEnigmaV1DirectionAvailablePaymentTypesGetParams,
    DirectionEndpointsListDirectionsByMerchantIdEnigmaV1DirectionMerchantMerchantIdGetParams,
    DirectionEndpointsListDirectionsEnigmaV1DirectionGetParams,
    DirectionUpdate,
    DirectionUpdateBulkItem,
    DirectionUpdateLimits,
    DirectionUpdateState,
    DirectionUpdateType,
    FeeCreate,
    FeeUpdate,
    HTTPValidationError,
    PaymentTypesLink
} from "../blowFishEnigmaAPIService.schemas";

import { authFetch } from "../../../helpers/orvalAuthFetchMiddleware";

/**
 * Returns a paginated list of directions. Supports filtering and pagination
 * @summary Get a paginated list of directions
 */
export type directionEndpointsListDirectionsEnigmaV1DirectionGetResponse200 = {
    data: ApiResponseOffsetPaginationDirection;
    status: 200;
};

export type directionEndpointsListDirectionsEnigmaV1DirectionGetResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type directionEndpointsListDirectionsEnigmaV1DirectionGetResponseComposite =
    | directionEndpointsListDirectionsEnigmaV1DirectionGetResponse200
    | directionEndpointsListDirectionsEnigmaV1DirectionGetResponse422;

export type directionEndpointsListDirectionsEnigmaV1DirectionGetResponse =
    directionEndpointsListDirectionsEnigmaV1DirectionGetResponseComposite & {
        headers: Headers;
    };

export const getDirectionEndpointsListDirectionsEnigmaV1DirectionGetUrl = (
    params?: DirectionEndpointsListDirectionsEnigmaV1DirectionGetParams
) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? "null" : value.toString());
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/direction?${stringifiedParams}`
        : `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/direction`;
};

export const directionEndpointsListDirectionsEnigmaV1DirectionGet = async (
    params?: DirectionEndpointsListDirectionsEnigmaV1DirectionGetParams,
    options?: RequestInit
): Promise<directionEndpointsListDirectionsEnigmaV1DirectionGetResponse> => {
    return authFetch<directionEndpointsListDirectionsEnigmaV1DirectionGetResponse>(
        getDirectionEndpointsListDirectionsEnigmaV1DirectionGetUrl(params),
        {
            ...options,
            method: "GET"
        }
    );
};

/**
 * Registers a new direction in the system
 * @summary Create a new direction
 */
export type directionEndpointsCreateDirectionEnigmaV1DirectionPostResponse200 = {
    data: ApiResponseDirection;
    status: 200;
};

export type directionEndpointsCreateDirectionEnigmaV1DirectionPostResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type directionEndpointsCreateDirectionEnigmaV1DirectionPostResponseComposite =
    | directionEndpointsCreateDirectionEnigmaV1DirectionPostResponse200
    | directionEndpointsCreateDirectionEnigmaV1DirectionPostResponse422;

export type directionEndpointsCreateDirectionEnigmaV1DirectionPostResponse =
    directionEndpointsCreateDirectionEnigmaV1DirectionPostResponseComposite & {
        headers: Headers;
    };

export const getDirectionEndpointsCreateDirectionEnigmaV1DirectionPostUrl = () => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/direction`;
};

export const directionEndpointsCreateDirectionEnigmaV1DirectionPost = async (
    directionCreate: DirectionCreate,
    options?: RequestInit
): Promise<directionEndpointsCreateDirectionEnigmaV1DirectionPostResponse> => {
    return authFetch<directionEndpointsCreateDirectionEnigmaV1DirectionPostResponse>(
        getDirectionEndpointsCreateDirectionEnigmaV1DirectionPostUrl(),
        {
            ...options,
            method: "POST",
            headers: { "Content-Type": "application/json", ...options?.headers },
            body: JSON.stringify(directionCreate)
        }
    );
};

/**
 * Returns a paginated list of directions filtered by merchant unique ID
 * @summary Get a paginated list of directions by merchant
 */
export type directionEndpointsListDirectionsByMerchantIdEnigmaV1DirectionMerchantMerchantIdGetResponse200 = {
    data: ApiResponseOffsetPaginationDirection;
    status: 200;
};

export type directionEndpointsListDirectionsByMerchantIdEnigmaV1DirectionMerchantMerchantIdGetResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type directionEndpointsListDirectionsByMerchantIdEnigmaV1DirectionMerchantMerchantIdGetResponseComposite =
    | directionEndpointsListDirectionsByMerchantIdEnigmaV1DirectionMerchantMerchantIdGetResponse200
    | directionEndpointsListDirectionsByMerchantIdEnigmaV1DirectionMerchantMerchantIdGetResponse422;

export type directionEndpointsListDirectionsByMerchantIdEnigmaV1DirectionMerchantMerchantIdGetResponse =
    directionEndpointsListDirectionsByMerchantIdEnigmaV1DirectionMerchantMerchantIdGetResponseComposite & {
        headers: Headers;
    };

export const getDirectionEndpointsListDirectionsByMerchantIdEnigmaV1DirectionMerchantMerchantIdGetUrl = (
    merchantId: string,
    params?: DirectionEndpointsListDirectionsByMerchantIdEnigmaV1DirectionMerchantMerchantIdGetParams
) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? "null" : value.toString());
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/direction/merchant/${merchantId}?${stringifiedParams}`
        : `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/direction/merchant/${merchantId}`;
};

export const directionEndpointsListDirectionsByMerchantIdEnigmaV1DirectionMerchantMerchantIdGet = async (
    merchantId: string,
    params?: DirectionEndpointsListDirectionsByMerchantIdEnigmaV1DirectionMerchantMerchantIdGetParams,
    options?: RequestInit
): Promise<directionEndpointsListDirectionsByMerchantIdEnigmaV1DirectionMerchantMerchantIdGetResponse> => {
    return authFetch<directionEndpointsListDirectionsByMerchantIdEnigmaV1DirectionMerchantMerchantIdGetResponse>(
        getDirectionEndpointsListDirectionsByMerchantIdEnigmaV1DirectionMerchantMerchantIdGetUrl(merchantId, params),
        {
            ...options,
            method: "GET"
        }
    );
};

/**
 * Fetches the details of a direction identified by its unique ID
 * @summary Retrieve direction details
 */
export type directionEndpointsGetDirectionEnigmaV1DirectionDirectionIdGetResponse200 = {
    data: ApiResponseDirection;
    status: 200;
};

export type directionEndpointsGetDirectionEnigmaV1DirectionDirectionIdGetResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type directionEndpointsGetDirectionEnigmaV1DirectionDirectionIdGetResponseComposite =
    | directionEndpointsGetDirectionEnigmaV1DirectionDirectionIdGetResponse200
    | directionEndpointsGetDirectionEnigmaV1DirectionDirectionIdGetResponse422;

export type directionEndpointsGetDirectionEnigmaV1DirectionDirectionIdGetResponse =
    directionEndpointsGetDirectionEnigmaV1DirectionDirectionIdGetResponseComposite & {
        headers: Headers;
    };

export const getDirectionEndpointsGetDirectionEnigmaV1DirectionDirectionIdGetUrl = (directionId: string) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/direction/${directionId}`;
};

export const directionEndpointsGetDirectionEnigmaV1DirectionDirectionIdGet = async (
    directionId: string,
    options?: RequestInit
): Promise<directionEndpointsGetDirectionEnigmaV1DirectionDirectionIdGetResponse> => {
    return authFetch<directionEndpointsGetDirectionEnigmaV1DirectionDirectionIdGetResponse>(
        getDirectionEndpointsGetDirectionEnigmaV1DirectionDirectionIdGetUrl(directionId),
        {
            ...options,
            method: "GET"
        }
    );
};

/**
 * Modifies the attributes of an existing direction identified by its unique ID
 * @summary Update direction details
 */
export type directionEndpointsUpdateDirectionEnigmaV1DirectionDirectionIdPutResponse200 = {
    data: ApiResponseDirection;
    status: 200;
};

export type directionEndpointsUpdateDirectionEnigmaV1DirectionDirectionIdPutResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type directionEndpointsUpdateDirectionEnigmaV1DirectionDirectionIdPutResponseComposite =
    | directionEndpointsUpdateDirectionEnigmaV1DirectionDirectionIdPutResponse200
    | directionEndpointsUpdateDirectionEnigmaV1DirectionDirectionIdPutResponse422;

export type directionEndpointsUpdateDirectionEnigmaV1DirectionDirectionIdPutResponse =
    directionEndpointsUpdateDirectionEnigmaV1DirectionDirectionIdPutResponseComposite & {
        headers: Headers;
    };

export const getDirectionEndpointsUpdateDirectionEnigmaV1DirectionDirectionIdPutUrl = (directionId: string) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/direction/${directionId}`;
};

export const directionEndpointsUpdateDirectionEnigmaV1DirectionDirectionIdPut = async (
    directionId: string,
    directionUpdate: DirectionUpdate,
    options?: RequestInit
): Promise<directionEndpointsUpdateDirectionEnigmaV1DirectionDirectionIdPutResponse> => {
    return authFetch<directionEndpointsUpdateDirectionEnigmaV1DirectionDirectionIdPutResponse>(
        getDirectionEndpointsUpdateDirectionEnigmaV1DirectionDirectionIdPutUrl(directionId),
        {
            ...options,
            method: "PUT",
            headers: { "Content-Type": "application/json", ...options?.headers },
            body: JSON.stringify(directionUpdate)
        }
    );
};

/**
 * Deletes a direction from the system using its unique ID
 * @summary Remove a direction
 */
export type directionEndpointsDeleteDirectionEnigmaV1DirectionDirectionIdDeleteResponse200 = {
    data: ApiResponseNoneType;
    status: 200;
};

export type directionEndpointsDeleteDirectionEnigmaV1DirectionDirectionIdDeleteResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type directionEndpointsDeleteDirectionEnigmaV1DirectionDirectionIdDeleteResponseComposite =
    | directionEndpointsDeleteDirectionEnigmaV1DirectionDirectionIdDeleteResponse200
    | directionEndpointsDeleteDirectionEnigmaV1DirectionDirectionIdDeleteResponse422;

export type directionEndpointsDeleteDirectionEnigmaV1DirectionDirectionIdDeleteResponse =
    directionEndpointsDeleteDirectionEnigmaV1DirectionDirectionIdDeleteResponseComposite & {
        headers: Headers;
    };

export const getDirectionEndpointsDeleteDirectionEnigmaV1DirectionDirectionIdDeleteUrl = (directionId: string) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/direction/${directionId}`;
};

export const directionEndpointsDeleteDirectionEnigmaV1DirectionDirectionIdDelete = async (
    directionId: string,
    options?: RequestInit
): Promise<directionEndpointsDeleteDirectionEnigmaV1DirectionDirectionIdDeleteResponse> => {
    return authFetch<directionEndpointsDeleteDirectionEnigmaV1DirectionDirectionIdDeleteResponse>(
        getDirectionEndpointsDeleteDirectionEnigmaV1DirectionDirectionIdDeleteUrl(directionId),
        {
            ...options,
            method: "DELETE"
        }
    );
};

/**
 * Updates multiple directions in one request using bulk update
 * @summary Bulk update directions
 */
export type directionEndpointsBulkUpdateDirectionsEnigmaV1DirectionBatchPatchResponse200 = {
    data: ApiResponseOffsetPaginationDirection;
    status: 200;
};

export type directionEndpointsBulkUpdateDirectionsEnigmaV1DirectionBatchPatchResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type directionEndpointsBulkUpdateDirectionsEnigmaV1DirectionBatchPatchResponseComposite =
    | directionEndpointsBulkUpdateDirectionsEnigmaV1DirectionBatchPatchResponse200
    | directionEndpointsBulkUpdateDirectionsEnigmaV1DirectionBatchPatchResponse422;

export type directionEndpointsBulkUpdateDirectionsEnigmaV1DirectionBatchPatchResponse =
    directionEndpointsBulkUpdateDirectionsEnigmaV1DirectionBatchPatchResponseComposite & {
        headers: Headers;
    };

export const getDirectionEndpointsBulkUpdateDirectionsEnigmaV1DirectionBatchPatchUrl = () => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/direction/batch`;
};

export const directionEndpointsBulkUpdateDirectionsEnigmaV1DirectionBatchPatch = async (
    directionUpdateBulkItem: DirectionUpdateBulkItem[],
    options?: RequestInit
): Promise<directionEndpointsBulkUpdateDirectionsEnigmaV1DirectionBatchPatchResponse> => {
    return authFetch<directionEndpointsBulkUpdateDirectionsEnigmaV1DirectionBatchPatchResponse>(
        getDirectionEndpointsBulkUpdateDirectionsEnigmaV1DirectionBatchPatchUrl(),
        {
            ...options,
            method: "PATCH",
            headers: { "Content-Type": "application/json", ...options?.headers },
            body: JSON.stringify(directionUpdateBulkItem)
        }
    );
};

/**
 * Updates the state (active/inactive) for the specified direction
 * @summary Update state for a direction
 */
export type directionEndpointsUpdateStateEnigmaV1DirectionDirectionIdStatePatchResponse200 = {
    data: ApiResponseDirection;
    status: 200;
};

export type directionEndpointsUpdateStateEnigmaV1DirectionDirectionIdStatePatchResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type directionEndpointsUpdateStateEnigmaV1DirectionDirectionIdStatePatchResponseComposite =
    | directionEndpointsUpdateStateEnigmaV1DirectionDirectionIdStatePatchResponse200
    | directionEndpointsUpdateStateEnigmaV1DirectionDirectionIdStatePatchResponse422;

export type directionEndpointsUpdateStateEnigmaV1DirectionDirectionIdStatePatchResponse =
    directionEndpointsUpdateStateEnigmaV1DirectionDirectionIdStatePatchResponseComposite & {
        headers: Headers;
    };

export const getDirectionEndpointsUpdateStateEnigmaV1DirectionDirectionIdStatePatchUrl = (directionId: string) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/direction/${directionId}/state`;
};

export const directionEndpointsUpdateStateEnigmaV1DirectionDirectionIdStatePatch = async (
    directionId: string,
    directionUpdateState: DirectionUpdateState,
    options?: RequestInit
): Promise<directionEndpointsUpdateStateEnigmaV1DirectionDirectionIdStatePatchResponse> => {
    return authFetch<directionEndpointsUpdateStateEnigmaV1DirectionDirectionIdStatePatchResponse>(
        getDirectionEndpointsUpdateStateEnigmaV1DirectionDirectionIdStatePatchUrl(directionId),
        {
            ...options,
            method: "PATCH",
            headers: { "Content-Type": "application/json", ...options?.headers },
            body: JSON.stringify(directionUpdateState)
        }
    );
};

/**
 * Updates the type ('universal', 'deposit', 'withdraw') for the specified direction
 * @summary Update type for a direction
 */
export type directionEndpointsUpdateTypeEnigmaV1DirectionDirectionIdTypePatchResponse200 = {
    data: ApiResponseDirection;
    status: 200;
};

export type directionEndpointsUpdateTypeEnigmaV1DirectionDirectionIdTypePatchResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type directionEndpointsUpdateTypeEnigmaV1DirectionDirectionIdTypePatchResponseComposite =
    | directionEndpointsUpdateTypeEnigmaV1DirectionDirectionIdTypePatchResponse200
    | directionEndpointsUpdateTypeEnigmaV1DirectionDirectionIdTypePatchResponse422;

export type directionEndpointsUpdateTypeEnigmaV1DirectionDirectionIdTypePatchResponse =
    directionEndpointsUpdateTypeEnigmaV1DirectionDirectionIdTypePatchResponseComposite & {
        headers: Headers;
    };

export const getDirectionEndpointsUpdateTypeEnigmaV1DirectionDirectionIdTypePatchUrl = (directionId: string) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/direction/${directionId}/type`;
};

export const directionEndpointsUpdateTypeEnigmaV1DirectionDirectionIdTypePatch = async (
    directionId: string,
    directionUpdateType: DirectionUpdateType,
    options?: RequestInit
): Promise<directionEndpointsUpdateTypeEnigmaV1DirectionDirectionIdTypePatchResponse> => {
    return authFetch<directionEndpointsUpdateTypeEnigmaV1DirectionDirectionIdTypePatchResponse>(
        getDirectionEndpointsUpdateTypeEnigmaV1DirectionDirectionIdTypePatchUrl(directionId),
        {
            ...options,
            method: "PATCH",
            headers: { "Content-Type": "application/json", ...options?.headers },
            body: JSON.stringify(directionUpdateType)
        }
    );
};

/**
 * Associates a new fee with a specified direction
 * @summary Add a new fee to a direction
 */
export type directionEndpointsAddFeeEnigmaV1DirectionDirectionIdFeePatchResponse200 = {
    data: ApiResponseDirection;
    status: 200;
};

export type directionEndpointsAddFeeEnigmaV1DirectionDirectionIdFeePatchResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type directionEndpointsAddFeeEnigmaV1DirectionDirectionIdFeePatchResponseComposite =
    | directionEndpointsAddFeeEnigmaV1DirectionDirectionIdFeePatchResponse200
    | directionEndpointsAddFeeEnigmaV1DirectionDirectionIdFeePatchResponse422;

export type directionEndpointsAddFeeEnigmaV1DirectionDirectionIdFeePatchResponse =
    directionEndpointsAddFeeEnigmaV1DirectionDirectionIdFeePatchResponseComposite & {
        headers: Headers;
    };

export const getDirectionEndpointsAddFeeEnigmaV1DirectionDirectionIdFeePatchUrl = (directionId: string) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/direction/${directionId}/fee`;
};

export const directionEndpointsAddFeeEnigmaV1DirectionDirectionIdFeePatch = async (
    directionId: string,
    feeCreate: FeeCreate,
    options?: RequestInit
): Promise<directionEndpointsAddFeeEnigmaV1DirectionDirectionIdFeePatchResponse> => {
    return authFetch<directionEndpointsAddFeeEnigmaV1DirectionDirectionIdFeePatchResponse>(
        getDirectionEndpointsAddFeeEnigmaV1DirectionDirectionIdFeePatchUrl(directionId),
        {
            ...options,
            method: "PATCH",
            headers: { "Content-Type": "application/json", ...options?.headers },
            body: JSON.stringify(feeCreate)
        }
    );
};

/**
 * Modifies an existing fee associated with a specified direction
 * @summary Update an existing fee for a direction
 */
export type directionEndpointsUpdateFeeEnigmaV1DirectionDirectionIdFeeFeeIdPatchResponse200 = {
    data: ApiResponseDirection;
    status: 200;
};

export type directionEndpointsUpdateFeeEnigmaV1DirectionDirectionIdFeeFeeIdPatchResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type directionEndpointsUpdateFeeEnigmaV1DirectionDirectionIdFeeFeeIdPatchResponseComposite =
    | directionEndpointsUpdateFeeEnigmaV1DirectionDirectionIdFeeFeeIdPatchResponse200
    | directionEndpointsUpdateFeeEnigmaV1DirectionDirectionIdFeeFeeIdPatchResponse422;

export type directionEndpointsUpdateFeeEnigmaV1DirectionDirectionIdFeeFeeIdPatchResponse =
    directionEndpointsUpdateFeeEnigmaV1DirectionDirectionIdFeeFeeIdPatchResponseComposite & {
        headers: Headers;
    };

export const getDirectionEndpointsUpdateFeeEnigmaV1DirectionDirectionIdFeeFeeIdPatchUrl = (
    directionId: string,
    feeId: string
) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/direction/${directionId}/fee/${feeId}`;
};

export const directionEndpointsUpdateFeeEnigmaV1DirectionDirectionIdFeeFeeIdPatch = async (
    directionId: string,
    feeId: string,
    feeUpdate: FeeUpdate,
    options?: RequestInit
): Promise<directionEndpointsUpdateFeeEnigmaV1DirectionDirectionIdFeeFeeIdPatchResponse> => {
    return authFetch<directionEndpointsUpdateFeeEnigmaV1DirectionDirectionIdFeeFeeIdPatchResponse>(
        getDirectionEndpointsUpdateFeeEnigmaV1DirectionDirectionIdFeeFeeIdPatchUrl(directionId, feeId),
        {
            ...options,
            method: "PATCH",
            headers: { "Content-Type": "application/json", ...options?.headers },
            body: JSON.stringify(feeUpdate)
        }
    );
};

/**
 * Deletes a specific fee associated with a given direction
 * @summary Remove a fee from a direction
 */
export type directionEndpointsDeleteFeeEnigmaV1DirectionDirectionIdFeeFeeIdDeleteResponse200 = {
    data: ApiResponseDirection;
    status: 200;
};

export type directionEndpointsDeleteFeeEnigmaV1DirectionDirectionIdFeeFeeIdDeleteResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type directionEndpointsDeleteFeeEnigmaV1DirectionDirectionIdFeeFeeIdDeleteResponseComposite =
    | directionEndpointsDeleteFeeEnigmaV1DirectionDirectionIdFeeFeeIdDeleteResponse200
    | directionEndpointsDeleteFeeEnigmaV1DirectionDirectionIdFeeFeeIdDeleteResponse422;

export type directionEndpointsDeleteFeeEnigmaV1DirectionDirectionIdFeeFeeIdDeleteResponse =
    directionEndpointsDeleteFeeEnigmaV1DirectionDirectionIdFeeFeeIdDeleteResponseComposite & {
        headers: Headers;
    };

export const getDirectionEndpointsDeleteFeeEnigmaV1DirectionDirectionIdFeeFeeIdDeleteUrl = (
    directionId: string,
    feeId: string
) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/direction/${directionId}/fee/${feeId}`;
};

export const directionEndpointsDeleteFeeEnigmaV1DirectionDirectionIdFeeFeeIdDelete = async (
    directionId: string,
    feeId: string,
    options?: RequestInit
): Promise<directionEndpointsDeleteFeeEnigmaV1DirectionDirectionIdFeeFeeIdDeleteResponse> => {
    return authFetch<directionEndpointsDeleteFeeEnigmaV1DirectionDirectionIdFeeFeeIdDeleteResponse>(
        getDirectionEndpointsDeleteFeeEnigmaV1DirectionDirectionIdFeeFeeIdDeleteUrl(directionId, feeId),
        {
            ...options,
            method: "DELETE"
        }
    );
};

/**
 * Updates all limits (payin, payout, reward) for the specified direction
 * @deprecated
 * @summary Update limits for a direction
 */
export type directionEndpointsUpdateLimitsEnigmaV1DirectionDirectionIdLimitsPatchResponse200 = {
    data: ApiResponseDirection;
    status: 200;
};

export type directionEndpointsUpdateLimitsEnigmaV1DirectionDirectionIdLimitsPatchResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type directionEndpointsUpdateLimitsEnigmaV1DirectionDirectionIdLimitsPatchResponseComposite =
    | directionEndpointsUpdateLimitsEnigmaV1DirectionDirectionIdLimitsPatchResponse200
    | directionEndpointsUpdateLimitsEnigmaV1DirectionDirectionIdLimitsPatchResponse422;

export type directionEndpointsUpdateLimitsEnigmaV1DirectionDirectionIdLimitsPatchResponse =
    directionEndpointsUpdateLimitsEnigmaV1DirectionDirectionIdLimitsPatchResponseComposite & {
        headers: Headers;
    };

export const getDirectionEndpointsUpdateLimitsEnigmaV1DirectionDirectionIdLimitsPatchUrl = (directionId: string) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/direction/${directionId}/limits`;
};

export const directionEndpointsUpdateLimitsEnigmaV1DirectionDirectionIdLimitsPatch = async (
    directionId: string,
    directionUpdateLimits: DirectionUpdateLimits,
    options?: RequestInit
): Promise<directionEndpointsUpdateLimitsEnigmaV1DirectionDirectionIdLimitsPatchResponse> => {
    return authFetch<directionEndpointsUpdateLimitsEnigmaV1DirectionDirectionIdLimitsPatchResponse>(
        getDirectionEndpointsUpdateLimitsEnigmaV1DirectionDirectionIdLimitsPatchUrl(directionId),
        {
            ...options,
            method: "PATCH",
            headers: { "Content-Type": "application/json", ...options?.headers },
            body: JSON.stringify(directionUpdateLimits)
        }
    );
};

/**
 * Resets all limits (payin, payout, reward) by setting quantity to 0 for both min and max
 * @deprecated
 * @summary Delete (reset) limits for a direction
 */
export type directionEndpointsDeleteLimitsEnigmaV1DirectionDirectionIdLimitsDeleteResponse200 = {
    data: ApiResponseDirection;
    status: 200;
};

export type directionEndpointsDeleteLimitsEnigmaV1DirectionDirectionIdLimitsDeleteResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type directionEndpointsDeleteLimitsEnigmaV1DirectionDirectionIdLimitsDeleteResponseComposite =
    | directionEndpointsDeleteLimitsEnigmaV1DirectionDirectionIdLimitsDeleteResponse200
    | directionEndpointsDeleteLimitsEnigmaV1DirectionDirectionIdLimitsDeleteResponse422;

export type directionEndpointsDeleteLimitsEnigmaV1DirectionDirectionIdLimitsDeleteResponse =
    directionEndpointsDeleteLimitsEnigmaV1DirectionDirectionIdLimitsDeleteResponseComposite & {
        headers: Headers;
    };

export const getDirectionEndpointsDeleteLimitsEnigmaV1DirectionDirectionIdLimitsDeleteUrl = (directionId: string) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/direction/${directionId}/limits`;
};

export const directionEndpointsDeleteLimitsEnigmaV1DirectionDirectionIdLimitsDelete = async (
    directionId: string,
    options?: RequestInit
): Promise<directionEndpointsDeleteLimitsEnigmaV1DirectionDirectionIdLimitsDeleteResponse> => {
    return authFetch<directionEndpointsDeleteLimitsEnigmaV1DirectionDirectionIdLimitsDeleteResponse>(
        getDirectionEndpointsDeleteLimitsEnigmaV1DirectionDirectionIdLimitsDeleteUrl(directionId),
        {
            ...options,
            method: "DELETE"
        }
    );
};

/**
 * Returns a list of payment types that are common across the specified merchant, provider, and terminal. If no parameters are provided, all payment types are returned.
 * @summary Get available payment types based on merchant, provider, and terminal
 */
export type directionEndpointsGetAvailablePaymentTypesEnigmaV1DirectionAvailablePaymentTypesGetResponse200 = {
    data: ApiResponseOffsetPaginationPaymentTypeModel;
    status: 200;
};

export type directionEndpointsGetAvailablePaymentTypesEnigmaV1DirectionAvailablePaymentTypesGetResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type directionEndpointsGetAvailablePaymentTypesEnigmaV1DirectionAvailablePaymentTypesGetResponseComposite =
    | directionEndpointsGetAvailablePaymentTypesEnigmaV1DirectionAvailablePaymentTypesGetResponse200
    | directionEndpointsGetAvailablePaymentTypesEnigmaV1DirectionAvailablePaymentTypesGetResponse422;

export type directionEndpointsGetAvailablePaymentTypesEnigmaV1DirectionAvailablePaymentTypesGetResponse =
    directionEndpointsGetAvailablePaymentTypesEnigmaV1DirectionAvailablePaymentTypesGetResponseComposite & {
        headers: Headers;
    };

export const getDirectionEndpointsGetAvailablePaymentTypesEnigmaV1DirectionAvailablePaymentTypesGetUrl = (
    params?: DirectionEndpointsGetAvailablePaymentTypesEnigmaV1DirectionAvailablePaymentTypesGetParams
) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? "null" : value.toString());
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/direction/available_payment_types?${stringifiedParams}`
        : `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/direction/available_payment_types`;
};

export const directionEndpointsGetAvailablePaymentTypesEnigmaV1DirectionAvailablePaymentTypesGet = async (
    params?: DirectionEndpointsGetAvailablePaymentTypesEnigmaV1DirectionAvailablePaymentTypesGetParams,
    options?: RequestInit
): Promise<directionEndpointsGetAvailablePaymentTypesEnigmaV1DirectionAvailablePaymentTypesGetResponse> => {
    return authFetch<directionEndpointsGetAvailablePaymentTypesEnigmaV1DirectionAvailablePaymentTypesGetResponse>(
        getDirectionEndpointsGetAvailablePaymentTypesEnigmaV1DirectionAvailablePaymentTypesGetUrl(params),
        {
            ...options,
            method: "GET"
        }
    );
};

/**
 * Associates existing payment types with a direction. Skips already linked types.
 * @summary Add payment types to direction
 */
export type directionEndpointsAddPaymentTypesToDirectionEnigmaV1DirectionDirectionIdAddPaymentTypesPatchResponse200 = {
    data: ApiResponseDirection;
    status: 200;
};

export type directionEndpointsAddPaymentTypesToDirectionEnigmaV1DirectionDirectionIdAddPaymentTypesPatchResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type directionEndpointsAddPaymentTypesToDirectionEnigmaV1DirectionDirectionIdAddPaymentTypesPatchResponseComposite =

        | directionEndpointsAddPaymentTypesToDirectionEnigmaV1DirectionDirectionIdAddPaymentTypesPatchResponse200
        | directionEndpointsAddPaymentTypesToDirectionEnigmaV1DirectionDirectionIdAddPaymentTypesPatchResponse422;

export type directionEndpointsAddPaymentTypesToDirectionEnigmaV1DirectionDirectionIdAddPaymentTypesPatchResponse =
    directionEndpointsAddPaymentTypesToDirectionEnigmaV1DirectionDirectionIdAddPaymentTypesPatchResponseComposite & {
        headers: Headers;
    };

export const getDirectionEndpointsAddPaymentTypesToDirectionEnigmaV1DirectionDirectionIdAddPaymentTypesPatchUrl = (
    directionId: string
) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/direction/${directionId}/add_payment_types`;
};

export const directionEndpointsAddPaymentTypesToDirectionEnigmaV1DirectionDirectionIdAddPaymentTypesPatch = async (
    directionId: string,
    paymentTypesLink: PaymentTypesLink,
    options?: RequestInit
): Promise<directionEndpointsAddPaymentTypesToDirectionEnigmaV1DirectionDirectionIdAddPaymentTypesPatchResponse> => {
    return authFetch<directionEndpointsAddPaymentTypesToDirectionEnigmaV1DirectionDirectionIdAddPaymentTypesPatchResponse>(
        getDirectionEndpointsAddPaymentTypesToDirectionEnigmaV1DirectionDirectionIdAddPaymentTypesPatchUrl(directionId),
        {
            ...options,
            method: "PATCH",
            headers: { "Content-Type": "application/json", ...options?.headers },
            body: JSON.stringify(paymentTypesLink)
        }
    );
};

/**
 * Automatically associates all available payment types with a direction based on merchant and terminal intersection.
 * @summary Automatically add available payment types to direction
 */
export type directionEndpointsAutoAddPaymentTypesToDirectionEnigmaV1DirectionDirectionIdAutoAddPaymentTypesPatchResponse200 =
    {
        data: ApiResponseDirection;
        status: 200;
    };

export type directionEndpointsAutoAddPaymentTypesToDirectionEnigmaV1DirectionDirectionIdAutoAddPaymentTypesPatchResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type directionEndpointsAutoAddPaymentTypesToDirectionEnigmaV1DirectionDirectionIdAutoAddPaymentTypesPatchResponseComposite =

        | directionEndpointsAutoAddPaymentTypesToDirectionEnigmaV1DirectionDirectionIdAutoAddPaymentTypesPatchResponse200
        | directionEndpointsAutoAddPaymentTypesToDirectionEnigmaV1DirectionDirectionIdAutoAddPaymentTypesPatchResponse422;

export type directionEndpointsAutoAddPaymentTypesToDirectionEnigmaV1DirectionDirectionIdAutoAddPaymentTypesPatchResponse =
    directionEndpointsAutoAddPaymentTypesToDirectionEnigmaV1DirectionDirectionIdAutoAddPaymentTypesPatchResponseComposite & {
        headers: Headers;
    };

export const getDirectionEndpointsAutoAddPaymentTypesToDirectionEnigmaV1DirectionDirectionIdAutoAddPaymentTypesPatchUrl =
    (directionId: string) => {
        return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/direction/${directionId}/auto_add_payment_types`;
    };

export const directionEndpointsAutoAddPaymentTypesToDirectionEnigmaV1DirectionDirectionIdAutoAddPaymentTypesPatch =
    async (
        directionId: string,
        options?: RequestInit
    ): Promise<directionEndpointsAutoAddPaymentTypesToDirectionEnigmaV1DirectionDirectionIdAutoAddPaymentTypesPatchResponse> => {
        return authFetch<directionEndpointsAutoAddPaymentTypesToDirectionEnigmaV1DirectionDirectionIdAutoAddPaymentTypesPatchResponse>(
            getDirectionEndpointsAutoAddPaymentTypesToDirectionEnigmaV1DirectionDirectionIdAutoAddPaymentTypesPatchUrl(
                directionId
            ),
            {
                ...options,
                method: "PATCH"
            }
        );
    };

/**
 * Disassociates a payment type from a direction by its code.
 * @summary Remove payment type from direction
 */
export type directionEndpointsRemovePaymentTypeFromDirectionEnigmaV1DirectionDirectionIdRemovePaymentTypePaymentTypeCodeDeleteResponse200 =
    {
        data: ApiResponseDirection;
        status: 200;
    };

export type directionEndpointsRemovePaymentTypeFromDirectionEnigmaV1DirectionDirectionIdRemovePaymentTypePaymentTypeCodeDeleteResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type directionEndpointsRemovePaymentTypeFromDirectionEnigmaV1DirectionDirectionIdRemovePaymentTypePaymentTypeCodeDeleteResponseComposite =

        | directionEndpointsRemovePaymentTypeFromDirectionEnigmaV1DirectionDirectionIdRemovePaymentTypePaymentTypeCodeDeleteResponse200
        | directionEndpointsRemovePaymentTypeFromDirectionEnigmaV1DirectionDirectionIdRemovePaymentTypePaymentTypeCodeDeleteResponse422;

export type directionEndpointsRemovePaymentTypeFromDirectionEnigmaV1DirectionDirectionIdRemovePaymentTypePaymentTypeCodeDeleteResponse =
    directionEndpointsRemovePaymentTypeFromDirectionEnigmaV1DirectionDirectionIdRemovePaymentTypePaymentTypeCodeDeleteResponseComposite & {
        headers: Headers;
    };

export const getDirectionEndpointsRemovePaymentTypeFromDirectionEnigmaV1DirectionDirectionIdRemovePaymentTypePaymentTypeCodeDeleteUrl =
    (directionId: string, paymentTypeCode: string) => {
        return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/direction/${directionId}/remove_payment_type/${paymentTypeCode}`;
    };

export const directionEndpointsRemovePaymentTypeFromDirectionEnigmaV1DirectionDirectionIdRemovePaymentTypePaymentTypeCodeDelete =
    async (
        directionId: string,
        paymentTypeCode: string,
        options?: RequestInit
    ): Promise<directionEndpointsRemovePaymentTypeFromDirectionEnigmaV1DirectionDirectionIdRemovePaymentTypePaymentTypeCodeDeleteResponse> => {
        return authFetch<directionEndpointsRemovePaymentTypeFromDirectionEnigmaV1DirectionDirectionIdRemovePaymentTypePaymentTypeCodeDeleteResponse>(
            getDirectionEndpointsRemovePaymentTypeFromDirectionEnigmaV1DirectionDirectionIdRemovePaymentTypePaymentTypeCodeDeleteUrl(
                directionId,
                paymentTypeCode
            ),
            {
                ...options,
                method: "DELETE"
            }
        );
    };
