/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * BlowFish - Enigma API Service
 * OpenAPI spec version: develop
 */
import type {
    ApiResponseImportResponse,
    ApiResponseListPaymentCategoryItem,
    ApiResponseListRequiredFieldItem,
    ApiResponseNoneType,
    ApiResponseOffsetPaginationPaymentTypeModel,
    ApiResponsePaymentTypeModel,
    BodyPaymentTypeEndpointsImportPaymentTypesEnigmaV1PaymentTypeImportPost,
    CurrenciesLink,
    HTTPValidationError,
    PaymentTypeCreate,
    PaymentTypeEndpointsExportPaymentTypesEnigmaV1PaymentTypeExportGetParams,
    PaymentTypeEndpointsImportPaymentTypesEnigmaV1PaymentTypeImportPostParams,
    PaymentTypeEndpointsListPaymentTypesEnigmaV1PaymentTypeGetParams,
    PaymentTypeUpdate
} from "../blowFishEnigmaAPIService.schemas";

import { authFetch } from "../../../helpers/orvalAuthFetchMiddleware";

/**
 * Returns a list of payment type categories in a name:value format
 * @summary Retrieve payment type categories
 */
export type paymentTypeEndpointsGetPaymentTypeCategoriesEnigmaV1PaymentTypeCategoriesGetResponse200 = {
    data: ApiResponseListPaymentCategoryItem;
    status: 200;
};

export type paymentTypeEndpointsGetPaymentTypeCategoriesEnigmaV1PaymentTypeCategoriesGetResponseComposite =
    paymentTypeEndpointsGetPaymentTypeCategoriesEnigmaV1PaymentTypeCategoriesGetResponse200;

export type paymentTypeEndpointsGetPaymentTypeCategoriesEnigmaV1PaymentTypeCategoriesGetResponse =
    paymentTypeEndpointsGetPaymentTypeCategoriesEnigmaV1PaymentTypeCategoriesGetResponseComposite & {
        headers: Headers;
    };

export const getPaymentTypeEndpointsGetPaymentTypeCategoriesEnigmaV1PaymentTypeCategoriesGetUrl = () => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/payment_type/categories`;
};

export const paymentTypeEndpointsGetPaymentTypeCategoriesEnigmaV1PaymentTypeCategoriesGet = async (
    options?: RequestInit
): Promise<paymentTypeEndpointsGetPaymentTypeCategoriesEnigmaV1PaymentTypeCategoriesGetResponse> => {
    return authFetch<paymentTypeEndpointsGetPaymentTypeCategoriesEnigmaV1PaymentTypeCategoriesGetResponse>(
        getPaymentTypeEndpointsGetPaymentTypeCategoriesEnigmaV1PaymentTypeCategoriesGetUrl(),
        {
            ...options,
            method: "GET"
        }
    );
};

/**
 * Returns a list of all available field names that can be used in required_fields_for_payment. These fields correspond to the Requisites model fields.
 * @summary Retrieve available required fields for payment
 */
export type paymentTypeEndpointsGetRequiredFieldsEnigmaV1PaymentTypeRequiredFieldsGetResponse200 = {
    data: ApiResponseListRequiredFieldItem;
    status: 200;
};

export type paymentTypeEndpointsGetRequiredFieldsEnigmaV1PaymentTypeRequiredFieldsGetResponseComposite =
    paymentTypeEndpointsGetRequiredFieldsEnigmaV1PaymentTypeRequiredFieldsGetResponse200;

export type paymentTypeEndpointsGetRequiredFieldsEnigmaV1PaymentTypeRequiredFieldsGetResponse =
    paymentTypeEndpointsGetRequiredFieldsEnigmaV1PaymentTypeRequiredFieldsGetResponseComposite & {
        headers: Headers;
    };

export const getPaymentTypeEndpointsGetRequiredFieldsEnigmaV1PaymentTypeRequiredFieldsGetUrl = () => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/payment_type/required-fields`;
};

export const paymentTypeEndpointsGetRequiredFieldsEnigmaV1PaymentTypeRequiredFieldsGet = async (
    options?: RequestInit
): Promise<paymentTypeEndpointsGetRequiredFieldsEnigmaV1PaymentTypeRequiredFieldsGetResponse> => {
    return authFetch<paymentTypeEndpointsGetRequiredFieldsEnigmaV1PaymentTypeRequiredFieldsGetResponse>(
        getPaymentTypeEndpointsGetRequiredFieldsEnigmaV1PaymentTypeRequiredFieldsGetUrl(),
        {
            ...options,
            method: "GET"
        }
    );
};

/**
 * Returns a paginated list of available payment types. Supports filtering based on query parameters
 * @summary Get a list of payment types with filtering and pagination
 */
export type paymentTypeEndpointsListPaymentTypesEnigmaV1PaymentTypeGetResponse200 = {
    data: ApiResponseOffsetPaginationPaymentTypeModel;
    status: 200;
};

export type paymentTypeEndpointsListPaymentTypesEnigmaV1PaymentTypeGetResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type paymentTypeEndpointsListPaymentTypesEnigmaV1PaymentTypeGetResponseComposite =
    | paymentTypeEndpointsListPaymentTypesEnigmaV1PaymentTypeGetResponse200
    | paymentTypeEndpointsListPaymentTypesEnigmaV1PaymentTypeGetResponse422;

export type paymentTypeEndpointsListPaymentTypesEnigmaV1PaymentTypeGetResponse =
    paymentTypeEndpointsListPaymentTypesEnigmaV1PaymentTypeGetResponseComposite & {
        headers: Headers;
    };

export const getPaymentTypeEndpointsListPaymentTypesEnigmaV1PaymentTypeGetUrl = (
    params?: PaymentTypeEndpointsListPaymentTypesEnigmaV1PaymentTypeGetParams
) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? "null" : value.toString());
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/payment_type?${stringifiedParams}`
        : `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/payment_type`;
};

export const paymentTypeEndpointsListPaymentTypesEnigmaV1PaymentTypeGet = async (
    params?: PaymentTypeEndpointsListPaymentTypesEnigmaV1PaymentTypeGetParams,
    options?: RequestInit
): Promise<paymentTypeEndpointsListPaymentTypesEnigmaV1PaymentTypeGetResponse> => {
    return authFetch<paymentTypeEndpointsListPaymentTypesEnigmaV1PaymentTypeGetResponse>(
        getPaymentTypeEndpointsListPaymentTypesEnigmaV1PaymentTypeGetUrl(params),
        {
            ...options,
            method: "GET"
        }
    );
};

/**
 * Adds a new payment type to the database using the provided details
 * @summary Create a new payment type entry
 */
export type paymentTypeEndpointsCreatePaymentTypeEnigmaV1PaymentTypePostResponse200 = {
    data: ApiResponsePaymentTypeModel;
    status: 200;
};

export type paymentTypeEndpointsCreatePaymentTypeEnigmaV1PaymentTypePostResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type paymentTypeEndpointsCreatePaymentTypeEnigmaV1PaymentTypePostResponseComposite =
    | paymentTypeEndpointsCreatePaymentTypeEnigmaV1PaymentTypePostResponse200
    | paymentTypeEndpointsCreatePaymentTypeEnigmaV1PaymentTypePostResponse422;

export type paymentTypeEndpointsCreatePaymentTypeEnigmaV1PaymentTypePostResponse =
    paymentTypeEndpointsCreatePaymentTypeEnigmaV1PaymentTypePostResponseComposite & {
        headers: Headers;
    };

export const getPaymentTypeEndpointsCreatePaymentTypeEnigmaV1PaymentTypePostUrl = () => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/payment_type`;
};

export const paymentTypeEndpointsCreatePaymentTypeEnigmaV1PaymentTypePost = async (
    paymentTypeCreate: PaymentTypeCreate,
    options?: RequestInit
): Promise<paymentTypeEndpointsCreatePaymentTypeEnigmaV1PaymentTypePostResponse> => {
    return authFetch<paymentTypeEndpointsCreatePaymentTypeEnigmaV1PaymentTypePostResponse>(
        getPaymentTypeEndpointsCreatePaymentTypeEnigmaV1PaymentTypePostUrl(),
        {
            ...options,
            method: "POST",
            headers: { "Content-Type": "application/json", ...options?.headers },
            body: JSON.stringify(paymentTypeCreate)
        }
    );
};

/**
 * Exports payment types to a CSV file and download it
 * @summary Export payment types to CSV
 */
export type paymentTypeEndpointsExportPaymentTypesEnigmaV1PaymentTypeExportGetResponse200 = {
    data: unknown;
    status: 200;
};

export type paymentTypeEndpointsExportPaymentTypesEnigmaV1PaymentTypeExportGetResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type paymentTypeEndpointsExportPaymentTypesEnigmaV1PaymentTypeExportGetResponseComposite =
    | paymentTypeEndpointsExportPaymentTypesEnigmaV1PaymentTypeExportGetResponse200
    | paymentTypeEndpointsExportPaymentTypesEnigmaV1PaymentTypeExportGetResponse422;

export type paymentTypeEndpointsExportPaymentTypesEnigmaV1PaymentTypeExportGetResponse =
    paymentTypeEndpointsExportPaymentTypesEnigmaV1PaymentTypeExportGetResponseComposite & {
        headers: Headers;
    };

export const getPaymentTypeEndpointsExportPaymentTypesEnigmaV1PaymentTypeExportGetUrl = (
    params?: PaymentTypeEndpointsExportPaymentTypesEnigmaV1PaymentTypeExportGetParams
) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? "null" : value.toString());
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/payment_type/export?${stringifiedParams}`
        : `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/payment_type/export`;
};

export const paymentTypeEndpointsExportPaymentTypesEnigmaV1PaymentTypeExportGet = async (
    params?: PaymentTypeEndpointsExportPaymentTypesEnigmaV1PaymentTypeExportGetParams,
    options?: RequestInit
): Promise<paymentTypeEndpointsExportPaymentTypesEnigmaV1PaymentTypeExportGetResponse> => {
    return authFetch<paymentTypeEndpointsExportPaymentTypesEnigmaV1PaymentTypeExportGetResponse>(
        getPaymentTypeEndpointsExportPaymentTypesEnigmaV1PaymentTypeExportGetUrl(params),
        {
            ...options,
            method: "GET"
        }
    );
};

/**
 * Import payment types from a CSV file
 * @summary Imports payment types records from a CSV file.
 */
export type paymentTypeEndpointsImportPaymentTypesEnigmaV1PaymentTypeImportPostResponse200 = {
    data: ApiResponseImportResponse;
    status: 200;
};

export type paymentTypeEndpointsImportPaymentTypesEnigmaV1PaymentTypeImportPostResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type paymentTypeEndpointsImportPaymentTypesEnigmaV1PaymentTypeImportPostResponseComposite =
    | paymentTypeEndpointsImportPaymentTypesEnigmaV1PaymentTypeImportPostResponse200
    | paymentTypeEndpointsImportPaymentTypesEnigmaV1PaymentTypeImportPostResponse422;

export type paymentTypeEndpointsImportPaymentTypesEnigmaV1PaymentTypeImportPostResponse =
    paymentTypeEndpointsImportPaymentTypesEnigmaV1PaymentTypeImportPostResponseComposite & {
        headers: Headers;
    };

export const getPaymentTypeEndpointsImportPaymentTypesEnigmaV1PaymentTypeImportPostUrl = (
    params?: PaymentTypeEndpointsImportPaymentTypesEnigmaV1PaymentTypeImportPostParams
) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? "null" : value.toString());
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/payment_type/import?${stringifiedParams}`
        : `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/payment_type/import`;
};

export const paymentTypeEndpointsImportPaymentTypesEnigmaV1PaymentTypeImportPost = async (
    bodyPaymentTypeEndpointsImportPaymentTypesEnigmaV1PaymentTypeImportPost: BodyPaymentTypeEndpointsImportPaymentTypesEnigmaV1PaymentTypeImportPost,
    params?: PaymentTypeEndpointsImportPaymentTypesEnigmaV1PaymentTypeImportPostParams,
    options?: RequestInit
): Promise<paymentTypeEndpointsImportPaymentTypesEnigmaV1PaymentTypeImportPostResponse> => {
    const formData = new FormData();
    formData.append("csv_file", bodyPaymentTypeEndpointsImportPaymentTypesEnigmaV1PaymentTypeImportPost.csv_file);

    return authFetch<paymentTypeEndpointsImportPaymentTypesEnigmaV1PaymentTypeImportPostResponse>(
        getPaymentTypeEndpointsImportPaymentTypesEnigmaV1PaymentTypeImportPostUrl(params),
        {
            ...options,
            method: "POST",
            body: formData
        }
    );
};

/**
 * Fetches details of a payment type identified by its unique ID
 * @summary Get details of a specific payment type
 */
export type paymentTypeEndpointsGetPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeGetResponse200 = {
    data: ApiResponsePaymentTypeModel;
    status: 200;
};

export type paymentTypeEndpointsGetPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeGetResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type paymentTypeEndpointsGetPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeGetResponseComposite =
    | paymentTypeEndpointsGetPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeGetResponse200
    | paymentTypeEndpointsGetPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeGetResponse422;

export type paymentTypeEndpointsGetPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeGetResponse =
    paymentTypeEndpointsGetPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeGetResponseComposite & {
        headers: Headers;
    };

export const getPaymentTypeEndpointsGetPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeGetUrl = (
    paymentTypeCode: string
) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/payment_type/${paymentTypeCode}`;
};

export const paymentTypeEndpointsGetPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeGet = async (
    paymentTypeCode: string,
    options?: RequestInit
): Promise<paymentTypeEndpointsGetPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeGetResponse> => {
    return authFetch<paymentTypeEndpointsGetPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeGetResponse>(
        getPaymentTypeEndpointsGetPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeGetUrl(paymentTypeCode),
        {
            ...options,
            method: "GET"
        }
    );
};

/**
 * Modifies the details of a payment type identified by its unique ID
 * @summary Update an existing payment type
 */
export type paymentTypeEndpointsUpdatePaymentTypeEnigmaV1PaymentTypePaymentTypeCodePutResponse200 = {
    data: ApiResponsePaymentTypeModel;
    status: 200;
};

export type paymentTypeEndpointsUpdatePaymentTypeEnigmaV1PaymentTypePaymentTypeCodePutResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type paymentTypeEndpointsUpdatePaymentTypeEnigmaV1PaymentTypePaymentTypeCodePutResponseComposite =
    | paymentTypeEndpointsUpdatePaymentTypeEnigmaV1PaymentTypePaymentTypeCodePutResponse200
    | paymentTypeEndpointsUpdatePaymentTypeEnigmaV1PaymentTypePaymentTypeCodePutResponse422;

export type paymentTypeEndpointsUpdatePaymentTypeEnigmaV1PaymentTypePaymentTypeCodePutResponse =
    paymentTypeEndpointsUpdatePaymentTypeEnigmaV1PaymentTypePaymentTypeCodePutResponseComposite & {
        headers: Headers;
    };

export const getPaymentTypeEndpointsUpdatePaymentTypeEnigmaV1PaymentTypePaymentTypeCodePutUrl = (
    paymentTypeCode: string
) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/payment_type/${paymentTypeCode}`;
};

export const paymentTypeEndpointsUpdatePaymentTypeEnigmaV1PaymentTypePaymentTypeCodePut = async (
    paymentTypeCode: string,
    paymentTypeUpdate: PaymentTypeUpdate,
    options?: RequestInit
): Promise<paymentTypeEndpointsUpdatePaymentTypeEnigmaV1PaymentTypePaymentTypeCodePutResponse> => {
    return authFetch<paymentTypeEndpointsUpdatePaymentTypeEnigmaV1PaymentTypePaymentTypeCodePutResponse>(
        getPaymentTypeEndpointsUpdatePaymentTypeEnigmaV1PaymentTypePaymentTypeCodePutUrl(paymentTypeCode),
        {
            ...options,
            method: "PUT",
            headers: { "Content-Type": "application/json", ...options?.headers },
            body: JSON.stringify(paymentTypeUpdate)
        }
    );
};

/**
 * Removes a payment type from the database using its unique ID
 * @summary Delete a payment type entry
 */
export type paymentTypeEndpointsDeletePaymentTypeEnigmaV1PaymentTypePaymentTypeCodeDeleteResponse200 = {
    data: ApiResponseNoneType;
    status: 200;
};

export type paymentTypeEndpointsDeletePaymentTypeEnigmaV1PaymentTypePaymentTypeCodeDeleteResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type paymentTypeEndpointsDeletePaymentTypeEnigmaV1PaymentTypePaymentTypeCodeDeleteResponseComposite =
    | paymentTypeEndpointsDeletePaymentTypeEnigmaV1PaymentTypePaymentTypeCodeDeleteResponse200
    | paymentTypeEndpointsDeletePaymentTypeEnigmaV1PaymentTypePaymentTypeCodeDeleteResponse422;

export type paymentTypeEndpointsDeletePaymentTypeEnigmaV1PaymentTypePaymentTypeCodeDeleteResponse =
    paymentTypeEndpointsDeletePaymentTypeEnigmaV1PaymentTypePaymentTypeCodeDeleteResponseComposite & {
        headers: Headers;
    };

export const getPaymentTypeEndpointsDeletePaymentTypeEnigmaV1PaymentTypePaymentTypeCodeDeleteUrl = (
    paymentTypeCode: string
) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/payment_type/${paymentTypeCode}`;
};

export const paymentTypeEndpointsDeletePaymentTypeEnigmaV1PaymentTypePaymentTypeCodeDelete = async (
    paymentTypeCode: string,
    options?: RequestInit
): Promise<paymentTypeEndpointsDeletePaymentTypeEnigmaV1PaymentTypePaymentTypeCodeDeleteResponse> => {
    return authFetch<paymentTypeEndpointsDeletePaymentTypeEnigmaV1PaymentTypePaymentTypeCodeDeleteResponse>(
        getPaymentTypeEndpointsDeletePaymentTypeEnigmaV1PaymentTypePaymentTypeCodeDeleteUrl(paymentTypeCode),
        {
            ...options,
            method: "DELETE"
        }
    );
};

/**
 * Associates existing currencies with a payment type. Skips already linked currencies.
 * @summary Add currencies to payment type
 */
export type paymentTypeEndpointsAddCurrenciesToPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeAddCurrenciesPatchResponse200 =
    {
        data: ApiResponsePaymentTypeModel;
        status: 200;
    };

export type paymentTypeEndpointsAddCurrenciesToPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeAddCurrenciesPatchResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type paymentTypeEndpointsAddCurrenciesToPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeAddCurrenciesPatchResponseComposite =

        | paymentTypeEndpointsAddCurrenciesToPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeAddCurrenciesPatchResponse200
        | paymentTypeEndpointsAddCurrenciesToPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeAddCurrenciesPatchResponse422;

export type paymentTypeEndpointsAddCurrenciesToPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeAddCurrenciesPatchResponse =
    paymentTypeEndpointsAddCurrenciesToPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeAddCurrenciesPatchResponseComposite & {
        headers: Headers;
    };

export const getPaymentTypeEndpointsAddCurrenciesToPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeAddCurrenciesPatchUrl =
    (paymentTypeCode: string) => {
        return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/payment_type/${paymentTypeCode}/add_currencies`;
    };

export const paymentTypeEndpointsAddCurrenciesToPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeAddCurrenciesPatch =
    async (
        paymentTypeCode: string,
        currenciesLink: CurrenciesLink,
        options?: RequestInit
    ): Promise<paymentTypeEndpointsAddCurrenciesToPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeAddCurrenciesPatchResponse> => {
        return authFetch<paymentTypeEndpointsAddCurrenciesToPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeAddCurrenciesPatchResponse>(
            getPaymentTypeEndpointsAddCurrenciesToPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeAddCurrenciesPatchUrl(
                paymentTypeCode
            ),
            {
                ...options,
                method: "PATCH",
                headers: { "Content-Type": "application/json", ...options?.headers },
                body: JSON.stringify(currenciesLink)
            }
        );
    };

/**
 * Disassociates a currency from a payment type by its code.
 * @summary Remove currency from payment type
 */
export type paymentTypeEndpointsRemoveCurrencyFromPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeRemoveCurrencyCurrencyCodeDeleteResponse200 =
    {
        data: ApiResponsePaymentTypeModel;
        status: 200;
    };

export type paymentTypeEndpointsRemoveCurrencyFromPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeRemoveCurrencyCurrencyCodeDeleteResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type paymentTypeEndpointsRemoveCurrencyFromPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeRemoveCurrencyCurrencyCodeDeleteResponseComposite =

        | paymentTypeEndpointsRemoveCurrencyFromPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeRemoveCurrencyCurrencyCodeDeleteResponse200
        | paymentTypeEndpointsRemoveCurrencyFromPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeRemoveCurrencyCurrencyCodeDeleteResponse422;

export type paymentTypeEndpointsRemoveCurrencyFromPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeRemoveCurrencyCurrencyCodeDeleteResponse =
    paymentTypeEndpointsRemoveCurrencyFromPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeRemoveCurrencyCurrencyCodeDeleteResponseComposite & {
        headers: Headers;
    };

export const getPaymentTypeEndpointsRemoveCurrencyFromPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeRemoveCurrencyCurrencyCodeDeleteUrl =
    (paymentTypeCode: string, currencyCode: string) => {
        return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/payment_type/${paymentTypeCode}/remove_currency/${currencyCode}`;
    };

export const paymentTypeEndpointsRemoveCurrencyFromPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeRemoveCurrencyCurrencyCodeDelete =
    async (
        paymentTypeCode: string,
        currencyCode: string,
        options?: RequestInit
    ): Promise<paymentTypeEndpointsRemoveCurrencyFromPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeRemoveCurrencyCurrencyCodeDeleteResponse> => {
        return authFetch<paymentTypeEndpointsRemoveCurrencyFromPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeRemoveCurrencyCurrencyCodeDeleteResponse>(
            getPaymentTypeEndpointsRemoveCurrencyFromPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeRemoveCurrencyCurrencyCodeDeleteUrl(
                paymentTypeCode,
                currencyCode
            ),
            {
                ...options,
                method: "DELETE"
            }
        );
    };
