/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * BlowFish - Enigma API Service
 * OpenAPI spec version: develop
 */
import type {
    ApiResponseNoneType,
    ApiResponseOffsetPaginationPaymentTypeRead,
    ApiResponsePaymentTypeRead,
    HTTPValidationError,
    PaymentTypeCreate,
    PaymentTypeEndpointsListPaymentTypesEnigmaV1PaymentTypeGetParams,
    PaymentTypeUpdate
} from "../blowFishEnigmaAPIService.schemas";

import { authFetch } from "../../../helpers/orvalAuthFetchMiddleware";

/**
 * Returns a paginated list of available payment types. Supports filtering based on query parameters
 * @summary Get a list of payment types with filtering and pagination
 */
export type paymentTypeEndpointsListPaymentTypesEnigmaV1PaymentTypeGetResponse200 = {
    data: ApiResponseOffsetPaginationPaymentTypeRead;
    status: 200;
};

export type paymentTypeEndpointsListPaymentTypesEnigmaV1PaymentTypeGetResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type paymentTypeEndpointsListPaymentTypesEnigmaV1PaymentTypeGetResponseComposite =
    | paymentTypeEndpointsListPaymentTypesEnigmaV1PaymentTypeGetResponse200
    | paymentTypeEndpointsListPaymentTypesEnigmaV1PaymentTypeGetResponse422;

export type paymentTypeEndpointsListPaymentTypesEnigmaV1PaymentTypeGetResponse =
    paymentTypeEndpointsListPaymentTypesEnigmaV1PaymentTypeGetResponseComposite & {
        headers: Headers;
    };

export const getPaymentTypeEndpointsListPaymentTypesEnigmaV1PaymentTypeGetUrl = (
    params?: PaymentTypeEndpointsListPaymentTypesEnigmaV1PaymentTypeGetParams
) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? "null" : value.toString());
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/payment_type?${stringifiedParams}`
        : `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/payment_type`;
};

export const paymentTypeEndpointsListPaymentTypesEnigmaV1PaymentTypeGet = async (
    params?: PaymentTypeEndpointsListPaymentTypesEnigmaV1PaymentTypeGetParams,
    options?: RequestInit
): Promise<paymentTypeEndpointsListPaymentTypesEnigmaV1PaymentTypeGetResponse> => {
    return authFetch<paymentTypeEndpointsListPaymentTypesEnigmaV1PaymentTypeGetResponse>(
        getPaymentTypeEndpointsListPaymentTypesEnigmaV1PaymentTypeGetUrl(params),
        {
            ...options,
            method: "GET"
        }
    );
};

/**
 * Adds a new payment type to the database using the provided details
 * @summary Create a new payment type entry
 */
export type paymentTypeEndpointsCreatePaymentTypeEnigmaV1PaymentTypePostResponse200 = {
    data: ApiResponsePaymentTypeRead;
    status: 200;
};

export type paymentTypeEndpointsCreatePaymentTypeEnigmaV1PaymentTypePostResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type paymentTypeEndpointsCreatePaymentTypeEnigmaV1PaymentTypePostResponseComposite =
    | paymentTypeEndpointsCreatePaymentTypeEnigmaV1PaymentTypePostResponse200
    | paymentTypeEndpointsCreatePaymentTypeEnigmaV1PaymentTypePostResponse422;

export type paymentTypeEndpointsCreatePaymentTypeEnigmaV1PaymentTypePostResponse =
    paymentTypeEndpointsCreatePaymentTypeEnigmaV1PaymentTypePostResponseComposite & {
        headers: Headers;
    };

export const getPaymentTypeEndpointsCreatePaymentTypeEnigmaV1PaymentTypePostUrl = () => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/payment_type`;
};

export const paymentTypeEndpointsCreatePaymentTypeEnigmaV1PaymentTypePost = async (
    paymentTypeCreate: PaymentTypeCreate,
    options?: RequestInit
): Promise<paymentTypeEndpointsCreatePaymentTypeEnigmaV1PaymentTypePostResponse> => {
    return authFetch<paymentTypeEndpointsCreatePaymentTypeEnigmaV1PaymentTypePostResponse>(
        getPaymentTypeEndpointsCreatePaymentTypeEnigmaV1PaymentTypePostUrl(),
        {
            ...options,
            method: "POST",
            headers: { "Content-Type": "application/json", ...options?.headers },
            body: JSON.stringify(paymentTypeCreate)
        }
    );
};

/**
 * Fetches details of a payment type identified by its unique ID
 * @summary Get details of a specific payment type
 */
export type paymentTypeEndpointsGetPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeGetResponse200 = {
    data: ApiResponsePaymentTypeRead;
    status: 200;
};

export type paymentTypeEndpointsGetPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeGetResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type paymentTypeEndpointsGetPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeGetResponseComposite =
    | paymentTypeEndpointsGetPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeGetResponse200
    | paymentTypeEndpointsGetPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeGetResponse422;

export type paymentTypeEndpointsGetPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeGetResponse =
    paymentTypeEndpointsGetPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeGetResponseComposite & {
        headers: Headers;
    };

export const getPaymentTypeEndpointsGetPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeGetUrl = (
    paymentTypeCode: string
) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/payment_type/${paymentTypeCode}`;
};

export const paymentTypeEndpointsGetPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeGet = async (
    paymentTypeCode: string,
    options?: RequestInit
): Promise<paymentTypeEndpointsGetPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeGetResponse> => {
    return authFetch<paymentTypeEndpointsGetPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeGetResponse>(
        getPaymentTypeEndpointsGetPaymentTypeEnigmaV1PaymentTypePaymentTypeCodeGetUrl(paymentTypeCode),
        {
            ...options,
            method: "GET"
        }
    );
};

/**
 * Modifies the details of a payment type identified by its unique ID
 * @summary Update an existing payment type
 */
export type paymentTypeEndpointsUpdatePaymentTypeEnigmaV1PaymentTypePaymentTypeCodePutResponse200 = {
    data: ApiResponsePaymentTypeRead;
    status: 200;
};

export type paymentTypeEndpointsUpdatePaymentTypeEnigmaV1PaymentTypePaymentTypeCodePutResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type paymentTypeEndpointsUpdatePaymentTypeEnigmaV1PaymentTypePaymentTypeCodePutResponseComposite =
    | paymentTypeEndpointsUpdatePaymentTypeEnigmaV1PaymentTypePaymentTypeCodePutResponse200
    | paymentTypeEndpointsUpdatePaymentTypeEnigmaV1PaymentTypePaymentTypeCodePutResponse422;

export type paymentTypeEndpointsUpdatePaymentTypeEnigmaV1PaymentTypePaymentTypeCodePutResponse =
    paymentTypeEndpointsUpdatePaymentTypeEnigmaV1PaymentTypePaymentTypeCodePutResponseComposite & {
        headers: Headers;
    };

export const getPaymentTypeEndpointsUpdatePaymentTypeEnigmaV1PaymentTypePaymentTypeCodePutUrl = (
    paymentTypeCode: string
) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/payment_type/${paymentTypeCode}`;
};

export const paymentTypeEndpointsUpdatePaymentTypeEnigmaV1PaymentTypePaymentTypeCodePut = async (
    paymentTypeCode: string,
    paymentTypeUpdate: PaymentTypeUpdate,
    options?: RequestInit
): Promise<paymentTypeEndpointsUpdatePaymentTypeEnigmaV1PaymentTypePaymentTypeCodePutResponse> => {
    return authFetch<paymentTypeEndpointsUpdatePaymentTypeEnigmaV1PaymentTypePaymentTypeCodePutResponse>(
        getPaymentTypeEndpointsUpdatePaymentTypeEnigmaV1PaymentTypePaymentTypeCodePutUrl(paymentTypeCode),
        {
            ...options,
            method: "PUT",
            headers: { "Content-Type": "application/json", ...options?.headers },
            body: JSON.stringify(paymentTypeUpdate)
        }
    );
};

/**
 * Removes a payment type from the database using its unique ID
 * @summary Delete a payment type entry
 */
export type paymentTypeEndpointsDeletePaymentTypeEnigmaV1PaymentTypePaymentTypeCodeDeleteResponse200 = {
    data: ApiResponseNoneType;
    status: 200;
};

export type paymentTypeEndpointsDeletePaymentTypeEnigmaV1PaymentTypePaymentTypeCodeDeleteResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type paymentTypeEndpointsDeletePaymentTypeEnigmaV1PaymentTypePaymentTypeCodeDeleteResponseComposite =
    | paymentTypeEndpointsDeletePaymentTypeEnigmaV1PaymentTypePaymentTypeCodeDeleteResponse200
    | paymentTypeEndpointsDeletePaymentTypeEnigmaV1PaymentTypePaymentTypeCodeDeleteResponse422;

export type paymentTypeEndpointsDeletePaymentTypeEnigmaV1PaymentTypePaymentTypeCodeDeleteResponse =
    paymentTypeEndpointsDeletePaymentTypeEnigmaV1PaymentTypePaymentTypeCodeDeleteResponseComposite & {
        headers: Headers;
    };

export const getPaymentTypeEndpointsDeletePaymentTypeEnigmaV1PaymentTypePaymentTypeCodeDeleteUrl = (
    paymentTypeCode: string
) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/payment_type/${paymentTypeCode}`;
};

export const paymentTypeEndpointsDeletePaymentTypeEnigmaV1PaymentTypePaymentTypeCodeDelete = async (
    paymentTypeCode: string,
    options?: RequestInit
): Promise<paymentTypeEndpointsDeletePaymentTypeEnigmaV1PaymentTypePaymentTypeCodeDeleteResponse> => {
    return authFetch<paymentTypeEndpointsDeletePaymentTypeEnigmaV1PaymentTypePaymentTypeCodeDeleteResponse>(
        getPaymentTypeEndpointsDeletePaymentTypeEnigmaV1PaymentTypePaymentTypeCodeDeleteUrl(paymentTypeCode),
        {
            ...options,
            method: "DELETE"
        }
    );
};
