/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * BlowFish - Enigma API Service
 * OpenAPI spec version: local
 */
import type {
    ApiResponseCascadeTerminalSchema,
    ApiResponseDictStrStr,
    ApiResponseOffsetPaginationCascadeTerminalSchema,
    CascadeTerminalCreate,
<<<<<<< HEAD
=======
    CascadeTerminalEndpointsListCascadeTerminalsEnigmaV1CascadeTerminalGetParams,
>>>>>>> INT-89
    CascadeTerminalUpdate,
    HTTPValidationError
} from "../blowFishEnigmaAPIService.schemas";

import { authFetch } from "../../../helpers/orvalAuthFetchMiddleware";

/**
 * Returns all cascades that include a specific terminal
 * @summary Get cascades for terminal
 */
export type cascadeTerminalEndpointsListCascadeTerminalsEnigmaV1CascadeTerminalGetResponse200 = {
    data: ApiResponseOffsetPaginationCascadeTerminalSchema;
    status: 200;
};

<<<<<<< HEAD
export type cascadeTerminalEndpointsListCascadeTerminalsEnigmaV1CascadeTerminalGetResponseComposite =
    cascadeTerminalEndpointsListCascadeTerminalsEnigmaV1CascadeTerminalGetResponse200;
=======
export type cascadeTerminalEndpointsListCascadeTerminalsEnigmaV1CascadeTerminalGetResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type cascadeTerminalEndpointsListCascadeTerminalsEnigmaV1CascadeTerminalGetResponseComposite =
    | cascadeTerminalEndpointsListCascadeTerminalsEnigmaV1CascadeTerminalGetResponse200
    | cascadeTerminalEndpointsListCascadeTerminalsEnigmaV1CascadeTerminalGetResponse422;
>>>>>>> INT-89

export type cascadeTerminalEndpointsListCascadeTerminalsEnigmaV1CascadeTerminalGetResponse =
    cascadeTerminalEndpointsListCascadeTerminalsEnigmaV1CascadeTerminalGetResponseComposite & {
        headers: Headers;
    };

<<<<<<< HEAD
export const getCascadeTerminalEndpointsListCascadeTerminalsEnigmaV1CascadeTerminalGetUrl = () => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/cascade_terminal`;
};

export const cascadeTerminalEndpointsListCascadeTerminalsEnigmaV1CascadeTerminalGet = async (
    options?: RequestInit
): Promise<cascadeTerminalEndpointsListCascadeTerminalsEnigmaV1CascadeTerminalGetResponse> => {
    return authFetch<cascadeTerminalEndpointsListCascadeTerminalsEnigmaV1CascadeTerminalGetResponse>(
        getCascadeTerminalEndpointsListCascadeTerminalsEnigmaV1CascadeTerminalGetUrl(),
=======
export const getCascadeTerminalEndpointsListCascadeTerminalsEnigmaV1CascadeTerminalGetUrl = (
    params?: CascadeTerminalEndpointsListCascadeTerminalsEnigmaV1CascadeTerminalGetParams
) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? "null" : value.toString());
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/cascade_terminal?${stringifiedParams}`
        : `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/cascade_terminal`;
};

export const cascadeTerminalEndpointsListCascadeTerminalsEnigmaV1CascadeTerminalGet = async (
    params?: CascadeTerminalEndpointsListCascadeTerminalsEnigmaV1CascadeTerminalGetParams,
    options?: RequestInit
): Promise<cascadeTerminalEndpointsListCascadeTerminalsEnigmaV1CascadeTerminalGetResponse> => {
    return authFetch<cascadeTerminalEndpointsListCascadeTerminalsEnigmaV1CascadeTerminalGetResponse>(
        getCascadeTerminalEndpointsListCascadeTerminalsEnigmaV1CascadeTerminalGetUrl(params),
>>>>>>> INT-89
        {
            ...options,
            method: "GET"
        }
    );
};

/**
 * Adds a terminal to a cascade with specified conditions
 * @summary Add terminal to cascade
 */
export type cascadeTerminalEndpointsCreateCascadeTerminalEnigmaV1CascadeTerminalPostResponse200 = {
    data: ApiResponseCascadeTerminalSchema;
    status: 200;
};

export type cascadeTerminalEndpointsCreateCascadeTerminalEnigmaV1CascadeTerminalPostResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type cascadeTerminalEndpointsCreateCascadeTerminalEnigmaV1CascadeTerminalPostResponseComposite =
    | cascadeTerminalEndpointsCreateCascadeTerminalEnigmaV1CascadeTerminalPostResponse200
    | cascadeTerminalEndpointsCreateCascadeTerminalEnigmaV1CascadeTerminalPostResponse422;

export type cascadeTerminalEndpointsCreateCascadeTerminalEnigmaV1CascadeTerminalPostResponse =
    cascadeTerminalEndpointsCreateCascadeTerminalEnigmaV1CascadeTerminalPostResponseComposite & {
        headers: Headers;
    };

export const getCascadeTerminalEndpointsCreateCascadeTerminalEnigmaV1CascadeTerminalPostUrl = () => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/cascade_terminal`;
};

export const cascadeTerminalEndpointsCreateCascadeTerminalEnigmaV1CascadeTerminalPost = async (
    cascadeTerminalCreate: CascadeTerminalCreate,
    options?: RequestInit
): Promise<cascadeTerminalEndpointsCreateCascadeTerminalEnigmaV1CascadeTerminalPostResponse> => {
    return authFetch<cascadeTerminalEndpointsCreateCascadeTerminalEnigmaV1CascadeTerminalPostResponse>(
        getCascadeTerminalEndpointsCreateCascadeTerminalEnigmaV1CascadeTerminalPostUrl(),
        {
            ...options,
            method: "POST",
            headers: { "Content-Type": "application/json", ...options?.headers },
            body: JSON.stringify(cascadeTerminalCreate)
        }
    );
};

/**
 * Fetches details of a cascade terminal by its ID
 * @summary Get cascade terminal details
 */
export type cascadeTerminalEndpointsGetCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdGetResponse200 = {
    data: ApiResponseCascadeTerminalSchema;
    status: 200;
};

export type cascadeTerminalEndpointsGetCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdGetResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type cascadeTerminalEndpointsGetCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdGetResponseComposite =
    | cascadeTerminalEndpointsGetCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdGetResponse200
    | cascadeTerminalEndpointsGetCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdGetResponse422;

export type cascadeTerminalEndpointsGetCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdGetResponse =
    cascadeTerminalEndpointsGetCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdGetResponseComposite & {
        headers: Headers;
    };

export const getCascadeTerminalEndpointsGetCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdGetUrl = (
    cascadeTerminalId: string
) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/cascade_terminal/${cascadeTerminalId}`;
};

export const cascadeTerminalEndpointsGetCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdGet = async (
    cascadeTerminalId: string,
    options?: RequestInit
): Promise<cascadeTerminalEndpointsGetCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdGetResponse> => {
    return authFetch<cascadeTerminalEndpointsGetCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdGetResponse>(
        getCascadeTerminalEndpointsGetCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdGetUrl(cascadeTerminalId),
        {
            ...options,
            method: "GET"
        }
    );
};

/**
 * Updates cascade terminal configuration
 * @summary Update cascade terminal
 */
export type cascadeTerminalEndpointsUpdateCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdPutResponse200 = {
    data: ApiResponseCascadeTerminalSchema;
    status: 200;
};

export type cascadeTerminalEndpointsUpdateCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdPutResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type cascadeTerminalEndpointsUpdateCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdPutResponseComposite =
    | cascadeTerminalEndpointsUpdateCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdPutResponse200
    | cascadeTerminalEndpointsUpdateCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdPutResponse422;

export type cascadeTerminalEndpointsUpdateCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdPutResponse =
    cascadeTerminalEndpointsUpdateCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdPutResponseComposite & {
        headers: Headers;
    };

export const getCascadeTerminalEndpointsUpdateCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdPutUrl = (
    cascadeTerminalId: string
) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/cascade_terminal/${cascadeTerminalId}`;
};

export const cascadeTerminalEndpointsUpdateCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdPut = async (
    cascadeTerminalId: string,
    cascadeTerminalUpdate: CascadeTerminalUpdate,
    options?: RequestInit
): Promise<cascadeTerminalEndpointsUpdateCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdPutResponse> => {
    return authFetch<cascadeTerminalEndpointsUpdateCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdPutResponse>(
        getCascadeTerminalEndpointsUpdateCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdPutUrl(
            cascadeTerminalId
        ),
        {
            ...options,
            method: "PUT",
            headers: { "Content-Type": "application/json", ...options?.headers },
            body: JSON.stringify(cascadeTerminalUpdate)
        }
    );
};

/**
 * Removes a terminal from a cascade
 * @summary Remove terminal from cascade
 */
export type cascadeTerminalEndpointsRemoveTerminalFromCascadeEnigmaV1CascadeTerminalCascadeTerminalIdDeleteResponse200 =
    {
        data: ApiResponseDictStrStr;
        status: 200;
    };

export type cascadeTerminalEndpointsRemoveTerminalFromCascadeEnigmaV1CascadeTerminalCascadeTerminalIdDeleteResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type cascadeTerminalEndpointsRemoveTerminalFromCascadeEnigmaV1CascadeTerminalCascadeTerminalIdDeleteResponseComposite =

        | cascadeTerminalEndpointsRemoveTerminalFromCascadeEnigmaV1CascadeTerminalCascadeTerminalIdDeleteResponse200
        | cascadeTerminalEndpointsRemoveTerminalFromCascadeEnigmaV1CascadeTerminalCascadeTerminalIdDeleteResponse422;

export type cascadeTerminalEndpointsRemoveTerminalFromCascadeEnigmaV1CascadeTerminalCascadeTerminalIdDeleteResponse =
    cascadeTerminalEndpointsRemoveTerminalFromCascadeEnigmaV1CascadeTerminalCascadeTerminalIdDeleteResponseComposite & {
        headers: Headers;
    };

export const getCascadeTerminalEndpointsRemoveTerminalFromCascadeEnigmaV1CascadeTerminalCascadeTerminalIdDeleteUrl = (
    cascadeTerminalId: string
) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/cascade_terminal/${cascadeTerminalId}`;
};

export const cascadeTerminalEndpointsRemoveTerminalFromCascadeEnigmaV1CascadeTerminalCascadeTerminalIdDelete = async (
    cascadeTerminalId: string,
    options?: RequestInit
): Promise<cascadeTerminalEndpointsRemoveTerminalFromCascadeEnigmaV1CascadeTerminalCascadeTerminalIdDeleteResponse> => {
    return authFetch<cascadeTerminalEndpointsRemoveTerminalFromCascadeEnigmaV1CascadeTerminalCascadeTerminalIdDeleteResponse>(
        getCascadeTerminalEndpointsRemoveTerminalFromCascadeEnigmaV1CascadeTerminalCascadeTerminalIdDeleteUrl(
            cascadeTerminalId
        ),
        {
            ...options,
            method: "DELETE"
        }
    );
};
