/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * BlowFish - Enigma API Service
 * OpenAPI spec version: local
 */
import type {
    ApiResponseCascadeTerminalRead,
    ApiResponseDictStrStr,
    ApiResponseOffsetPaginationCascadeTerminalRead,
    ApiResponseOffsetPaginationCascadeTerminalWithDetails,
    CascadeTerminalCreate,
    CascadeTerminalEndpointsListCascadesForTerminalEnigmaV1CascadeTerminalTerminalTerminalIdGetParams,
    CascadeTerminalEndpointsListTerminalsInCascadeEnigmaV1CascadeTerminalCascadeCascadeIdGetParams,
    CascadeTerminalUpdate,
    HTTPValidationError
} from "../blowFishEnigmaAPIService.schemas";

import { authFetch } from "../../../helpers/orvalAuthFetchMiddleware";

/**
 * Adds a terminal to a cascade with specified conditions
 * @summary Add terminal to cascade
 */
export type cascadeTerminalEndpointsCreateCascadeTerminalEnigmaV1CascadeTerminalPostResponse200 = {
    data: ApiResponseCascadeTerminalRead;
    status: 200;
};

export type cascadeTerminalEndpointsCreateCascadeTerminalEnigmaV1CascadeTerminalPostResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type cascadeTerminalEndpointsCreateCascadeTerminalEnigmaV1CascadeTerminalPostResponseComposite =
    | cascadeTerminalEndpointsCreateCascadeTerminalEnigmaV1CascadeTerminalPostResponse200
    | cascadeTerminalEndpointsCreateCascadeTerminalEnigmaV1CascadeTerminalPostResponse422;

export type cascadeTerminalEndpointsCreateCascadeTerminalEnigmaV1CascadeTerminalPostResponse =
    cascadeTerminalEndpointsCreateCascadeTerminalEnigmaV1CascadeTerminalPostResponseComposite & {
        headers: Headers;
    };

export const getCascadeTerminalEndpointsCreateCascadeTerminalEnigmaV1CascadeTerminalPostUrl = () => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/cascade_terminal`;
};

export const cascadeTerminalEndpointsCreateCascadeTerminalEnigmaV1CascadeTerminalPost = async (
    cascadeTerminalCreate: CascadeTerminalCreate,
    options?: RequestInit
): Promise<cascadeTerminalEndpointsCreateCascadeTerminalEnigmaV1CascadeTerminalPostResponse> => {
    return authFetch<cascadeTerminalEndpointsCreateCascadeTerminalEnigmaV1CascadeTerminalPostResponse>(
        getCascadeTerminalEndpointsCreateCascadeTerminalEnigmaV1CascadeTerminalPostUrl(),
        {
            ...options,
            method: "POST",
            headers: { "Content-Type": "application/json", ...options?.headers },
            body: JSON.stringify(cascadeTerminalCreate)
        }
    );
};

/**
 * Fetches details of a cascade terminal by its ID
 * @summary Get cascade terminal details
 */
export type cascadeTerminalEndpointsGetCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdGetResponse200 = {
    data: ApiResponseCascadeTerminalRead;
    status: 200;
};

export type cascadeTerminalEndpointsGetCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdGetResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type cascadeTerminalEndpointsGetCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdGetResponseComposite =
    | cascadeTerminalEndpointsGetCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdGetResponse200
    | cascadeTerminalEndpointsGetCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdGetResponse422;

export type cascadeTerminalEndpointsGetCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdGetResponse =
    cascadeTerminalEndpointsGetCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdGetResponseComposite & {
        headers: Headers;
    };

export const getCascadeTerminalEndpointsGetCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdGetUrl = (
    cascadeTerminalId: string
) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/cascade_terminal/${cascadeTerminalId}`;
};

export const cascadeTerminalEndpointsGetCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdGet = async (
    cascadeTerminalId: string,
    options?: RequestInit
): Promise<cascadeTerminalEndpointsGetCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdGetResponse> => {
    return authFetch<cascadeTerminalEndpointsGetCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdGetResponse>(
        getCascadeTerminalEndpointsGetCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdGetUrl(cascadeTerminalId),
        {
            ...options,
            method: "GET"
        }
    );
};

/**
 * Updates cascade terminal configuration
 * @summary Update cascade terminal
 */
export type cascadeTerminalEndpointsUpdateCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdPutResponse200 = {
    data: ApiResponseCascadeTerminalRead;
    status: 200;
};

export type cascadeTerminalEndpointsUpdateCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdPutResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type cascadeTerminalEndpointsUpdateCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdPutResponseComposite =
    | cascadeTerminalEndpointsUpdateCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdPutResponse200
    | cascadeTerminalEndpointsUpdateCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdPutResponse422;

export type cascadeTerminalEndpointsUpdateCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdPutResponse =
    cascadeTerminalEndpointsUpdateCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdPutResponseComposite & {
        headers: Headers;
    };

export const getCascadeTerminalEndpointsUpdateCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdPutUrl = (
    cascadeTerminalId: string
) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/cascade_terminal/${cascadeTerminalId}`;
};

export const cascadeTerminalEndpointsUpdateCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdPut = async (
    cascadeTerminalId: string,
    cascadeTerminalUpdate: CascadeTerminalUpdate,
    options?: RequestInit
): Promise<cascadeTerminalEndpointsUpdateCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdPutResponse> => {
    return authFetch<cascadeTerminalEndpointsUpdateCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdPutResponse>(
        getCascadeTerminalEndpointsUpdateCascadeTerminalEnigmaV1CascadeTerminalCascadeTerminalIdPutUrl(
            cascadeTerminalId
        ),
        {
            ...options,
            method: "PUT",
            headers: { "Content-Type": "application/json", ...options?.headers },
            body: JSON.stringify(cascadeTerminalUpdate)
        }
    );
};

/**
 * Removes a terminal from a cascade
 * @summary Remove terminal from cascade
 */
export type cascadeTerminalEndpointsRemoveTerminalFromCascadeEnigmaV1CascadeTerminalCascadeTerminalIdDeleteResponse200 =
    {
        data: ApiResponseDictStrStr;
        status: 200;
    };

export type cascadeTerminalEndpointsRemoveTerminalFromCascadeEnigmaV1CascadeTerminalCascadeTerminalIdDeleteResponse422 =
    {
        data: HTTPValidationError;
        status: 422;
    };

export type cascadeTerminalEndpointsRemoveTerminalFromCascadeEnigmaV1CascadeTerminalCascadeTerminalIdDeleteResponseComposite =

        | cascadeTerminalEndpointsRemoveTerminalFromCascadeEnigmaV1CascadeTerminalCascadeTerminalIdDeleteResponse200
        | cascadeTerminalEndpointsRemoveTerminalFromCascadeEnigmaV1CascadeTerminalCascadeTerminalIdDeleteResponse422;

export type cascadeTerminalEndpointsRemoveTerminalFromCascadeEnigmaV1CascadeTerminalCascadeTerminalIdDeleteResponse =
    cascadeTerminalEndpointsRemoveTerminalFromCascadeEnigmaV1CascadeTerminalCascadeTerminalIdDeleteResponseComposite & {
        headers: Headers;
    };

export const getCascadeTerminalEndpointsRemoveTerminalFromCascadeEnigmaV1CascadeTerminalCascadeTerminalIdDeleteUrl = (
    cascadeTerminalId: string
) => {
    return `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/cascade_terminal/${cascadeTerminalId}`;
};

export const cascadeTerminalEndpointsRemoveTerminalFromCascadeEnigmaV1CascadeTerminalCascadeTerminalIdDelete = async (
    cascadeTerminalId: string,
    options?: RequestInit
): Promise<cascadeTerminalEndpointsRemoveTerminalFromCascadeEnigmaV1CascadeTerminalCascadeTerminalIdDeleteResponse> => {
    return authFetch<cascadeTerminalEndpointsRemoveTerminalFromCascadeEnigmaV1CascadeTerminalCascadeTerminalIdDeleteResponse>(
        getCascadeTerminalEndpointsRemoveTerminalFromCascadeEnigmaV1CascadeTerminalCascadeTerminalIdDeleteUrl(
            cascadeTerminalId
        ),
        {
            ...options,
            method: "DELETE"
        }
    );
};

/**
 * Returns all terminals associated with a specific cascade
 * @summary Get terminals in cascade
 */
export type cascadeTerminalEndpointsListTerminalsInCascadeEnigmaV1CascadeTerminalCascadeCascadeIdGetResponse200 = {
    data: ApiResponseOffsetPaginationCascadeTerminalWithDetails;
    status: 200;
};

export type cascadeTerminalEndpointsListTerminalsInCascadeEnigmaV1CascadeTerminalCascadeCascadeIdGetResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type cascadeTerminalEndpointsListTerminalsInCascadeEnigmaV1CascadeTerminalCascadeCascadeIdGetResponseComposite =
    | cascadeTerminalEndpointsListTerminalsInCascadeEnigmaV1CascadeTerminalCascadeCascadeIdGetResponse200
    | cascadeTerminalEndpointsListTerminalsInCascadeEnigmaV1CascadeTerminalCascadeCascadeIdGetResponse422;

export type cascadeTerminalEndpointsListTerminalsInCascadeEnigmaV1CascadeTerminalCascadeCascadeIdGetResponse =
    cascadeTerminalEndpointsListTerminalsInCascadeEnigmaV1CascadeTerminalCascadeCascadeIdGetResponseComposite & {
        headers: Headers;
    };

export const getCascadeTerminalEndpointsListTerminalsInCascadeEnigmaV1CascadeTerminalCascadeCascadeIdGetUrl = (
    cascadeId: string,
    params: CascadeTerminalEndpointsListTerminalsInCascadeEnigmaV1CascadeTerminalCascadeCascadeIdGetParams
) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? "null" : value.toString());
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/cascade_terminal/cascade/${cascadeId}?${stringifiedParams}`
        : `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/cascade_terminal/cascade/${cascadeId}`;
};

export const cascadeTerminalEndpointsListTerminalsInCascadeEnigmaV1CascadeTerminalCascadeCascadeIdGet = async (
    cascadeId: string,
    params: CascadeTerminalEndpointsListTerminalsInCascadeEnigmaV1CascadeTerminalCascadeCascadeIdGetParams,
    options?: RequestInit
): Promise<cascadeTerminalEndpointsListTerminalsInCascadeEnigmaV1CascadeTerminalCascadeCascadeIdGetResponse> => {
    return authFetch<cascadeTerminalEndpointsListTerminalsInCascadeEnigmaV1CascadeTerminalCascadeCascadeIdGetResponse>(
        getCascadeTerminalEndpointsListTerminalsInCascadeEnigmaV1CascadeTerminalCascadeCascadeIdGetUrl(
            cascadeId,
            params
        ),
        {
            ...options,
            method: "GET"
        }
    );
};

/**
 * Returns all cascades that include a specific terminal
 * @summary Get cascades for terminal
 */
export type cascadeTerminalEndpointsListCascadesForTerminalEnigmaV1CascadeTerminalTerminalTerminalIdGetResponse200 = {
    data: ApiResponseOffsetPaginationCascadeTerminalRead;
    status: 200;
};

export type cascadeTerminalEndpointsListCascadesForTerminalEnigmaV1CascadeTerminalTerminalTerminalIdGetResponse422 = {
    data: HTTPValidationError;
    status: 422;
};

export type cascadeTerminalEndpointsListCascadesForTerminalEnigmaV1CascadeTerminalTerminalTerminalIdGetResponseComposite =

        | cascadeTerminalEndpointsListCascadesForTerminalEnigmaV1CascadeTerminalTerminalTerminalIdGetResponse200
        | cascadeTerminalEndpointsListCascadesForTerminalEnigmaV1CascadeTerminalTerminalTerminalIdGetResponse422;

export type cascadeTerminalEndpointsListCascadesForTerminalEnigmaV1CascadeTerminalTerminalTerminalIdGetResponse =
    cascadeTerminalEndpointsListCascadesForTerminalEnigmaV1CascadeTerminalTerminalTerminalIdGetResponseComposite & {
        headers: Headers;
    };

export const getCascadeTerminalEndpointsListCascadesForTerminalEnigmaV1CascadeTerminalTerminalTerminalIdGetUrl = (
    terminalId: string,
    params: CascadeTerminalEndpointsListCascadesForTerminalEnigmaV1CascadeTerminalTerminalTerminalIdGetParams
) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(key, value === null ? "null" : value.toString());
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/cascade_terminal/terminal/${terminalId}?${stringifiedParams}`
        : `https://apigate.develop.blowfish.api4ftx.cloud/enigma/v1/cascade_terminal/terminal/${terminalId}`;
};

export const cascadeTerminalEndpointsListCascadesForTerminalEnigmaV1CascadeTerminalTerminalTerminalIdGet = async (
    terminalId: string,
    params: CascadeTerminalEndpointsListCascadesForTerminalEnigmaV1CascadeTerminalTerminalTerminalIdGetParams,
    options?: RequestInit
): Promise<cascadeTerminalEndpointsListCascadesForTerminalEnigmaV1CascadeTerminalTerminalTerminalIdGetResponse> => {
    return authFetch<cascadeTerminalEndpointsListCascadesForTerminalEnigmaV1CascadeTerminalTerminalTerminalIdGetResponse>(
        getCascadeTerminalEndpointsListCascadesForTerminalEnigmaV1CascadeTerminalTerminalTerminalIdGetUrl(
            terminalId,
            params
        ),
        {
            ...options,
            method: "GET"
        }
    );
};
